# 📊 YouTube Trending Videos Analytics using SQL

## 🗄️ SQL Business Analytics Project

This project performs **SQL-based business analysis** on YouTube Trending Videos data.

The objective is to analyze video performance, audience engagement, content characteristics, publishing behavior, NLP-derived features, and channel performance using **SQLite and SQL queries**.

<div align="center">

<img src="https://th.bing.com/th/id/OIP.VDoCtgMoTijXbq1P73PuFgHaEZ?w=299&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3" width="100%" alt="YouTube Trending Videos Analytics using SQL">

</div>

---

## 🎯 Project Objectives

- Analyze trending video performance
- Identify high-performing videos and channels
- Compare category-wise performance
- Analyze views, likes, and comments
- Measure engagement, like rate, and comment rate
- Analyze publishing time and day patterns
- Study video quality and caption availability
- Analyze title and description characteristics
- Analyze hashtags, tags, and URLs
- Extract actionable business insights using SQL

---

## 🗃️ Dataset Information

**Database:** `trending_videos.db`

**Table:** `trending_videos`

**Total Records:** 199 Videos

---

## 📌 Dataset Columns

### 🎥 Video Information

| ColumnDescription |                             |
| ----------------- | --------------------------- |
| `video_id`        | Unique video identifier     |
| `title`           | Video title                 |
| `description`     | Video description           |
| `channel_id`      | Unique channel identifier   |
| `channel_title`   | Channel name                |
| `category_id`     | YouTube category identifier |
| `category_name`   | Category name               |

### 📅 Publishing Information

| Column               | Description                           |
| -------------------- | ------------------------------------- |
| `published_at`       | Original publishing timestamp         |
| `published_at_date`  | Publishing date                       |
| `publish_year`       | Publishing year                       |
| `publish_month`      | Publishing month                      |
| `publish_month_name` | Month name                            |
| `publish_day`        | Day number                            |
| `publish_day_name`   | Day name                              |
| `publish_week`       | Week number                           |
| `publish_hour`       | Publishing hour                       |
| `publish_minute`     | Publishing minute                     |
| `publish_second`     | Publishing second                     |
| `publish_session`    | Morning / Afternoon / Evening / Night |
| `is_weekend`         | Weekend indicator                     |
| `weekend_flag`       | Weekend classification                |

### 📈 Performance Metrics

| Column             | Description              |
| ------------------ | ------------------------ |
| `view_count`       | Total video views        |
| `like_count`       | Total likes              |
| `comment_count`    | Total comments           |
| `favorite_count`   | Favorite count           |
| `engagement_score` | Overall engagement score |
| `engagement_rate`  | Engagement percentage    |
| `like_rate`        | Like-to-view rate        |
| `comment_rate`     | Comment-to-view rate     |

### 🎬 Video Attributes

| Column              | Description          |
| ------------------- | -------------------- |
| `duration`          | Video duration       |
| `duration_seconds`  | Duration in seconds  |
| `duration_category` | Video duration group |
| `definition`        | Video quality        |
| `is_hd`             | HD indicator         |
| `caption`           | Caption availability |
| `has_caption`       | Caption flag         |

### 🔗 URL / Hashtag / Tag Features

| Column          | Description         |
| --------------- | ------------------- |
| `urls_links`    | Extracted URLs      |
| `url_count`     | Number of URLs      |
| `url_types`     | URL platform/type   |
| `hashtags`      | Extracted hashtags  |
| `hashtag_count` | Number of hashtags  |
| `tags`          | Original video tags |
| `tags_clean`    | Cleaned tags        |
| `tag_count`     | Number of tags      |

### 📝 NLP / Text Features

| Column                   | Description                      |
| ------------------------ | -------------------------------- |
| `clean_description`      | Cleaned description text         |
| `tokens`                 | Tokenized text                   |
| `processed_text`         | NLP processed text               |
| `title_length`           | Number of title characters       |
| `title_word_count`       | Number of title words            |
| `description_length`     | Number of description characters |
| `description_word_count` | Number of description words      |

---

## 🔍 SQL Analysis Areas

### 📊 Performance Analysis

- Top videos by views
- Top videos by likes
- Top videos by comments
- Highest engagement videos
- Like rate analysis
- Comment rate analysis

### 📺 Channel Analysis

- Top channels by total views
- Top channels by average engagement
- Most frequently trending channels
- High-reach and high-engagement channels

### 🗂️ Category Analysis

- Category distribution
- Average views by category
- Average likes by category
- Average comments by category
- Overall category performance

### 🕐 Publishing Analysis

- Best publishing hour
- Best publishing day
- Weekend vs weekday performance
- Publishing session analysis

### 📝 NLP / Content Analysis

- Title length analysis
- Description length analysis
- Tag count analysis
- Hashtag count analysis
- URL usage analysis
- Content length vs engagement

---

## 🛠️ Technologies Used

- Python
- Pandas
- SQLite
- SQL
- Jupyter Notebook
- NumPy
- Matplotlib
- Seaborn
- NLP / Text Processing

---

## 💼 Business Questions

This project answers business questions such as:

- Which videos generate the highest reach?
- Which channels consistently perform well?
- Which categories attract the highest engagement?
- What publishing time produces better performance?
- Do HD videos perform better?
- Does caption availability influence engagement?
- Does title length affect engagement?
- Do hashtags and tags contribute to performance?
- Which content characteristics are associated with higher views?
- Which channels have both high reach and high engagement?

---

## 📌 Final Outcome

The analysis transforms raw YouTube video data into **business-oriented insights** that can help content creators, marketers, and media teams understand:

**Reach → Engagement → Content Strategy → Publishing Strategy → Channel Performance**

---

## 🚀 Project Workflow

Raw Dataset
↓
Data Cleaning
↓
Feature Engineering
↓
NLP / Text Processing
↓
SQLite Database
↓
SQL Analysis
↓
Business Questions
↓
Insights & Recommendations

In [1]:
# import library's for using sql execution's

import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("trending_videos.db")

print("SQLite database connected successfully!")

SQLite database connected successfully!

In [3]:
tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    """,
    conn
)

display(tables)

              name
0  trending_videos

In [4]:
data = pd.read_sql_query(
    """
    SELECT *
    FROM trending_videos
    LIMIT 10
    """,
    conn
)

display(data)

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,definition,...,has_caption,view_bucket,month_part,popular_category,weekend_flag,upload_time,category_name,log_view_count,log_like_count,log_comment_count
0,Bz4Uzthytss,"Stray Kids ""This & That"" M/V","Stray Kids( ) ""This & That"" M/V Listen to ""THI...",2026-08-07 04:00:01+00:00,UCaO6TYtlC8U5ttz62hTrZgg,JYP Entertainment,10,"[""JYP Entertainment"", ""JYP"", ""Stray Kids"", ""스트...",PT3M14S,hd,...,1,Very High,Beginning,0,0,Late Night,Music,14.951791,13.221649,11.086609
1,5Fhxyqqokl8,Primetime | Official Trailer HD | A24,SUBSCRIBE: From director Lance Oppenheim and s...,2026-08-06 13:00:36+00:00,UCuPivVjnfNo4mb3Oog_frZg,A24,1,"[""a24"", ""a24 films"", ""a24 trailers"", ""independ...",PT2M17S,hd,...,0,Very High,Beginning,0,0,Afternoon,Film & Animation,15.231577,11.746613,9.099744
2,O4Oeg34Sslq,Pooh Shiesty - Reap What You Sow [Official Audio],FOR ENTERTAINMENT PURPOSES ONLY Pooh Shiesty -...,2026-08-07 04:00:19+00:00,UCTBIIbIs83IBsy4E1BQxYBw,Pooh Shiesty,10,"[""pooh shiesty"", ""pooh sheisty"", ""pooh"", ""shie...",PT3M38S,hd,...,0,Low,Beginning,0,0,Late Night,Music,10.612114,8.297793,5.743003
3,I2Zohquncbo,Tough Call | D.Mon Hero Trailer | Overwatch,"Every hero needs a squad, and every squad need...",2026-08-06 16:00:06+00:00,UClOf1XXinvZsy4wKPAkro2A,PlayOverwatch,20,"[""Overwatch 2"", ""Overwatch""]",PT2M35S,hd,...,1,Very High,Beginning,1,0,Afternoon,Gaming,13.686994,10.831391,8.431853
4,Qq76Pqsi1Iw,Grand Theft Auto VI: An Extended Look Coming A...,Grand Theft Auto VI: An Extended Look will pre...,2026-08-06 12:00:25+00:00,UC6VcWc1rAoWdBCM0JxrRQ3A,Rockstar Games,20,"[""Grand Theft Auto VI"", ""Grand Theft Auto 6"", ...",PT26S,hd,...,0,Very High,Beginning,1,0,Afternoon,Gaming,14.858825,12.462237,10.030076
5,Pq7Ibyc9Cys,"KAROL G, Drake - Ahí (Visualizer)",Escucha / Stream ‘NO ME ARREPIENTO DE SENTIR T...,2026-08-07 04:00:13+00:00,UCz9yS18zJGQObwUL_K-ICnw,KarolGVEVO,10,"[""karol g"", ""karolg"", ""bichota"", ""matadora"", ""...",PT2M57S,hd,...,0,Medium,Beginning,0,0,Late Night,Music,11.651591,9.777981,7.362011
6,2Uf4Pcge8Ga,Quake: Dawn of the Machine — Launch Trailer,Quake™: Dawn of the Machine is available now! ...,2026-08-06 18:06:42+00:00,UCvZHe-SP3xC7DdOk4Ri8QBw,Bethesda Softworks,20,"[""Bethesda Softworks"", ""Quake"", ""id Software"",...",PT1M,hd,...,0,Very High,Beginning,1,0,Evening,Gaming,12.764528,9.875500,7.708860
7,-Tanwotw0Bc,🔴LIVE | TARKOV SEASONAL | DAY 4 | HutchMF x GI...,,2026-08-07 08:48:26+00:00,UCMNEVbszv8ZyvSXoTn3yhpQ,TheBurntPeanut,20,"[""funny"", ""escape from tarkov"", ""tarkov""]",PT8H18M25S,hd,...,0,Very High,Beginning,1,0,Morning,Gaming,12.922336,8.827321,2.708050
8,Hcvizzvdeq8,FARMING,Provided to YouTube by JYP Entertainment Corpo...,2026-07-10 14:04:27+00:00,UCIMmuidNJdncfMEelOU08Fg,Stray Kids - Topic,10,"[""Stray Kids"", ""RESTART"", ""Chae Ganghae"", ""채강해...",PT2M31S,hd,...,0,High,Beginning,0,0,Afternoon,Music,12.381756,11.067825,8.190909
9,Ixa7Bmrbbxs,THE ONLY LIVING PICKPOCKET IN NEW YORK | Offic...,A love-letter to New York City. Watch the offi...,2026-08-06 15:00:56+00:00,UCruD_lL-5fmllpKMSL-yCyQ,Sony Pictures Classics,24,[],PT2M18S,hd,...,1,Very High,Beginning,0,0,Afternoon,Entertainment,12.796298,8.970813,6.424869

In [5]:
df = pd.read_sql("""
    select * from trending_videos
    """,
    conn
                )

In [6]:
print(f"Data size is {df.size} and Data Shape is {df.shape} ")

Data size is 11144 and Data Shape is (199, 56)

# BASIC DATA CHECKS — 1 to 10

In [7]:
# 1. Total number of rows

pd.read_sql_query("""
SELECT COUNT(*) AS total_rows
FROM trending_videos;
""", conn)

   total_rows
0         199

In [8]:
# 2. Total number of columns

pd.read_sql_query("""
PRAGMA table_info(trending_videos);
""", conn)

    cid                    name       type  notnull dflt_value  pk
0     0                video_id       TEXT        0       None   0
1     1                   title       TEXT        0       None   0
2     2             description       TEXT        0       None   0
3     3            published_at  TIMESTAMP        0       None   0
4     4              channel_id       TEXT        0       None   0
5     5           channel_title       TEXT        0       None   0
6     6             category_id    INTEGER        0       None   0
7     7                    tags       TEXT        0       None   0
8     8                duration       TEXT        0       None   0
9     9              definition       TEXT        0       None   0
10   10                 caption       TEXT        0       None   0
11   11              view_count    INTEGER        0       None   0
12   12              like_count    INTEGER        0       None   0
13   13           comment_count    INTEGER        0       None   0
14   14              urls_links       TEXT        0       None   0
15   15               url_count    INTEGER        0       None   0
16   16               url_types       TEXT        0       None   0
17   17                hashtags       TEXT        0       None   0
18   18           hashtag_count    INTEGER        0       None   0
19   19       clean_description       TEXT        0       None   0
20   20              tags_clean       TEXT        0       None   0
21   21               tag_count    INTEGER        0       None   0
22   22       published_at_date       DATE        0       None   0
23   23           publish_month    INTEGER        0       None   0
24   24      publish_month_name       TEXT        0       None   0
25   25             publish_day    INTEGER        0       None   0
26   26        publish_day_name       TEXT        0       None   0
27   27            publish_week    INTEGER        0       None   0
28   28              is_weekend    INTEGER        0       None   0
29   29            publish_hour    INTEGER        0       None   0
30   30          publish_minute    INTEGER        0       None   0
31   31          publish_second    INTEGER        0       None   0
32   32                  tokens       TEXT        0       None   0
33   33          processed_text       TEXT        0       None   0
34   34        duration_seconds       REAL        0       None   0
35   35       duration_category       TEXT        0       None   0
36   36            title_length    INTEGER        0       None   0
37   37        title_word_count    INTEGER        0       None   0
38   38      description_length    INTEGER        0       None   0
39   39  description_word_count    INTEGER        0       None   0
40   40         publish_session       TEXT        0       None   0
41   41        engagement_score    INTEGER        0       None   0
42   42               like_rate       REAL        0       None   0
43   43            comment_rate       REAL        0       None   0
44   44         engagement_rate       REAL        0       None   0
45   45                   is_hd    INTEGER        0       None   0
46   46             has_caption    INTEGER        0       None   0
47   47             view_bucket       TEXT        0       None   0
48   48              month_part       TEXT        0       None   0
49   49        popular_category    INTEGER        0       None   0
50   50            weekend_flag    INTEGER        0       None   0
51   51             upload_time       TEXT        0       None   0
52   52           category_name       TEXT        0       None   0
53   53          log_view_count       REAL        0       None   0
54   54          log_like_count       REAL        0       None   0
55   55       log_comment_count       REAL        0       None   0

In [9]:
# 3. First 10 rows

pd.read_sql_query("""
SELECT *
FROM trending_videos
LIMIT 10;
""", conn)

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,definition,...,has_caption,view_bucket,month_part,popular_category,weekend_flag,upload_time,category_name,log_view_count,log_like_count,log_comment_count
0,Bz4Uzthytss,"Stray Kids ""This & That"" M/V","Stray Kids( ) ""This & That"" M/V Listen to ""THI...",2026-08-07 04:00:01+00:00,UCaO6TYtlC8U5ttz62hTrZgg,JYP Entertainment,10,"[""JYP Entertainment"", ""JYP"", ""Stray Kids"", ""스트...",PT3M14S,hd,...,1,Very High,Beginning,0,0,Late Night,Music,14.951791,13.221649,11.086609
1,5Fhxyqqokl8,Primetime | Official Trailer HD | A24,SUBSCRIBE: From director Lance Oppenheim and s...,2026-08-06 13:00:36+00:00,UCuPivVjnfNo4mb3Oog_frZg,A24,1,"[""a24"", ""a24 films"", ""a24 trailers"", ""independ...",PT2M17S,hd,...,0,Very High,Beginning,0,0,Afternoon,Film & Animation,15.231577,11.746613,9.099744
2,O4Oeg34Sslq,Pooh Shiesty - Reap What You Sow [Official Audio],FOR ENTERTAINMENT PURPOSES ONLY Pooh Shiesty -...,2026-08-07 04:00:19+00:00,UCTBIIbIs83IBsy4E1BQxYBw,Pooh Shiesty,10,"[""pooh shiesty"", ""pooh sheisty"", ""pooh"", ""shie...",PT3M38S,hd,...,0,Low,Beginning,0,0,Late Night,Music,10.612114,8.297793,5.743003
3,I2Zohquncbo,Tough Call | D.Mon Hero Trailer | Overwatch,"Every hero needs a squad, and every squad need...",2026-08-06 16:00:06+00:00,UClOf1XXinvZsy4wKPAkro2A,PlayOverwatch,20,"[""Overwatch 2"", ""Overwatch""]",PT2M35S,hd,...,1,Very High,Beginning,1,0,Afternoon,Gaming,13.686994,10.831391,8.431853
4,Qq76Pqsi1Iw,Grand Theft Auto VI: An Extended Look Coming A...,Grand Theft Auto VI: An Extended Look will pre...,2026-08-06 12:00:25+00:00,UC6VcWc1rAoWdBCM0JxrRQ3A,Rockstar Games,20,"[""Grand Theft Auto VI"", ""Grand Theft Auto 6"", ...",PT26S,hd,...,0,Very High,Beginning,1,0,Afternoon,Gaming,14.858825,12.462237,10.030076
5,Pq7Ibyc9Cys,"KAROL G, Drake - Ahí (Visualizer)",Escucha / Stream ‘NO ME ARREPIENTO DE SENTIR T...,2026-08-07 04:00:13+00:00,UCz9yS18zJGQObwUL_K-ICnw,KarolGVEVO,10,"[""karol g"", ""karolg"", ""bichota"", ""matadora"", ""...",PT2M57S,hd,...,0,Medium,Beginning,0,0,Late Night,Music,11.651591,9.777981,7.362011
6,2Uf4Pcge8Ga,Quake: Dawn of the Machine — Launch Trailer,Quake™: Dawn of the Machine is available now! ...,2026-08-06 18:06:42+00:00,UCvZHe-SP3xC7DdOk4Ri8QBw,Bethesda Softworks,20,"[""Bethesda Softworks"", ""Quake"", ""id Software"",...",PT1M,hd,...,0,Very High,Beginning,1,0,Evening,Gaming,12.764528,9.875500,7.708860
7,-Tanwotw0Bc,🔴LIVE | TARKOV SEASONAL | DAY 4 | HutchMF x GI...,,2026-08-07 08:48:26+00:00,UCMNEVbszv8ZyvSXoTn3yhpQ,TheBurntPeanut,20,"[""funny"", ""escape from tarkov"", ""tarkov""]",PT8H18M25S,hd,...,0,Very High,Beginning,1,0,Morning,Gaming,12.922336,8.827321,2.708050
8,Hcvizzvdeq8,FARMING,Provided to YouTube by JYP Entertainment Corpo...,2026-07-10 14:04:27+00:00,UCIMmuidNJdncfMEelOU08Fg,Stray Kids - Topic,10,"[""Stray Kids"", ""RESTART"", ""Chae Ganghae"", ""채강해...",PT2M31S,hd,...,0,High,Beginning,0,0,Afternoon,Music,12.381756,11.067825,8.190909
9,Ixa7Bmrbbxs,THE ONLY LIVING PICKPOCKET IN NEW YORK | Offic...,A love-letter to New York City. Watch the offi...,2026-08-06 15:00:56+00:00,UCruD_lL-5fmllpKMSL-yCyQ,Sony Pictures Classics,24,[],PT2M18S,hd,...,1,Very High,Beginning,0,0,Afternoon,Entertainment,12.796298,8.970813,6.424869

In [10]:
# 4. Last 10 rows

pd.read_sql_query("""
SELECT *
FROM trending_videos
ORDER BY rowid DESC
LIMIT 10;
""", conn)

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,definition,...,has_caption,view_bucket,month_part,popular_category,weekend_flag,upload_time,category_name,log_view_count,log_like_count,log_comment_count
0,Xdlklxkqccu,Spiff's first* playthrough of FNAF 4 and FNAF:...,THIS CHANNEL IS UNOFFICIAL AND FAN MANAGED Som...,2026-08-06 15:00:18+00:00,UCVvmyRG-p-aoZ10AJ9Q3qbw,AstralPlink,22,[],PT3H31M39S,hd,...,0,Low,Beginning,0,0,Afternoon,People & Blogs,10.068069,6.637258,4.369448
1,Ddqysefzwms,🚨🍀EXPOSING THE #1 HACKER ON WARZONE REBIRTH IS...,EXPOSING THE HACKER ON WARZONE REBIRTH ISLAND ...,2026-08-07 06:05:54+00:00,UCAtGANLX7I5N4wOBLH8Yq8Q,Lucky Chamu,20,"[""lucky chamu"", ""lucky chamu warzone"", ""lucky ...",PT3H14M30S,hd,...,0,Low,Beginning,1,0,Morning,Gaming,9.545383,4.718499,0.000000
2,P5B7M0Awzdk,Best Friends BiRTHDAY SURPRiSE in Berry Avenue...,Adley's Roblox BiRTHDAY went CRAZY!! JOIN THE ...,2026-08-06 13:00:29+00:00,UCo0NaLsgPT6JrQLQGecpMyw,G for Gaming,24,"[""g for gaming"", ""a for adley"", ""shonduras"", ""...",PT41M27S,hd,...,0,Medium,Beginning,0,0,Afternoon,Entertainment,11.508927,7.197435,6.302619
3,Zc9Oh3Xuhce,Black Ops 2 Sweats HATE Rapid Fire SMGs,"Toxic raging sweats, creative emblems, I am ho...",2026-08-06 17:37:15+00:00,UCJhkqWiq7wI3BCXz2IwOqng,Tmal,20,"[""Video"", ""Free"", ""Camera"", ""Photo"", ""Sharing""...",PT10M59S,sd,...,0,Medium,Beginning,1,0,Afternoon,Gaming,11.399387,8.376551,6.045005
4,Anqurgdkd4G,I Played 100% of Jazzpunk. I Have No Words,I played 100% of Jazzpunk and what on earth ju...,2026-08-06 12:00:11+00:00,UCO9XZbb3iTp4l5dsLkW8Z1w,Floydsonson,20,"[""floydson"", ""floydsonson"", ""full game"", ""100%...",PT1H30M15S,hd,...,0,High,Beginning,1,0,Afternoon,Gaming,11.736789,8.318986,5.252273
5,Hmmfrwe2Z4E,VANOSS helps me TROLL Wildcat in Big Walk,We couldn't help ourselves... SUBSCRIBE & CLIC...,2026-08-06 19:44:10+00:00,UCQiojTHkAvFvdCSajklqUXA,Terroriser,20,"[""big walk update"", ""big walk gameplay"", ""big ...",PT31M34S,hd,...,0,Low,Beginning,1,0,Evening,Gaming,10.848249,8.203851,4.779123
6,Llbxf4N1R78,All This NEW Stuff Just Added to College Footb...,"In this College Football 27 video, I'll show a...",2026-08-07 02:23:15+00:00,UCq_2n18CJaRVGxEfxtCfI-Q,EricRayweather,20,"[""eric rayweather"", ""ericrayweather"", ""eric ra...",PT9M47S,hd,...,0,Low,Beginning,1,0,Late Night,Gaming,10.238959,6.934397,4.955827
7,Imobxwibj0Y,Persona 4 Revival — Yukiko Sizzle,She’ll give it her all Take on the mystery of ...,2026-08-07 00:00:38+00:00,UC7hgDFSPvJVIUx_b8i1cILA,Official ATLUS West,20,[],PT1M28S,hd,...,0,Medium,Beginning,1,0,Late Night,Gaming,11.195128,8.846641,6.396930
8,Mtr5Priz8Ti,cartoon animal game of the year (Zoominoes),Zoominoes on Steam: This video came from my st...,2026-08-06 17:00:16+00:00,UC3tNpTOHsTnkmbwztCs30sA,Northernlion,20,[],PT56M6S,hd,...,0,Low,Beginning,1,0,Afternoon,Gaming,11.045095,7.431300,5.105945
9,4_Hvmk5Fi6E,WATCHING NA EVAL CUP FINALS 🏆 NEW UPDATE? 👀,WATCHING EVAL CUP FINALS NEW UPDATE? Aussie An...,2026-08-07 04:33:35+00:00,UC5aATYG-mEny8VBUzf2TIjQ,AussieAntics,24,"[""fortnite"", ""fortnite battle royale"", ""epic g...",PT9H7M25S,hd,...,0,Medium,Beginning,0,0,Late Night,Entertainment,11.608272,7.108244,1.609438

In [11]:
# 5. Table structure

pd.read_sql_query("""
PRAGMA table_info(trending_videos);
""", conn)

    cid                    name       type  notnull dflt_value  pk
0     0                video_id       TEXT        0       None   0
1     1                   title       TEXT        0       None   0
2     2             description       TEXT        0       None   0
3     3            published_at  TIMESTAMP        0       None   0
4     4              channel_id       TEXT        0       None   0
5     5           channel_title       TEXT        0       None   0
6     6             category_id    INTEGER        0       None   0
7     7                    tags       TEXT        0       None   0
8     8                duration       TEXT        0       None   0
9     9              definition       TEXT        0       None   0
10   10                 caption       TEXT        0       None   0
11   11              view_count    INTEGER        0       None   0
12   12              like_count    INTEGER        0       None   0
13   13           comment_count    INTEGER        0       None   0
14   14              urls_links       TEXT        0       None   0
15   15               url_count    INTEGER        0       None   0
16   16               url_types       TEXT        0       None   0
17   17                hashtags       TEXT        0       None   0
18   18           hashtag_count    INTEGER        0       None   0
19   19       clean_description       TEXT        0       None   0
20   20              tags_clean       TEXT        0       None   0
21   21               tag_count    INTEGER        0       None   0
22   22       published_at_date       DATE        0       None   0
23   23           publish_month    INTEGER        0       None   0
24   24      publish_month_name       TEXT        0       None   0
25   25             publish_day    INTEGER        0       None   0
26   26        publish_day_name       TEXT        0       None   0
27   27            publish_week    INTEGER        0       None   0
28   28              is_weekend    INTEGER        0       None   0
29   29            publish_hour    INTEGER        0       None   0
30   30          publish_minute    INTEGER        0       None   0
31   31          publish_second    INTEGER        0       None   0
32   32                  tokens       TEXT        0       None   0
33   33          processed_text       TEXT        0       None   0
34   34        duration_seconds       REAL        0       None   0
35   35       duration_category       TEXT        0       None   0
36   36            title_length    INTEGER        0       None   0
37   37        title_word_count    INTEGER        0       None   0
38   38      description_length    INTEGER        0       None   0
39   39  description_word_count    INTEGER        0       None   0
40   40         publish_session       TEXT        0       None   0
41   41        engagement_score    INTEGER        0       None   0
42   42               like_rate       REAL        0       None   0
43   43            comment_rate       REAL        0       None   0
44   44         engagement_rate       REAL        0       None   0
45   45                   is_hd    INTEGER        0       None   0
46   46             has_caption    INTEGER        0       None   0
47   47             view_bucket       TEXT        0       None   0
48   48              month_part       TEXT        0       None   0
49   49        popular_category    INTEGER        0       None   0
50   50            weekend_flag    INTEGER        0       None   0
51   51             upload_time       TEXT        0       None   0
52   52           category_name       TEXT        0       None   0
53   53          log_view_count       REAL        0       None   0
54   54          log_like_count       REAL        0       None   0
55   55       log_comment_count       REAL        0       None   0

In [12]:
# 6. Unique video IDs

pd.read_sql_query("""
SELECT COUNT(DISTINCT video_id) AS unique_video_ids
FROM trending_videos;
""", conn)

   unique_video_ids
0               199

In [13]:
# 7. Duplicate video IDs

pd.read_sql_query("""
SELECT
    video_id,
    COUNT(*) AS duplicate_count
FROM trending_videos
GROUP BY video_id
HAVING COUNT(*) > 1;
""", conn)

Empty DataFrame
Columns: [video_id, duplicate_count]
Index: []

In [14]:
# 8. Total distinct channels

pd.read_sql_query("""
SELECT COUNT(DISTINCT channel_title) AS unique_channels
FROM trending_videos;
""", conn)

   unique_channels
0              199

In [15]:
# 9. Total categories

pd.read_sql_query("""
SELECT COUNT(DISTINCT category_name) AS unique_categories
FROM trending_videos;
""", conn)

   unique_categories
0                  8

In [16]:
# 10. Earliest and latest published dates

pd.read_sql_query("""
SELECT
    MIN(published_at_date) AS earliest_date,
    MAX(published_at_date) AS latest_date
FROM trending_videos;
""", conn)

  earliest_date latest_date
0    2026-07-10  2026-08-07

# NULL / MISSING VALUE ANALYSIS — 11 to 20

In [17]:
# 11. Missing video IDs

pd.read_sql_query("""
SELECT COUNT(*) AS missing_video_id
FROM trending_videos
WHERE video_id IS NULL;
""", conn)

   missing_video_id
0                 0

In [18]:
# 12. Missing titles

pd.read_sql_query("""
SELECT COUNT(*) AS missing_titles
FROM trending_videos
WHERE title IS NULL;
""", conn)

   missing_titles
0               0

In [19]:
# 13. Missing descriptions

pd.read_sql_query("""
SELECT COUNT(*) AS missing_descriptions
FROM trending_videos
WHERE description IS NULL;
""", conn)

   missing_descriptions
0                     0

In [20]:
# 14. Missing channel names

pd.read_sql_query("""
SELECT COUNT(*) AS missing_channels
FROM trending_videos
WHERE channel_title IS NULL;
""", conn)

   missing_channels
0                 0

In [21]:
# 15. Missing view counts

pd.read_sql_query("""
SELECT COUNT(*) AS missing_views
FROM trending_videos
WHERE view_count IS NULL;
""", conn)

   missing_views
0              0

In [22]:
# 16. Missing likes

pd.read_sql_query("""
SELECT COUNT(*) AS missing_likes
FROM trending_videos
WHERE like_count IS NULL;
""", conn)

   missing_likes
0              0

In [23]:
# 17. Missing comments

pd.read_sql_query("""
SELECT COUNT(*) AS missing_comments
FROM trending_videos
WHERE comment_count IS NULL;
""", conn)

   missing_comments
0                 0

In [24]:
# 18. Missing URL links

pd.read_sql_query("""
SELECT COUNT(*) AS missing_urls
FROM trending_videos
WHERE urls_links IS NULL;
""", conn)

   missing_urls
0            22

In [25]:
# 19. Missing hashtags

pd.read_sql_query("""
SELECT COUNT(*) AS missing_hashtags
FROM trending_videos
WHERE hashtags IS NULL;
""", conn)

   missing_hashtags
0                 0

In [26]:
# 20. Missing values for important columns

pd.read_sql_query("""
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN video_id IS NULL THEN 1 ELSE 0 END) AS missing_video_id,
    SUM(CASE WHEN title IS NULL THEN 1 ELSE 0 END) AS missing_title,
    SUM(CASE WHEN description IS NULL THEN 1 ELSE 0 END) AS missing_description,
    SUM(CASE WHEN view_count IS NULL THEN 1 ELSE 0 END) AS missing_views,
    SUM(CASE WHEN like_count IS NULL THEN 1 ELSE 0 END) AS missing_likes,
    SUM(CASE WHEN comment_count IS NULL THEN 1 ELSE 0 END) AS missing_comments
FROM trending_videos;
""", conn)

,total_rows,missing_video_id,missing_title,missing_description,missing_views,missing_likes,missing_comments
0,199,0,0,0,0,0,0

# STATISTICAL ANALYSIS — 21 to 30

In [27]:
# 21. Minimum views

pd.read_sql_query("""
SELECT MIN(view_count) AS minimum_views
FROM trending_videos;
""", conn)

   minimum_views
0           6569

In [28]:
# 22. Maximum views

pd.read_sql_query("""
SELECT MAX(view_count) AS maximum_views
FROM trending_videos;
""", conn)

   maximum_views
0        4929447

In [29]:
# 23. Average views

pd.read_sql_query("""
SELECT ROUND(AVG(view_count), 2) AS average_views
FROM trending_videos;
""", conn)

   average_views
0      285063.72

In [30]:
# 24. Total views

pd.read_sql_query("""
SELECT SUM(view_count) AS total_views
FROM trending_videos;
""", conn)

   total_views
0     56727681

In [31]:
# 25. Average likes

pd.read_sql_query("""
SELECT ROUND(AVG(like_count), 2) AS average_likes
FROM trending_videos;
""", conn)

   average_likes
0       14458.05

In [32]:
# 26. Average comments

pd.read_sql_query("""
SELECT ROUND(AVG(comment_count), 2) AS average_comments
FROM trending_videos;
""", conn)

   average_comments
0           1244.53

In [33]:
# 27. Minimum likes

pd.read_sql_query("""
SELECT MIN(like_count) AS minimum_likes
FROM trending_videos;
""", conn)

   minimum_likes
0            111

In [39]:
# 28. Maximum likes

pd.read_sql_query("""
SELECT MAX(like_count) AS maximum_likes
FROM trending_videos;
""", conn)

   maximum_likes
0         552190

In [40]:
# 29. Minimum comments

pd.read_sql_query("""
SELECT MIN(comment_count) AS minimum_comments
FROM trending_videos;
""", conn)

   minimum_comments
0                 0

In [41]:
# 30. Maximum comments

pd.read_sql_query("""
SELECT MAX(comment_count) AS maximum_comments
FROM trending_videos;
""", conn)

   maximum_comments
0             65290

# DISTRIBUTION / GROUP ANALYSIS — 31 to 40

In [42]:
# 31. Videos by category

pd.read_sql_query("""
SELECT
    category_name,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY category_name
ORDER BY total_videos DESC;
""", conn)

      category_name  total_videos
0            Gaming           134
1             Music            37
2     Entertainment            14
3    People & Blogs             8
4  Film & Animation             3
5            Sports             1
6   News & Politics             1
7            Comedy             1

In [44]:
# 32. Videos by channel

pd.read_sql_query("""
SELECT
    channel_title,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY channel_title
ORDER BY total_videos DESC
LIMIT 20;
""", conn)

      channel_title  total_videos
0       with uh why             1
1            weezer             1
2   videogamedunkey             1
3         vanilbean             1
4             steak             1
5     shadypenguinn             1
6      rooflemonger             1
7           rebecca             1
8       outsidexbox             1
9              jenn             1
10         gameranx             1
11           elixir             1
12           daukey             1
13     callmehhaley             1
14         berleezy             1
15      ZooMaa Live             1
16            Zoink             1
17         YumiLive             1
18     Wyful Shorts             1
19          Wittyyb             1

In [45]:
# 33. Video quality distribution

pd.read_sql_query("""
SELECT
    definition,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY definition
ORDER BY total_videos DESC;
""", conn)

  definition  total_videos
0         hd           197
1         sd             2

In [46]:
# 34. Caption availability

pd.read_sql_query("""
SELECT
    caption,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY caption;
""", conn)

  caption  total_videos
0   false           188
1    true            11

In [47]:
# 35. Weekend vs weekday

pd.read_sql_query("""
SELECT
    is_weekend,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY is_weekend;
""", conn)

   is_weekend  total_videos
0           0           198
1           1             1

In [48]:
# 36. Videos by publishing day

pd.read_sql_query("""
SELECT
    publish_day_name,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY publish_day_name
ORDER BY total_videos DESC;
""", conn)

  publish_day_name  total_videos
0         Thursday           121
1           Friday            55
2        Wednesday            16
3          Tuesday             3
4           Monday             3
5           Sunday             1

In [49]:
# 37. Videos by publishing hour

pd.read_sql_query("""
SELECT
    publish_hour,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY publish_hour
ORDER BY publish_hour;
""", conn)

    publish_hour  total_videos
0              0             8
1              1            12
2              2             4
3              3             3
4              4            15
5              5             6
6              6             7
7              7             1
8              8             3
9              9             1
10            10             4
11            12             4
12            13            13
13            14             4
14            15             8
15            16            24
16            17            10
17            18             9
18            19             9
19            20            11
20            21            16
21            22            17
22            23            10

In [50]:
# 38. Duration category distribution

pd.read_sql_query("""
SELECT
    duration_category,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY duration_category
ORDER BY total_videos DESC;
""", conn)

  duration_category  total_videos
0              Long           138
1            Medium            57
2             Short             4

In [51]:
# 39. View bucket distribution

pd.read_sql_query("""
SELECT
    view_bucket,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY view_bucket
ORDER BY total_videos DESC;
""", conn)

  view_bucket  total_videos
0   Very High            50
1      Medium            50
2         Low            50
3        High            49

In [52]:
# 40. Publishing session distribution

pd.read_sql_query("""
SELECT
    publish_session,
    COUNT(*) AS total_videos
FROM trending_videos
GROUP BY publish_session
ORDER BY total_videos DESC;
""", conn)

  publish_session  total_videos
0       Afternoon            68
1         Evening            63
2           Night            55
3         Morning            13

# ADVANCED STATISTICS — 41 to 50

In [53]:
# 41. Views variance

pd.read_sql_query("""
SELECT
    AVG(view_count * view_count)
    - AVG(view_count) * AVG(view_count)
    AS view_variance
FROM trending_videos;
""", conn)

   view_variance
0   3.359714e+11

In [54]:
# 42. Views standard deviation

pd.read_sql_query("""
SELECT
    SQRT(
        AVG(view_count * view_count)
        - AVG(view_count) * AVG(view_count)
    ) AS view_std_dev
FROM trending_videos;
""", conn)

    view_std_dev
0  579630.411153

In [55]:
# 43. Pearson correlation: views vs likes

pd.read_sql_query("""
SELECT
(
    SUM(
        (view_count - v.avg_views)
        * (like_count - v.avg_likes)
    )
)
/
(
    SQRT(
        SUM((view_count - v.avg_views) * (view_count - v.avg_views))
        *
        SUM((like_count - v.avg_likes) * (like_count - v.avg_likes))
    )
) AS pearson_views_likes
FROM trending_videos
CROSS JOIN (
    SELECT
        AVG(view_count) AS avg_views,
        AVG(like_count) AS avg_likes
    FROM trending_videos
) v;
""", conn)

   pearson_views_likes
0             0.704313

In [56]:
# 44. Pearson correlation: views vs comments

pd.read_sql_query("""
SELECT
(
    SUM(
        (view_count - v.avg_views)
        * (comment_count - v.avg_comments)
    )
)
/
(
    SQRT(
        SUM((view_count - v.avg_views) * (view_count - v.avg_views))
        *
        SUM((comment_count - v.avg_comments) * (comment_count - v.avg_comments))
    )
) AS pearson_views_comments
FROM trending_videos
CROSS JOIN (
    SELECT
        AVG(view_count) AS avg_views,
        AVG(comment_count) AS avg_comments
    FROM trending_videos
) v;
""", conn)

   pearson_views_comments
0                0.588218

In [68]:
# 45. Covariance: views vs likes

pd.read_sql_query("""
SELECT
    ROUND(AVG(
        (view_count - v.avg_views)
        *
        (like_count - v.avg_likes)
    ),3) AS covariance_views_likes
FROM trending_videos
CROSS JOIN (
    SELECT
        AVG(view_count) AS avg_views,
        AVG(like_count) AS avg_likes
    FROM trending_videos
) v;
""", conn)

   covariance_views_likes
0            1.866494e+10

In [58]:
# 46. Covariance: views vs comments

pd.read_sql_query("""
SELECT
    AVG(
        (view_count - v.avg_views)
        *
        (comment_count - v.avg_comments)
    ) AS covariance_views_comments
FROM trending_videos
CROSS JOIN (
    SELECT
        AVG(view_count) AS avg_views,
        AVG(comment_count) AS avg_comments
    FROM trending_videos
) v;
""", conn)

   covariance_views_comments
0               1.696334e+09

In [63]:
# 47. Top videos by engagement rate

pd.read_sql_query("""
SELECT
    video_id,
    title,
    channel_title,
    engagement_rate
FROM trending_videos
ORDER BY engagement_rate DESC
LIMIT 10;
""", conn)

,video_id,title,channel_title,engagement_rate
0,Hcvizzvdeq8,FARMING,Stray Kids - Topic,0.283888
1,Btxjs24K1Fs,Lil Peep - Benz Truck Pt. 2 (Official Video),Lil Peep,0.257730
2,9Vdgd4F9Cui,Destroy Lonely - MONSTER (official video),Destroy Lonely,0.234011
3,M6R6Nbmxca8,Brent Faiyaz - like it was. [Official Video],Brent Faiyaz,0.207755
4,Ic-Bjhmgmrk,Rebecca Black - Michael. (Official Video),rebecca,0.204025
5,Bz4Uzthytss,"Stray Kids ""This & That"" M/V",JYP Entertainment,0.198218
6,Bre0Atefme4,Hurricane Wisdom & Gunna - YK Where It's Goin’...,Hurricane Wisdom,0.191108
7,Zqkyha4L0Uw,IM SELLING FILIPINO STREET FOOD BUT A GHOST KE...,Kubz Scouts,0.185362
8,Zwzf5Ieqfge,FattMack - Miyla [Official Visualizer],FattMack,0.182372
9,Pq7Ibyc9Cys,"KAROL G, Drake - Ahí (Visualizer)",KarolGVEVO,0.167263

In [64]:
# 48. Top channels by average views

pd.read_sql_query("""
SELECT
    channel_title,
    COUNT(*) AS total_videos,
    ROUND(AVG(view_count), 2) AS average_views
FROM trending_videos
GROUP BY channel_title
HAVING COUNT(*) >= 2
ORDER BY average_views DESC
LIMIT 10;
""", conn)

Empty DataFrame
Columns: [channel_title, total_videos, average_views]
Index: []

In [65]:
# 49. Category performance summary

pd.read_sql_query("""
SELECT
    category_name,
    COUNT(*) AS total_videos,
    ROUND(AVG(view_count), 2) AS avg_views,
    ROUND(AVG(like_count), 2) AS avg_likes,
    ROUND(AVG(comment_count), 2) AS avg_comments,
    ROUND(AVG(engagement_rate), 2) AS avg_engagement
FROM trending_videos
GROUP BY category_name
ORDER BY avg_engagement DESC;
""", conn)

,category_name,total_videos,avg_views,avg_likes,avg_comments,avg_engagement
0,Music,37,229873.92,28245.92,2706.54,0.11
1,News & Politics,1,92100.00,7373.00,852.00,0.09
2,Comedy,1,133244.00,10689.00,817.00,0.09
3,People & Blogs,8,112766.63,7931.13,671.00,0.07
4,Sports,1,77299.00,2954.00,213.00,0.04
5,Gaming,134,247573.42,9859.21,842.13,0.04
6,Film & Animation,3,3090997.33,90934.33,6024.00,0.04
7,Entertainment,14,326410.00,10975.07,668.00,0.04

In [66]:
# 50. Overall performance summary

pd.read_sql_query("""
SELECT
    COUNT(*) AS total_videos,
    COUNT(DISTINCT channel_title) AS total_channels,
    COUNT(DISTINCT category_name) AS total_categories,

    SUM(view_count) AS total_views,

    ROUND(AVG(view_count), 2) AS avg_views,
    ROUND(AVG(like_count), 2) AS avg_likes,
    ROUND(AVG(comment_count), 2) AS avg_comments,

    ROUND(AVG(engagement_rate), 2) AS avg_engagement_rate,
    ROUND(AVG(like_rate), 2) AS avg_like_rate,
    ROUND(AVG(comment_rate), 2) AS avg_comment_rate

FROM trending_videos;
""", conn)

,total_videos,total_channels,total_categories,total_views,avg_views,avg_likes,avg_comments,avg_engagement_rate,avg_like_rate,avg_comment_rate
0,199,199,8,56727681,285063.72,14458.05,1244.53,0.06,0.05,0.0

In [69]:
# Which videos have views greater than 1 million?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    view_count
FROM trending_videos
WHERE view_count > 1000000
ORDER BY view_count DESC;
""", conn)

      video_id                                              title  view_count
0  1Ya87Encrj0  Awarapan 2 : Trailer: Shivam’s Rage  Vishesh |...     4929447
1  5Fhxyqqokl8              Primetime | Official Trailer HD | A24     4120877
2  Bz4Uzthytss                       Stray Kids "This & That" M/V     3115159
3  Qq76Pqsi1Iw  Grand Theft Auto VI: An Extended Look Coming A...     2838610
4  Ymweqizyb7S  The Hood: The World is His | Character Reveal ...     2434573
5  Q8Xyvyyypf0                                 3 SCARY GAMES #112     1515171
6  Jjhndnhia5Y              SIDEMEN MECCHA CHAMELEON: SNITCH ROLE     1371856
7  1Isngt7Qqh8                      🔴IF I LAUGH = YOU GET ROBUX!🔴     1218084
8  Gqptry8P_Q4                 ROBLOX MUKBANG has a DARK SECRET..     1061042

In [70]:
# Which videos have likes greater than 100,000?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    like_count
FROM trending_videos
WHERE like_count > 100000
ORDER BY like_count DESC;
""", conn)

      video_id                                              title  like_count
0  Bz4Uzthytss                       Stray Kids "This & That" M/V      552190
1  Qq76Pqsi1Iw  Grand Theft Auto VI: An Extended Look Coming A...      258392
2  1Ya87Encrj0  Awarapan 2 : Trailer: Shivam’s Rage  Vishesh |...      133543
3  5Fhxyqqokl8              Primetime | Official Trailer HD | A24      126324
4  4Ikhox-Dkrm                                         【Ado】モンストロ      107238

In [71]:
# Which videos have comments greater than 10,000?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    comment_count
FROM trending_videos
WHERE comment_count > 10000
ORDER BY comment_count DESC;
""", conn)

,video_id,title,comment_count
0,Bz4Uzthytss,"Stray Kids ""This & That"" M/V",65290
1,Qq76Pqsi1Iw,Grand Theft Auto VI: An Extended Look Coming A...,22698

In [72]:
# Which videos have engagement rate greater than 5%?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    engagement_rate
FROM trending_videos
WHERE engagement_rate > 5
ORDER BY engagement_rate DESC;
""", conn)

Empty DataFrame
Columns: [video_id, title, engagement_rate]
Index: []

In [73]:
# Which videos have like rate greater than 3%?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    like_rate
FROM trending_videos
WHERE like_rate > 3
ORDER BY like_rate DESC;
""", conn)

Empty DataFrame
Columns: [video_id, title, like_rate]
Index: []

In [74]:
# Which videos have comment rate less than 1%?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    comment_rate
FROM trending_videos
WHERE comment_rate < 1
ORDER BY comment_rate DESC;
""", conn)

,video_id,title,comment_rate
0,Btxjs24K1Fs,Lil Peep - Benz Truck Pt. 2 (Official Video),0.029996
1,8Nmqsnlc3Cs,Rockstar Launches A GTA 6 Trailer For A Traile...,0.029653
2,Zqkyha4L0Uw,IM SELLING FILIPINO STREET FOOD BUT A GHOST KE...,0.026466
3,Swp4Uh9Ay34,Tempo - No Te Sientas Mal (Video Oficial),0.023224
4,Ic-Bjhmgmrk,Rebecca Black - Michael. (Official Video),0.022058
...,...,...,...
194,Cb82Ghywury,LEFT PUNCH ONLY! Mike Tyson's Punch-Out!! (POR...,0.000013
195,Av_D9Fmskok,Around Me,0.000000
196,Nywycv1Ow78,MAYDAY,0.000000
197,Tpmig5Ndqk0,Call of Duty: Black Ops 7 Esports World Cup | ...,0.000000
198,Ddqysefzwms,🚨🍀EXPOSING THE #1 HACKER ON WARZONE REBIRTH IS...,0.000000

In [75]:
# Which videos have views between 100,000 and 1,000,000?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    view_count
FROM trending_videos
WHERE view_count BETWEEN 100000 AND 1000000
ORDER BY view_count DESC;
""", conn)

,video_id,title,view_count
0,I2Zohquncbo,Tough Call | D.Mon Hero Trailer | Overwatch,879398
1,Arj3S2Bpoq4,"1,000,000 Villagers Destroy VERITY",879005
2,Kmh_Np98Xlo,KAI X SPEED MINECRAFT HARDCORE MARATHON | OFFI...,771157
3,3Dliafcchag,I Used Infinite Rats to Kill God,766501
4,4Ikhox-Dkrm,【Ado】モンストロ,737844
...,...,...,...
111,H1Fxuqoliwk,We Don't Need to Be Perfect,106101
112,Jexnedfzhzo,FlightReacts 1st TIME PLAYING Madden 27 & THIS...,104432
113,Vk_Jnblkhjk,Shift At Midnight Fully Released,103595
114,Tekxuw3H90A,Identifying EVERY Darkner In Deltarune - Chapt...,103340
115,Zetbkvn1-9K,The Vanoss Crew Play Big Walk!,101328

In [76]:
# Which videos have both high views and high likes?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    view_count,
    like_count
FROM trending_videos
WHERE view_count > 1000000
AND like_count > 50000
ORDER BY view_count DESC;
""", conn)

,video_id,title,view_count,like_count
0,1Ya87Encrj0,Awarapan 2 : Trailer: Shivam’s Rage Vishesh |...,4929447,133543
1,5Fhxyqqokl8,Primetime | Official Trailer HD | A24,4120877,126324
2,Bz4Uzthytss,"Stray Kids ""This & That"" M/V",3115159,552190
3,Qq76Pqsi1Iw,Grand Theft Auto VI: An Extended Look Coming A...,2838610,258392
4,Ymweqizyb7S,The Hood: The World is His | Character Reveal ...,2434573,65659
5,Q8Xyvyyypf0,3 SCARY GAMES #112,1515171,60838
6,Gqptry8P_Q4,ROBLOX MUKBANG has a DARK SECRET..,1061042,58944

In [77]:
# Which videos have high views OR high comments?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    view_count,
    comment_count
FROM trending_videos
WHERE view_count > 1000000
OR comment_count > 10000
ORDER BY view_count DESC;
""", conn)

,video_id,title,view_count,comment_count
0,1Ya87Encrj0,Awarapan 2 : Trailer: Shivam’s Rage Vishesh |...,4929447,8172
1,5Fhxyqqokl8,Primetime | Official Trailer HD | A24,4120877,8952
2,Bz4Uzthytss,"Stray Kids ""This & That"" M/V",3115159,65290
3,Qq76Pqsi1Iw,Grand Theft Auto VI: An Extended Look Coming A...,2838610,22698
4,Ymweqizyb7S,The Hood: The World is His | Character Reveal ...,2434573,6018
5,Q8Xyvyyypf0,3 SCARY GAMES #112,1515171,3426
6,Jjhndnhia5Y,SIDEMEN MECCHA CHAMELEON: SNITCH ROLE,1371856,1068
7,1Isngt7Qqh8,🔴IF I LAUGH = YOU GET ROBUX!🔴,1218084,22
8,Gqptry8P_Q4,ROBLOX MUKBANG has a DARK SECRET..,1061042,1582

In [78]:
# Which videos have zero comments?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    comment_count
FROM trending_videos
WHERE comment_count = 0;
""", conn)

,video_id,title,comment_count
0,Av_D9Fmskok,Around Me,0
1,Nywycv1Ow78,MAYDAY,0
2,Tpmig5Ndqk0,Call of Duty: Black Ops 7 Esports World Cup | ...,0
3,Ddqysefzwms,🚨🍀EXPOSING THE #1 HACKER ON WARZONE REBIRTH IS...,0

In [79]:
# Which videos have no likes?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    like_count
FROM trending_videos
WHERE like_count = 0;
""", conn)

Empty DataFrame
Columns: [video_id, title, like_count]
Index: []

In [80]:
# Which videos are HD and have more than 500,000 views?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    definition,
    view_count
FROM trending_videos
WHERE definition = 'hd'
AND view_count > 500000
ORDER BY view_count DESC;
""", conn)

,video_id,title,definition,view_count
0,1Ya87Encrj0,Awarapan 2 : Trailer: Shivam’s Rage Vishesh |...,hd,4929447
1,5Fhxyqqokl8,Primetime | Official Trailer HD | A24,hd,4120877
2,Bz4Uzthytss,"Stray Kids ""This & That"" M/V",hd,3115159
3,Qq76Pqsi1Iw,Grand Theft Auto VI: An Extended Look Coming A...,hd,2838610
4,Ymweqizyb7S,The Hood: The World is His | Character Reveal ...,hd,2434573
5,Q8Xyvyyypf0,3 SCARY GAMES #112,hd,1515171
6,Jjhndnhia5Y,SIDEMEN MECCHA CHAMELEON: SNITCH ROLE,hd,1371856
7,1Isngt7Qqh8,🔴IF I LAUGH = YOU GET ROBUX!🔴,hd,1218084
8,Gqptry8P_Q4,ROBLOX MUKBANG has a DARK SECRET..,hd,1061042
9,I2Zohquncbo,Tough Call | D.Mon Hero Trailer | Overwatch,hd,879398
10,Arj3S2Bpoq4,"1,000,000 Villagers Destroy VERITY",hd,879005
11,Kmh_Np98Xlo,KAI X SPEED MINECRAFT HARDCORE MARATHON | OFFI...,hd,771157
12,3Dliafcchag,I Used Infinite Rats to Kill God,hd,766501
13,4Ikhox-Dkrm,【Ado】モンストロ,hd,737844
14,Dsizdcw_31O,Minecraft 2v2 Death Swap,hd,629888
15,Vetpwzytfx4,Hice un CUARTO SECRETO para ESCONDERME con MIS...,hd,602797
16,Xhd0Q9Pf-3U,​​​,hd,584438
17,6Wgo51Klkmm,"The DUCK SONG, But It’s NICO!",hd,520636
18,Qizmn1_Wtmw,"ANIMAL HOSPITAL, But I ONLY Accept GREEN PATIE...",hd,518828

In [81]:
# Which videos have captions and engagement rate above 5%?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    caption,
    engagement_rate
FROM trending_videos
WHERE caption = 'true'
AND engagement_rate > 5
ORDER BY engagement_rate DESC;
""", conn)

Empty DataFrame
Columns: [video_id, title, caption, engagement_rate]
Index: []

In [82]:
# Which videos were published on weekends and have more than 1 million views?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    publish_day_name,
    view_count
FROM trending_videos
WHERE is_weekend = 1
AND view_count > 1000000
ORDER BY view_count DESC;
""", conn)

Empty DataFrame
Columns: [video_id, title, publish_day_name, view_count]
Index: []

In [83]:
# Which videos have views greater than average views?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    view_count
FROM trending_videos
WHERE view_count > (
    SELECT AVG(view_count)
    FROM trending_videos
)
ORDER BY view_count DESC;
""", conn)

       video_id                                              title  view_count
0   1Ya87Encrj0  Awarapan 2 : Trailer: Shivam’s Rage  Vishesh |...     4929447
1   5Fhxyqqokl8              Primetime | Official Trailer HD | A24     4120877
2   Bz4Uzthytss                       Stray Kids "This & That" M/V     3115159
3   Qq76Pqsi1Iw  Grand Theft Auto VI: An Extended Look Coming A...     2838610
4   Ymweqizyb7S  The Hood: The World is His | Character Reveal ...     2434573
5   Q8Xyvyyypf0                                 3 SCARY GAMES #112     1515171
6   Jjhndnhia5Y              SIDEMEN MECCHA CHAMELEON: SNITCH ROLE     1371856
7   1Isngt7Qqh8                      🔴IF I LAUGH = YOU GET ROBUX!🔴     1218084
8   Gqptry8P_Q4                 ROBLOX MUKBANG has a DARK SECRET..     1061042
9   I2Zohquncbo        Tough Call | D.Mon Hero Trailer | Overwatch      879398
10  Arj3S2Bpoq4                 1,000,000 Villagers Destroy VERITY      879005
11  Kmh_Np98Xlo  KAI X SPEED MINECRAFT HARDCORE MARATHON | OFFI...      771157
12  3Dliafcchag                   I Used Infinite Rats to Kill God      766501
13  4Ikhox-Dkrm                                         【Ado】モンストロ      737844
14  Dsizdcw_31O                           Minecraft 2v2 Death Swap      629888
15  Vetpwzytfx4  Hice un CUARTO SECRETO para ESCONDERME con MIS...      602797
16  Xhd0Q9Pf-3U                                                ​​​      584438
17  6Wgo51Klkmm                      The DUCK SONG, But It’s NICO!      520636
18  Qizmn1_Wtmw  ANIMAL HOSPITAL, But I ONLY Accept GREEN PATIE...      518828
19  Qusmopfmkfu                         PLAYING DONUT SMP w/ STEAK      497618
20  B3Fbo_Zslg8       Animal (Live from Hinterland 2026) | KATSEYE      469044
21  R0Mvel7Btbe            The Backrooms Game Marathon w/ Mr Sark!      455600
22  Wpel938Frva        I Joined The Best Meccha Chameleon Lobby...      419887
23  F0N5Kg3Fmti             Weezer - C.E.O. (Official Music Video)      409950
24  -Tanwotw0Bc  🔴LIVE | TARKOV SEASONAL | DAY 4 | HutchMF x GI...      409353
25  Hfp_Bhl7Coc  Max's TOKON Day 1, Story, Tournament & More! 🔴...      391224
26  T8R1Sldktme                                               Peak      389139
27  Nogfqvuxcvg       100% Speedrunning Scale The Depths is Brutal      380720
28  Lnjnlem9Oj0                   Hide from the VILLAIN in Roblox!      376002
29  44Acyeimk9A                Finally... A Backrooms Anomaly Game      367180
30  Lcfmfmszr3K  Finding EVERY POPPY PLAYTIME Character In Robl...      366099
31  Ixa7Bmrbbxs  THE ONLY LIVING PICKPOCKET IN NEW YORK | Offic...      360878
32  Ik1Oza-Fjyc  7 NEW SPRITES and NEW SEASON in FORTNITE! (Pre...      353613
33  2Uf4Pcge8Ga        Quake: Dawn of the Machine — Launch Trailer      349593
34  H-Yja9O8Cb0  BEST FORTNITE UPDATE!! (let's play WYFUL PILLARS)      342716
35  G-2Kkmwahvq                         WONDERLAND - Final Trailer      339529
36  Jfbpb1_Imsq                  The Cranberries - Zombie (Lyrics)      334098
37  Wtpkcosphto           vani accidentally SWEARS on livestream..      326282
38  Q6Ub3Ut0Q6O                        Aphmau SNAPPED at Everyone!      323471
39  N1Szn7Dw9Oe  MY FAVOURITE MATCHUP OF ALL TIME - T1 VS DK - ...      322822
40  Clbhge1Lfd4                                   prepare yourself      316576
41  3Eozrq6Xzbq                MORNING DEW (DONK) REMIX (EXPLICIT)      313506
42  Q8Gsoap5Uuo          I Hired an Army of Assassins on Lifesteal      310973
43  U-I5Tini8M8       The Dark Truth Behind Flamingo Characters...      295333
44  I08I3Tsfro4            [Hollow Knight: Silksong] I Forgot | #7      290084

In [84]:
# Which videos have engagement rate greater than the average engagement rate?

pd.read_sql_query("""
SELECT
    video_id,
    title,
    engagement_rate
FROM trending_videos
WHERE engagement_rate > (
    SELECT AVG(engagement_rate)
    FROM trending_videos
)
ORDER BY engagement_rate DESC;
""", conn)

,video_id,title,engagement_rate
0,Hcvizzvdeq8,FARMING,0.283888
1,Btxjs24K1Fs,Lil Peep - Benz Truck Pt. 2 (Official Video),0.257730
2,9Vdgd4F9Cui,Destroy Lonely - MONSTER (official video),0.234011
3,M6R6Nbmxca8,Brent Faiyaz - like it was. [Official Video],0.207755
4,Ic-Bjhmgmrk,Rebecca Black - Michael. (Official Video),0.204025
...,...,...,...
71,Clbhge1Lfd4,prepare yourself,0.061319
72,Smnssjxeglo,"Roblox Bedwars, but you can FUSE KITS..",0.060908
73,Kmh_Np98Xlo,KAI X SPEED MINECRAFT HARDCORE MARATHON | OFFI...,0.060016
74,1Vvv6W9Gft8,"I downloaded some Desktop Helpers, but there's...",0.058959
75,-Nkqongjl6E,Future - No Misery (Official Music Video),0.058529

In [85]:
# Calculate the percentage of videos having more than 1 million views.

pd.read_sql_query("""
SELECT
    COUNT(*) AS total_videos,
    SUM(
        CASE
            WHEN view_count > 1000000 THEN 1
            ELSE 0
        END
    ) AS high_view_videos,
    ROUND(
        SUM(
            CASE
                WHEN view_count > 1000000 THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS high_view_rate
FROM trending_videos;
""", conn)

   total_videos  high_view_videos  high_view_rate
0           199                 9            4.52

In [86]:
# Calculate the percentage of videos having engagement rate above 5%.

pd.read_sql_query("""
SELECT
    COUNT(*) AS total_videos,
    SUM(
        CASE
            WHEN engagement_rate > 5 THEN 1
            ELSE 0
        END
    ) AS high_engagement_videos,
    ROUND(
        SUM(
            CASE
                WHEN engagement_rate > 5 THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS high_engagement_rate
FROM trending_videos;
""", conn)

   total_videos  high_engagement_videos  high_engagement_rate
0           199                       0                   0.0

In [87]:
# Classify videos based on their views.

pd.read_sql_query("""
SELECT
    video_id,
    title,
    view_count,
    CASE
        WHEN view_count >= 1000000 THEN 'High'
        WHEN view_count >= 100000 THEN 'Medium'
        ELSE 'Low'
    END AS view_performance
FROM trending_videos
ORDER BY view_count DESC;
""", conn)

,video_id,title,view_count,view_performance
0,1Ya87Encrj0,Awarapan 2 : Trailer: Shivam’s Rage Vishesh |...,4929447,High
1,5Fhxyqqokl8,Primetime | Official Trailer HD | A24,4120877,High
2,Bz4Uzthytss,"Stray Kids ""This & That"" M/V",3115159,High
3,Qq76Pqsi1Iw,Grand Theft Auto VI: An Extended Look Coming A...,2838610,High
4,Ymweqizyb7S,The Hood: The World is His | Character Reveal ...,2434573,High
...,...,...,...,...
194,5Fksfa-5Tx4,We Played Happy's Humble Burger Cult.. (got cr...,20015,Low
195,Ic-Bjhmgmrk,Rebecca Black - Michael. (Official Video),16547,Low
196,Ddqysefzwms,🚨🍀EXPOSING THE #1 HACKER ON WARZONE REBIRTH IS...,13979,Low
197,V4Brdhcndni,Jaded,7258,Low
198,Zwzf5Ieqfge,FattMack - Miyla [Official Visualizer],6569,Low

In [88]:
# Find videos having high views but below-average engagement.

pd.read_sql_query("""
SELECT
    video_id,
    title,
    view_count,
    engagement_rate
FROM trending_videos
WHERE view_count > (
    SELECT AVG(view_count)
    FROM trending_videos
)
AND engagement_rate < (
    SELECT AVG(engagement_rate)
    FROM trending_videos
)
ORDER BY view_count DESC;
""", conn)

,video_id,title,view_count,engagement_rate
0,1Ya87Encrj0,Awarapan 2 : Trailer: Shivam’s Rage Vishesh |...,4929447,0.028749
1,5Fhxyqqokl8,Primetime | Official Trailer HD | A24,4120877,0.032827
2,Ymweqizyb7S,The Hood: The World is His | Character Reveal ...,2434573,0.029441
3,Q8Xyvyyypf0,3 SCARY GAMES #112,1515171,0.042414
4,Jjhndnhia5Y,SIDEMEN MECCHA CHAMELEON: SNITCH ROLE,1371856,0.037032
5,1Isngt7Qqh8,🔴IF I LAUGH = YOU GET ROBUX!🔴,1218084,0.008169
6,Gqptry8P_Q4,ROBLOX MUKBANG has a DARK SECRET..,1061042,0.057044
7,Arj3S2Bpoq4,"1,000,000 Villagers Destroy VERITY",879005,0.022619
8,Dsizdcw_31O,Minecraft 2v2 Death Swap,629888,0.025508
9,Vetpwzytfx4,Hice un CUARTO SECRETO para ESCONDERME con MIS...,602797,0.015602
10,Xhd0Q9Pf-3U,​​​,584438,0.017750
11,6Wgo51Klkmm,"The DUCK SONG, But It’s NICO!",520636,0.020122
12,Qizmn1_Wtmw,"ANIMAL HOSPITAL, But I ONLY Accept GREEN PATIE...",518828,0.024594
13,Qusmopfmkfu,PLAYING DONUT SMP w/ STEAK,497618,0.014776
14,R0Mvel7Btbe,The Backrooms Game Marathon w/ Mr Sark!,455600,0.047283
15,Wpel938Frva,I Joined The Best Meccha Chameleon Lobby...,419887,0.026121
16,-Tanwotw0Bc,🔴LIVE | TARKOV SEASONAL | DAY 4 | HutchMF x GI...,409353,0.016687
17,Hfp_Bhl7Coc,"Max's TOKON Day 1, Story, Tournament & More! 🔴...",391224,0.015336
18,T8R1Sldktme,Peak,389139,0.050640
19,Nogfqvuxcvg,100% Speedrunning Scale The Depths is Brutal,380720,0.026347
20,Lnjnlem9Oj0,Hide from the VILLAIN in Roblox!,376002,0.043580
21,44Acyeimk9A,Finally... A Backrooms Anomaly Game,367180,0.049529
22,Lcfmfmszr3K,Finding EVERY POPPY PLAYTIME Character In Robl...,366099,0.018585
23,Ixa7Bmrbbxs,THE ONLY LIVING PICKPOCKET IN NEW YORK | Offic...,360878,0.023512
24,Ik1Oza-Fjyc,7 NEW SPRITES and NEW SEASON in FORTNITE! (Pre...,353613,0.019561
25,H-Yja9O8Cb0,BEST FORTNITE UPDATE!! (let's play WYFUL PILLARS),342716,0.012503
26,Jfbpb1_Imsq,The Cranberries - Zombie (Lyrics),334098,0.003837
27,Wtpkcosphto,vani accidentally SWEARS on livestream..,326282,0.036778
28,Q6Ub3Ut0Q6O,Aphmau SNAPPED at Everyone!,323471,0.031001
29,N1Szn7Dw9Oe,MY FAVOURITE MATCHUP OF ALL TIME - T1 VS DK - ...,322822,0.025525
30,Q8Gsoap5Uuo,I Hired an Army of Assassins on Lifesteal,310973,0.046281
31,I08I3Tsfro4,[Hollow Knight: Silksong] I Forgot | #7,290084,0.035104

# 💼 Business Questions — YouTube Trending Videos Analytics

The following business questions are designed to evaluate video performance,
channel performance, audience engagement, content strategy, and publishing
behavior using SQL.

---

## 📊 Video Performance Analysis

### 1. Which 10 videos have the highest number of views?

Identify the top-performing videos based on total views and determine
which content has achieved the highest audience reach.

---

### 2. Which 10 videos have the highest engagement rate?

Identify videos that generate the strongest overall audience interaction
relative to their reach.

---

### 3. Which videos have the highest like rate?

Determine which videos convert their viewers into likes most effectively.

---

### 4. Which videos generate the most comments per view?

Identify videos that encourage the strongest audience discussion and
interaction.

---

### 5. Which videos have high views but relatively low engagement?

Identify videos that achieve strong reach but comparatively weak audience
interaction to discover potential content-performance gaps.

---

## 📺 Channel Performance Analysis

### 6. Which channels have the highest total views?

Identify the channels generating the largest overall audience reach.

---

### 7. Which channels have the highest average engagement rate?

Determine which channels consistently generate strong audience interaction.

---

### 8. Which channels have published the most trending videos?

Identify channels that appear most frequently among trending videos.

---

### 9. Which channels have both high reach and high engagement?

Find channels that perform strongly in both audience reach and engagement,
rather than relying on views alone.

---

## 🗂️ Category Performance Analysis

### 10. Which categories generate the highest average views?

Identify the content categories with the strongest average audience reach.

---

### 11. Which categories receive the highest average likes?

Determine which categories generate stronger audience appreciation through
average likes.

---

### 12. Which categories receive the highest average comments?

Identify categories that encourage stronger audience conversations.

---

### 13. Which content categories have the strongest overall performance?

Compare categories using views, likes, comments, and engagement rate to
identify the strongest overall-performing content areas.

---

## 🕐 Publishing Strategy Analysis

### 14. Which publishing hour produces the highest average views?

Determine the most effective hours for publishing videos based on average
audience reach.

---

### 15. Which day of the week has the highest average views?

Identify the day that produces the strongest average video performance.

---

### 16. Do weekend videos perform better than weekday videos?

Compare weekend and weekday videos using views and engagement rate to
evaluate whether publishing on weekends provides a performance advantage.

---

### 17. Which publishing sessions generate the highest average engagement?

Compare publishing sessions such as morning, afternoon, evening, and night
to identify when audience engagement is strongest.

---

## 📝 Content & NLP Analysis

### 18. Do longer titles receive higher average engagement?

Analyze title length and title word count to determine whether longer or
shorter titles are associated with stronger engagement.

---

### 19. Does a higher number of hashtags correspond to higher average views?

Evaluate hashtag usage against average views to understand whether greater
hashtag usage is associated with stronger reach.

---

### 20. Do videos with more tags generate higher average engagement?

Analyze tag count against engagement rate to determine whether richer tag
usage is associated with better audience interaction.

---

# 🎯 Business Objective

These SQL questions help transform raw YouTube data into actionable
business insights across:

**Reach → Engagement → Channels → Categories → Publishing Strategy → Content Strategy**

The analysis can help content creators, marketing teams, and media
businesses make data-driven decisions about what content to create,
when to publish, and how to improve audience engagement.

In [91]:
# Which videos have the longest titles?

display(pd.read_sql_query("""
SELECT
    video_id,
    title,
    title_length,
    title_word_count
FROM trending_videos
ORDER BY title_length DESC
LIMIT 10
""", conn))

,video_id,title,title_length,title_word_count
0,P5B7M0Awzdk,Best Friends BiRTHDAY SURPRiSE in Berry Avenue...,98,16
1,Zqkyha4L0Uw,IM SELLING FILIPINO STREET FOOD BUT A GHOST KE...,96,17
2,_Vyy6Auewkm,"The Dukes of Hazzard (2027) – Matt Damon, Jake...",92,15
3,F2Zuy-0J_3E,EG SUDOWOODO | NRG vs ENVY - VCT Americas Stag...,91,16
4,1Ya87Encrj0,Awarapan 2 : Trailer: Shivam’s Rage Vishesh |...,90,18
5,Vetpwzytfx4,Hice un CUARTO SECRETO para ESCONDERME con MIS...,89,14
6,Jcywhp_-O5W,OpTic GAMING vs 100 THIEVES!! (MAPS 3-5) | SCU...,86,17
7,-Tanwotw0Bc,🔴LIVE | TARKOV SEASONAL | DAY 4 | HutchMF x GI...,85,17
8,Nh1Ehppefr8,"Cyclops Cast, Scorpion Confirms Venom Future, ...",83,12
9,Upf2F3Kyg-K,ESPORTS WORLD CUP WATCH PARTY DAY 2 // CODE ZO...,80,14

In [92]:
# Which videos have the most detailed descriptions?

display(pd.read_sql_query("""
SELECT
    video_id,
    title,
    description_length,
    description_word_count
FROM trending_videos
ORDER BY description_length DESC
LIMIT 10
""", conn))

,video_id,title,description_length,description_word_count
0,_Vyy6Auewkm,"The Dukes of Hazzard (2027) – Matt Damon, Jake...",3982,639
1,Un61Rc9Obfc,【ELSWORD】WEEKLY RESET!! CP speedrun cuz I wan...,2656,368
2,Knkpn0A6Wwq,Carly Rae Jepsen - Don’t Leave Me on the Dance...,2503,440
3,F0N5Kg3Fmti,Weezer - C.E.O. (Official Music Video),2497,416
4,Ic-Bjhmgmrk,Rebecca Black - Michael. (Official Video),2357,442
5,I08I3Tsfro4,[Hollow Knight: Silksong] I Forgot | #7,2110,277
6,F8Gspmnw-Cy,Bungie released One More Surprise Update for D...,2063,360
7,Pq7Ibyc9Cys,"KAROL G, Drake - Ahí (Visualizer)",1878,363
8,Dsizdcw_31O,Minecraft 2v2 Death Swap,1843,307
9,1Ya87Encrj0,Awarapan 2 : Trailer: Shivam’s Rage Vishesh |...,1831,239

In [93]:
# Which videos contain the highest number of URLs?

display(pd.read_sql_query("""
SELECT
    video_id,
    title,
    url_count,
    urls_links
FROM trending_videos
WHERE url_count > 0
ORDER BY url_count DESC
LIMIT 10
""", conn))

,video_id,title,url_count,urls_links
0,Zc9Oh3Xuhce,Black Ops 2 Sweats HATE Rapid Fire SMGs,46,https://discord.gg/ecdDEUw7su | https://www.tw...
1,Jjhndnhia5Y,SIDEMEN MECCHA CHAMELEON: SNITCH ROLE,33,https://SidePlus.com | https://www.eatsides.co...
2,Un61Rc9Obfc,【ELSWORD】WEEKLY RESET!! CP speedrun cuz I wan...,32,https://elsword.koggames.com/ | https://store....
3,Eyxadv1Llym,NickEh30 reacts to Spiderman in Fortnite!,26,https://a.co/d/0ggXP7VJ | https://site.andrews...
4,-11Dlee0Dbe,The NEW Ghost Recon: Wildlands Update (not kid...,20,https://gsght.com/c/7cteyz | https://www.twitc...
5,44Acyeimk9A,Finally... A Backrooms Anomaly Game,19,https://gamersupps.gg/s7 | https://www.youtube...
6,J8X9Xg9Icym,TIME FOR MORE MARVEL TOKON!!! !TOKON #ad,18,https://x.com/BASILISK_gg | https://starforgep...
7,Tjxabygnano,The Backrooms Incident 1997…,13,https://starforgepc.com/CaseOh | https://gamer...
8,Jcywhp_-O5W,OpTic GAMING vs 100 THIEVES!! (MAPS 3-5) | SCU...,13,http://www.twitch.tv/Scump | http://www.twitte...
9,4Rmbkgqjkuo,GUESS THE NBA JUMPSHOT TO GO 82-0,13,https://enjoybball.com/collections/spring-2-0 ...

In [94]:
# Which videos contain the highest number of hashtags?

display(pd.read_sql_query("""
SELECT
    video_id,
    title,
    hashtag_count,
    hashtags
FROM trending_videos
WHERE hashtag_count > 0
ORDER BY hashtag_count DESC
LIMIT 10
""", conn))

,video_id,title,hashtag_count,hashtags
0,F0N5Kg3Fmti,Weezer - C.E.O. (Official Music Video),12,"[""#Weezer"", ""#CEO"", ""#TonyHawk"", ""#CurryBarker..."
1,Un61Rc9Obfc,【ELSWORD】WEEKLY RESET!! CP speedrun cuz I wan...,8,"[""#OnAeru"", ""#Kobo_Kanaeru"", ""#holoID"", ""#holo..."
2,Swp4Uh9Ay34,Tempo - No Te Sientas Mal (Video Oficial),6,"[""#Tempo"", ""#NoTeSientasMal"", ""#Reggaeton"", ""#..."
3,Cfa6Qisnxjg,Wiz khalifa - All Eyes On Me (Official Music V...,6,"[""#AllEyesOnMe"", ""#StayFocused"", ""#KeepGrindin..."
4,Coi0Vl3Ludi,Choose Your Starter Playing I SPY!,6,"[""#pokemon"", ""#pokemonchallenge"", ""#starterpok..."
5,Cb82Ghywury,LEFT PUNCH ONLY! Mike Tyson's Punch-Out!! (POR...,6,"[""#punchout"", ""#miketysonspunchout"", ""#nes"", ""..."
6,Ddqysefzwms,🚨🍀EXPOSING THE #1 HACKER ON WARZONE REBIRTH IS...,6,"[""#1"", ""#cod"", ""#warzone"", ""#callofduty"", ""#wa..."
7,5Fns_Nqwvwo,ARTMS (아르테미스) 'Blue Blood' Visualizer,5,"[""#HeeJin"", ""#KimLip"", ""#JinSoul"", ""#Choerry"",..."
8,Bz4Uzthytss,"Stray Kids ""This & That"" M/V",4,"[""#StrayKids"", ""#THIS_AND_THAT"", ""#StrayKidsCo..."
9,O4Oeg34Sslq,Pooh Shiesty - Reap What You Sow [Official Audio],4,"[""#PoohShiesty"", ""#AllEyesOnShiest"", ""#ImBack""..."

In [95]:
# Which videos contain the highest number of tags?

display(pd.read_sql_query("""
SELECT
    video_id,
    title,
    tag_count
FROM trending_videos
ORDER BY tag_count DESC
LIMIT 10
""", conn))

      video_id                                              title  tag_count
0  I08I3Tsfro4            [Hollow Knight: Silksong] I Forgot | #7         65
1  1Isngt7Qqh8                      🔴IF I LAUGH = YOU GET ROBUX!🔴         54
2  Un61Rc9Obfc  【ELSWORD】WEEKLY RESET!!  CP speedrun cuz I wan...         52
3  N1Szn7Dw9Oe  MY FAVOURITE MATCHUP OF ALL TIME - T1 VS DK - ...         51
4  Bz4Uzthytss                       Stray Kids "This & That" M/V         47
5  Cq5Zu70Izhu  🔴ARTEMIS 13 66%, 32-100* 🔴TOP 1-3🔴 TUNG TUNG S...         47
6  Xaskbs4Dd1S  playing the are you smarter than a 5th grader ...         47
7  Pw5J9Ewp4Li                 They Forgot To Balance The Hulk...         39
8  Ttkm35Fnyq0                      Beat Me In A 1v1, Win $1,000!         37
9  Tr9Gxvtvuwo          We Played ILLEGAL Games in Machine Party!         37

In [96]:
# What is the average number of hashtags for each category?

display(pd.read_sql_query("""
SELECT
    category_name,
    COUNT(*) AS total_videos,
    ROUND(AVG(hashtag_count), 2) AS avg_hashtags
FROM trending_videos
GROUP BY category_name
ORDER BY avg_hashtags DESC
""", conn))

      category_name  total_videos  avg_hashtags
0             Music            37          2.05
1            Gaming           134          1.43
2    People & Blogs             8          1.38
3     Entertainment            14          1.14
4            Sports             1          1.00
5  Film & Animation             3          0.33
6   News & Politics             1          0.00
7            Comedy             1          0.00

In [97]:
# What is the average number of tags for each category?

display(pd.read_sql_query("""
SELECT
    category_name,
    COUNT(*) AS total_videos,
    ROUND(AVG(tag_count), 2) AS avg_tags
FROM trending_videos
GROUP BY category_name
ORDER BY avg_tags DESC
""", conn))

      category_name  total_videos  avg_tags
0            Gaming           134     14.50
1             Music            37     12.81
2     Entertainment            14      9.86
3  Film & Animation             3      9.00
4   News & Politics             1      4.00
5    People & Blogs             8      1.13
6            Sports             1      1.00
7            Comedy             1      0.00

In [98]:
# Which categories create longer titles on average?

display(pd.read_sql_query("""
SELECT
    category_name,
    ROUND(AVG(title_length), 2) AS avg_title_length,
    ROUND(AVG(title_word_count), 2) AS avg_title_words
FROM trending_videos
GROUP BY category_name
ORDER BY avg_title_length DESC
""", conn))

      category_name  avg_title_length  avg_title_words
0            Sports             57.00            10.00
1  Film & Animation             52.33             9.00
2     Entertainment             52.14             8.86
3            Comedy             47.00             9.00
4    People & Blogs             46.50             8.00
5            Gaming             46.19             8.22
6             Music             34.00             5.89
7   News & Politics             32.00             5.00

In [99]:
# Which categories provide longer descriptions on average?

display(pd.read_sql_query("""
SELECT
    category_name,
    ROUND(AVG(description_length), 2) AS avg_description_length,
    ROUND(AVG(description_word_count), 2) AS avg_description_words
FROM trending_videos
GROUP BY category_name
ORDER BY avg_description_length DESC
""", conn))

      category_name  avg_description_length  avg_description_words
0  Film & Animation                  930.00                 128.33
1     Entertainment                  799.79                 126.21
2            Comedy                  748.00                 116.00
3             Music                  696.38                 114.32
4            Gaming                  426.97                  68.37
5    People & Blogs                  400.38                  65.38
6            Sports                  367.00                  67.00
7   News & Politics                  334.00                  55.00

In [100]:
# Does a higher number of hashtags correspond to higher average views?

display(pd.read_sql_query("""
SELECT
    hashtag_count,
    COUNT(*) AS total_videos,
    ROUND(AVG(view_count), 2) AS avg_views
FROM trending_videos
GROUP BY hashtag_count
ORDER BY hashtag_count
""", conn))

   hashtag_count  total_videos  avg_views
0              0            93  323091.63
1              1            21  243008.14
2              2            23  267484.30
3              3            41  235786.10
4              4            13  365694.00
5              5             1  121196.00
6              6             5   75174.40
7              8             1   96579.00
8             12             1  409950.00

In [101]:
# Does a higher number of tags correspond to higher average engagement?

display(pd.read_sql_query("""
SELECT
    tag_count,
    COUNT(*) AS total_videos,
    ROUND(AVG(engagement_rate), 2) AS avg_engagement
FROM trending_videos
GROUP BY tag_count
ORDER BY tag_count
""", conn))

    tag_count  total_videos  avg_engagement
0           0            42            0.06
1           1             3            0.04
2           2             7            0.06
3           3            10            0.04
4           4             4            0.11
5           5             4            0.04
6           6             6            0.05
7           7             1            0.02
8           8            13            0.07
9           9             7            0.09
10         10             9            0.05
11         11             4            0.09
12         12             8            0.05
13         13             2            0.04
14         14             4            0.05
15         15             4            0.06
16         16             6            0.04
17         17             3            0.10
18         18             5            0.03
19         19             3            0.17
20         20             2            0.06
21         21             6            0.06
22         22             1            0.01
23         23             2            0.05
24         25             6            0.03
25         26             9            0.06
26         27             3            0.01
27         28             1            0.19
28         29             5            0.06
29         30             2            0.05
30         31             2            0.09
31         32             3            0.03
32         35             1            0.10
33         36             1            0.01
34         37             2            0.04
35         39             1            0.05
36         47             3            0.10
37         51             1            0.03
38         52             1            0.04
39         54             1            0.01
40         65             1            0.04

In [102]:
# Do longer titles receive higher average engagement?

display(pd.read_sql_query("""
SELECT
    CASE
        WHEN title_length < 50 THEN 'Short Title'
        WHEN title_length BETWEEN 50 AND 100 THEN 'Medium Title'
        ELSE 'Long Title'
    END AS title_type,
    COUNT(*) AS total_videos,
    ROUND(AVG(view_count), 2) AS avg_views,
    ROUND(AVG(engagement_rate), 2) AS avg_engagement
FROM trending_videos
GROUP BY title_type
ORDER BY avg_engagement DESC
""", conn))

     title_type  total_videos  avg_views  avg_engagement
0   Short Title           128  283865.13            0.06
1  Medium Title            71  287224.58            0.05

In [103]:
# Do longer descriptions receive higher average views?

display(pd.read_sql_query("""
SELECT
    CASE
        WHEN description_length < 500 THEN 'Short Description'
        WHEN description_length BETWEEN 500 AND 1500 THEN 'Medium Description'
        ELSE 'Long Description'
    END AS description_type,
    COUNT(*) AS total_videos,
    ROUND(AVG(view_count), 2) AS avg_views
FROM trending_videos
GROUP BY description_type
ORDER BY avg_views DESC
""", conn))

     description_type  total_videos  avg_views
0    Long Description            13  559854.00
1  Medium Description            47  318677.96
2   Short Description           139  247997.95

In [104]:
# Which video duration categories have the highest average engagement?

display(pd.read_sql_query("""
SELECT
    duration_category,
    COUNT(*) AS total_videos,
    ROUND(AVG(engagement_rate), 2) AS avg_engagement
FROM trending_videos
GROUP BY duration_category
ORDER BY avg_engagement DESC
""", conn))

  duration_category  total_videos  avg_engagement
0             Short             4            0.10
1            Medium            57            0.09
2              Long           138            0.04

In [105]:
# Which duration categories generate the highest average views?

display(pd.read_sql_query("""
SELECT
    duration_category,
    COUNT(*) AS total_videos,
    ROUND(AVG(view_count), 2) AS avg_views
FROM trending_videos
GROUP BY duration_category
ORDER BY avg_views DESC
""", conn))

  duration_category  total_videos  avg_views
0             Short             4  860549.00
1            Medium            57  423903.44
2              Long           138  211036.15

In [106]:
# Which upload sessions have the highest average hashtag usage?

display(pd.read_sql_query("""
SELECT
    publish_session,
    COUNT(*) AS total_videos,
    ROUND(AVG(hashtag_count), 2) AS avg_hashtags,
    ROUND(AVG(tag_count), 2) AS avg_tags
FROM trending_videos
GROUP BY publish_session
ORDER BY avg_hashtags DESC
""", conn))

  publish_session  total_videos  avg_hashtags  avg_tags
0           Night            55          1.60     14.40
1         Evening            63          1.51     15.27
2       Afternoon            68          1.51     10.01
3         Morning            13          0.85     12.38

In [107]:
# Which video categories have the highest URL usage?

display(pd.read_sql_query("""
SELECT
    category_name,
    COUNT(*) AS total_videos,
    SUM(CASE WHEN url_count > 0 THEN 1 ELSE 0 END) AS videos_with_urls,
    ROUND(
        SUM(CASE WHEN url_count > 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS url_usage_rate
FROM trending_videos
GROUP BY category_name
ORDER BY url_usage_rate DESC
""", conn))

      category_name  total_videos  videos_with_urls  url_usage_rate
0   News & Politics             1                 1          100.00
1  Film & Animation             3                 3          100.00
2     Entertainment            14                14          100.00
3            Comedy             1                 1          100.00
4            Gaming           134               127           94.78
5    People & Blogs             8                 7           87.50
6             Music            37                24           64.86
7            Sports             1                 0            0.00

In [108]:
# Which channels use the most hashtags per video on average?

display(pd.read_sql_query("""
SELECT
    channel_title,
    COUNT(*) AS total_videos,
    ROUND(AVG(hashtag_count), 2) AS avg_hashtags_per_video
FROM trending_videos
GROUP BY channel_title
HAVING COUNT(*) >= 2
ORDER BY avg_hashtags_per_video DESC
LIMIT 10
""", conn))

Empty DataFrame
Columns: [channel_title, total_videos, avg_hashtags_per_video]
Index: []

In [109]:
# Which channels use the most tags per video on average?

display(pd.read_sql_query("""
SELECT
    channel_title,
    COUNT(*) AS total_videos,
    ROUND(AVG(tag_count), 2) AS avg_tags_per_video
FROM trending_videos
GROUP BY channel_title
HAVING COUNT(*) >= 2
ORDER BY avg_tags_per_video DESC
LIMIT 10
""", conn))

Empty DataFrame
Columns: [channel_title, total_videos, avg_tags_per_video]
Index: []

In [110]:
# How does title length relate to like rate?

display(pd.read_sql_query("""
SELECT
    CASE
        WHEN title_length < 50 THEN 'Short'
        WHEN title_length BETWEEN 50 AND 100 THEN 'Medium'
        ELSE 'Long'
    END AS title_length_group,
    COUNT(*) AS total_videos,
    ROUND(AVG(like_rate), 2) AS avg_like_rate,
    ROUND(AVG(comment_rate), 2) AS avg_comment_rate
FROM trending_videos
GROUP BY title_length_group
ORDER BY avg_like_rate DESC
""", conn))

  title_length_group  total_videos  avg_like_rate  avg_comment_rate
0              Short           128           0.06               0.0
1             Medium            71           0.05               0.0

## 📌 Project Conclusion

This **YouTube Trending Videos Analytics** project successfully transformed raw YouTube trending video data into a structured analytical dataset and performed comprehensive **EDA, NLP-based text analysis, feature engineering, and SQL business analytics**.

The analysis examined video performance through **views, likes, comments, engagement rate, like rate, and comment rate**, while also studying content characteristics such as **title length, title word count, description length, description word count, tags, hashtags, URLs, and video duration**.

The project also analyzed publishing behavior using **publishing date, day, month, hour, weekend status, and publishing sessions** to understand how upload timing can be associated with video performance.

From the NLP and content perspective, **titles and descriptions were cleaned and processed**, while derived features such as `title_length`, `title_word_count`, `description_length`, `description_word_count`, `tag_count`, `hashtag_count`, and `url_count` enabled deeper content-level analysis.

The SQL analysis provided a business-oriented view of the dataset by identifying **high-performing content, channel behavior, category performance, content characteristics, publishing patterns, and engagement trends**.

---

## 🎯 Business Value

The project can help **content creators, digital marketers, media teams, and YouTube strategists** understand:

- Which content characteristics are associated with stronger performance
- How audience engagement varies across different content types
- How title and description structure can be analyzed
- How hashtags, tags, and URLs are used across videos
- How video duration relates to performance
- How publishing sessions and timing can be evaluated
- Which channels and categories demonstrate stronger performance patterns
- How SQL can convert raw analytical data into business-focused insights

---

## 🚀 Final Analytical Flow

**Raw YouTube Data**  
↓  
**Data Cleaning & Preprocessing**  
↓  
**EDA & Visualization**  
↓  
**NLP / Text Processing**  
↓  
**Feature Engineering**  
↓  
**SQLite Database**  
↓  
**SQL Business Analysis**  
↓  
**Performance & Content Insights**  
↓  
**Business Recommendations**

---

## 🏆 Final Conclusion

Overall, this project demonstrates an **end-to-end Data Analytics workflow** combining **Python, Pandas, EDA, Visualization, NLP, Feature Engineering, SQLite, and SQL** to understand YouTube trending video performance.

### 🔄 Complete Project Pipeline

**Raw Data → Clean Data → EDA → NLP → Features → Database → SQL → Business Insights**

# THE END