<div align="center">

# ⚡ EV INTELLIGENCE PLATFORM

### 🌱 Real-World Electric Vehicle Market, Mobility & Charging Analytics

**Data Collection • SQL • Data Analytics • Statistics • Machine Learning • Explainable AI • Geospatial Intelligence • Streamlit**

<br>

<img src="https://img.shields.io/badge/Python-3.12-blue?style=for-the-badge&logo=python&logoColor=white" alt="Python">
<img src="https://img.shields.io/badge/Pandas-Data%20Analysis-150458?style=for-the-badge&logo=pandas&logoColor=white" alt="Pandas">
<img src="https://img.shields.io/badge/SQL-Analytics-orange?style=for-the-badge&logo=sqlite&logoColor=white" alt="SQL">
<img src="https://img.shields.io/badge/Scikit--Learn-ML-F7931E?style=for-the-badge&logo=scikit-learn&logoColor=white" alt="Scikit Learn">
<img src="https://img.shields.io/badge/Streamlit-App-FF4B4B?style=for-the-badge&logo=streamlit&logoColor=white" alt="Streamlit">

<br><br>

**Real Public Data → Data Engineering → SQL → Analytics → ML → Interactive Intelligence**

<br>

[📊 Analytics](#-project-overview) •
[🗄️ Database](#-project-architecture) •
[🤖 Machine Learning](#-machine-learning-roadmap) •
[🗺️ Geo Analytics](#-geographic-intelligence) •
[🌐 Web App](#-web-application)

</div>

---

<div align="center">

<img src="../assets/banner.png"
     alt="EV Intelligence Platform Banner"
     width="100%">

</div>

---

## 🎯 One-Line Project Definition

> **An end-to-end real-world EV intelligence platform that collects publicly available electric-mobility data, stores and analyzes it through SQL and Python, discovers business insights, applies Machine Learning where appropriate, and delivers interactive intelligence through a Streamlit application.**

---

---

### 🌍 From Real-World EV Data → Data Engineering → SQL → Analytics → Machine Learning → Interactive Intelligence

**Project Type:** End-to-End Data Analytics & Data Science

**Domain:** Electric Vehicles • Green Mobility • Energy • Transportation

**Data:** Real-World Public EV Dataset

**Tools:** Python • Pandas • NumPy • SQL • SQLite • SQLAlchemy • Matplotlib • Seaborn • Plotly • Folium • Scikit-Learn • Streamlit

---

## 🎯 Project Overview

This project is a complete end-to-end **Electric Vehicle Intelligence Platform** built using real-world public EV data.

The objective is to transform raw electric vehicle data into meaningful business intelligence through a complete data workflow.

The project covers the complete lifecycle:

**Data Collection → Data Validation → Data Engineering → SQL → Data Cleaning → EDA → Statistics → Visualization → Feature Engineering → Machine Learning → Explainable AI → Dashboard → Deployment**

---

## 💼 Business Problem

The electric vehicle market is developing rapidly across different countries and regions.

However, raw EV data can be difficult to understand because information may contain:

- Multiple countries
- Different vehicle categories
- Different years
- EV sales
- EV stock
- EV adoption rates
- Charging infrastructure
- Energy-related indicators
- Historical observations
- Scenario-based values

Businesses and decision-makers need a structured analytical system that can transform this raw information into useful insights.

### The key questions are:

- Which countries have the highest EV adoption?
- How are EV sales changing over time?
- Which vehicle categories are growing fastest?
- Which regions are leading the EV transition?
- How is charging infrastructure developing?
- Which markets have strong EV growth?
- What relationship exists between EV adoption and charging infrastructure?
- Which factors are associated with EV market development?
- Can historical EV data support useful Machine Learning tasks?

---

# 🎯 Project Objectives

The main objectives of this project are:

1. Work with real-world EV data.
2. Preserve the original raw dataset.
3. Build a reproducible data pipeline.
4. Validate and profile the raw data.
5. Store structured data in a SQL database.
6. Practice SQL-based analytics.
7. Load SQL data into Pandas.
8. Clean and transform the dataset.
9. Perform exploratory data analysis.
10. Perform statistical analysis.
11. Create meaningful business KPIs.
12. Build advanced visualizations.
13. Perform geographic analysis.
14. Engineer analytical features.
15. Build Machine Learning models where appropriate.
16. Evaluate Machine Learning models.
17. Apply Explainable AI where applicable.
18. Build an interactive Streamlit dashboard.
19. Generate business insights.
20. Document the complete project workflow.

---

# 🏗️ End-to-End Architecture

```text
                    REAL-WORLD EV DATA
                            │
                            ▼
                  DATA COLLECTION
                            │
                            ▼
                    RAW DATA STORAGE
                            │
                            ▼
                  DATA VALIDATION
                            │
                            ▼
                  DATA PROFILING
                            │
                            ▼
                    SQL DATABASE
                            │
                            ▼
                       SQL QUERY
                            │
                            ▼
                     PANDAS DATAFRAME
                            │
                            ▼
                    DATA CLEANING
                            │
                            ▼
                   DATA TRANSFORMATION
                            │
                            ▼
                          EDA
                            │
                            ▼
                       STATISTICS
                            │
                            ▼
                    VISUAL ANALYTICS
                            │
                            ▼
                  FEATURE ENGINEERING
                            │
                            ▼
                 MACHINE LEARNING
                            │
                            ▼
                  MODEL EVALUATION
                            │
                            ▼
                  EXPLAINABLE AI
                            │
                            ▼
                 BUSINESS INTELLIGENCE
                            │
                            ▼
                 STREAMLIT DASHBOARD
                            │
                            ▼
                       DEPLOYMENT
````

---

# 🗂️ Project Modules

| Module | Focus                            |
| ------ | -------------------------------- |
| 01     | Real-World Data Collection       |
| 02     | Data Validation & Profiling      |
| 03     | Database Design                  |
| 04     | SQL Analytics                    |
| 05     | SQL → Pandas Pipeline            |
| 06     | Data Cleaning                    |
| 07     | Exploratory Data Analysis        |
| 08     | Statistics & Hypothesis Testing  |
| 09     | Advanced Visualization           |
| 10     | Feature Engineering              |
| 11     | ML Preprocessing                 |
| 12     | Regression                       |
| 13     | Classification                   |
| 14     | Clustering                       |
| 15     | Explainable AI                   |
| 16     | Model Deployment                 |
| 17     | Streamlit Intelligence Dashboard |

---

# 📊 Main Analytics Areas

## 🚗 EV Market Analytics

* EV Sales
* EV Stock
* EV Sales Share
* EV Stock Share
* Year-over-Year Growth
* Market Share
* Vehicle-Type Analysis
* Country Ranking
* Regional Comparison

## 🔌 Charging Infrastructure

* Public Charging Points
* Slow Chargers
* Fast Chargers
* Ultra-Fast Chargers
* Charging Growth
* EVs per Charging Point
* Charging Infrastructure Comparison

## 🌍 Geographic Analytics

* Country Comparison
* Regional Analysis
* EV Adoption Map
* Market Growth Map
* Charging Infrastructure Map
* Geographic Ranking

## ⚡ Energy & Environmental Analytics

Where supported by the dataset:

* Energy Demand
* Oil Displacement
* EV Energy Impact
* Market Transition
* Scenario Analysis

---

# 📈 Key Business KPIs

The project will calculate relevant KPIs such as:

* Total EV Sales
* Total EV Stock
* EV Sales Growth
* EV Sales Share
* EV Stock Share
* Top EV Market
* Fastest-Growing Market
* Total Charging Points
* Fast Charging Share
* EVs per Charging Point
* Vehicle-Type Share
* Energy Impact
* Oil Displacement

---

# 🤖 Machine Learning Strategy

Machine Learning will only be applied when the real dataset supports a valid business problem.

The project will NOT create artificial target variables simply to force Machine Learning into the project.

Potential ML applications include:

* Regression
* Classification
* Clustering
* Market Segmentation
* Growth Analysis
* Charging Infrastructure Analysis

The selected ML problem must have:

* Meaningful features
* Sufficient observations
* Valid target variable
* Business relevance
* Appropriate evaluation metrics

---

# 🧠 Explainable AI

Where Machine Learning is applicable, model interpretation will be performed using techniques such as:

```text
MODEL
   ↓
FEATURE IMPORTANCE
   ↓
PERMUTATION IMPORTANCE
   ↓
SHAP
   ↓
BUSINESS INTERPRETATION
```

The objective is not only to determine model performance, but also to understand **why the model produces its results**.

---

# 📊 Visualization Strategy

Different visualization libraries will be used for different analytical requirements.

### Matplotlib

* Statistical plots
* Distribution analysis
* Custom analytical charts

### Seaborn

* Correlation heatmaps
* Statistical visualizations
* Distribution analysis

### Plotly

* Interactive charts
* Interactive comparisons
* Time-series exploration
* Interactive dashboards

### Folium

* Geographic visualization
* Country-level EV analysis
* Charging infrastructure maps

### Altair

* Declarative statistical visualization
* Interactive analytical charts

### Other Visualization Techniques

* Bar Charts
* Line Charts
* Area Charts
* Histograms
* Box Plots
* Violin Plots
* Scatter Plots
* Heatmaps
* Treemaps
* Bubble Charts
* Geographic Maps
* Interactive Charts

---

# 🗄️ Database Architecture

The project will use a relational database to practice real-world data management.

```text
RAW DATA
   ↓
DATABASE
   ↓
TABLES
   ↓
RELATIONSHIPS
   ↓
SQL QUERIES
   ↓
PANDAS
   ↓
ANALYTICS
```

Database concepts covered:

* SQLite
* SQLAlchemy
* Tables
* Primary Keys
* Foreign Keys
* Relationships
* Indexes
* Views
* SQL Queries
* Aggregations
* Joins
* CTEs
* Window Functions
* Data Validation

---

# 🧹 Data Quality Workflow

The dataset will be investigated for:

* Missing Values
* Duplicate Records
* Incorrect Data Types
* Invalid Values
* Inconsistent Categories
* Country Name Variations
* Unit Differences
* Outliers
* Null Values
* Historical vs Projection Records

Important principle:

> An unusual value is not automatically an error. The value must first be investigated using its business and source context.

---

# 📚 Statistical Analysis

The project will cover:

* Mean
* Median
* Mode
* Variance
* Standard Deviation
* Range
* Quartiles
* Percentiles
* Skewness
* Kurtosis
* Correlation
* Covariance
* Distribution Analysis
* Hypothesis Testing
* T-Test
* ANOVA
* Chi-Square Test
* Normality Testing

Every statistical result should be converted into a meaningful business interpretation.

---

# 📁 Project Data Flow

```text
data/raw/
      ↓
data/interim/
      ↓
database/
      ↓
data/cleaned/
      ↓
data/processed/
      ↓
outputs/tables/
      ↓
outputs/figures/
      ↓
models/
      ↓
reports/
      ↓
Streamlit Application
```

---

# 🏆 Final Goal

The final system should demonstrate the complete professional Data Science lifecycle:

```text
REAL DATA
   ↓
DATA ENGINEERING
   ↓
SQL
   ↓
PYTHON
   ↓
DATA CLEANING
   ↓
EDA
   ↓
STATISTICS
   ↓
VISUALIZATION
   ↓
BUSINESS ANALYTICS
   ↓
FEATURE ENGINEERING
   ↓
MACHINE LEARNING
   ↓
MODEL EVALUATION
   ↓
EXPLAINABLE AI
   ↓
DASHBOARD
   ↓
DEPLOYMENT
```

---

## 🚀 Expected Outcome

At the end of this project, the raw EV dataset will be transformed into an interactive **EV Intelligence Platform** capable of supporting:

* Business analysis
* Market intelligence
* Geographic analysis
* EV adoption analysis
* Charging infrastructure analysis
* Statistical investigation
* Machine Learning experiments
* Model interpretation
* Interactive dashboards
* Data-driven decision making

---

### ⚡ From Raw EV Data to Intelligent Business Decisions

**Real Data • Real Analysis • Real Engineering • Real Business Insights**

```

**Bhai isme intentionally koi website URL, dataset URL, hyperlink, external reference link ya website mention nahi hai.** Ye directly Jupyter Notebook ke **first Markdown cell** ke liye optimized hai.
```


---

# 👨‍💻 Author

**S Mohammed Kaif**

**Data Analytics | Data Science | Machine Learning | AI**

---

# 📦 Import Libraries

This project uses Python libraries for real-world EV data collection, web scraping, data processing, visualization, database management, and analysis.

## 🔧 Core Libraries

- `pandas` — Data manipulation and analysis
- `numpy` — Numerical computing
- `requests` — HTTP requests and webpage/API data collection
- `beautifulsoup4` — HTML parsing and web scraping
- `lxml` — Fast HTML/XML parsing
- `urllib3` — HTTP connection handling

## 📁 File & Path Management

- `pathlib` — Project path management
- `os` — File and directory operations
- `json` — JSON data handling
- `re` — Regular expressions
- `io` — In-memory file handling
- `datetime` — Date and time management

## ⚠️ Warnings

```python
import warnings
warnings.filterwarnings("ignore")

!pip install libraries if you want to put it!

In [1]:
# ============================================================
# ⚡ EV INTELLIGENCE PLATFORM
# 01 - Real-World EV Data Collection
# ============================================================

# -----------------------------
# Core Data Analysis
# -----------------------------
import pandas as pd
import numpy as np

# -----------------------------
# Web Requests & Data Collection
# -----------------------------
import requests
from bs4 import BeautifulSoup
from lxml import html

# -----------------------------
# File & Data Handling
# -----------------------------
import os
import io
import json
import re
from pathlib import Path
from datetime import datetime, timezone

# -----------------------------
# Database
# -----------------------------
import sqlite3
from sqlalchemy import create_engine, text

# -----------------------------
# Data Validation
# -----------------------------
from typing import Optional, List, Dict, Any

# -----------------------------
# Visualization
# -----------------------------
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

# -----------------------------
# Geographic Visualization
# -----------------------------
import folium

# -----------------------------
# Statistics
# -----------------------------
import scipy.stats as stats

# -----------------------------
# Warnings
# -----------------------------
import warnings

warnings.filterwarnings("ignore")

# -----------------------------
# Display Configuration
# -----------------------------
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)


print("✅ EV Intelligence Platform libraries imported successfully.")

✅ EV Intelligence Platform libraries imported successfully.

## 📥 Load EV Dataset

Load the real-world Electric Vehicle Population dataset into Pandas for further analysis.

In [2]:
df = pd.read_csv("../datas/raw/Electric_Vehicle_Population_Data.csv")

print("✅ Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

✅ Dataset loaded successfully!
Shape: (150482, 17)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,KM8K33AGXL,King,Seattle,WA,98103.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258,0,43.0,249675142,POINT (-122.34301 47.659185),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,1C4RJYB61N,King,Bothell,WA,98011.0,2022,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,1.0,233928502,POINT (-122.20578 47.762405),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,1C4RJYD61P,Yakima,Yakima,WA,98908.0,2023,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,14.0,229675939,POINT (-120.6027202 46.5965625),PACIFICORP,5.307700e+10
3,5YJ3E1EA7J,King,Kirkland,WA,98034.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,45.0,104714466,POINT (-122.209285 47.71124),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
4,WBY7Z8C5XJ,Thurston,Olympia,WA,98501.0,2018,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,97,0,22.0,185498386,POINT (-122.89692 47.043535),PUGET SOUND ENERGY INC,5.306701e+10

In [3]:
df.tail()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
150477,WBY43AW05P,Grays Harbor,Montesano,WA,98563.0,2023,BMW,I4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,19.0,251204075,POINT (-123.60535 46.982215),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
150478,5YJ3E1EB7P,King,Seattle,WA,98104.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,43.0,241344414,POINT (-122.329075 47.6018),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
150479,5YJYGDEEXM,King,Seattle,WA,98109.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,43.0,180705626,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
150480,5UXTA6C08P,Snohomish,Mountlake Terrace,WA,98043.0,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,1.0,240473950,POINT (-122.30842 47.78416),PUGET SOUND ENERGY INC,5.306105e+10
150481,7SAYGDEF8N,Skagit,Mount Vernon,WA,98273.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,40.0,207667589,POINT (-122.338975 48.41333),PUGET SOUND ENERGY INC,5.305795e+10

## Data Inspection

In [4]:
df.sample()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
48820,5YJYGDEE2L,King,Medina,WA,98039.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291,0,48.0,113155241,POINT (-122.228025 47.61598),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10

In [5]:
df.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', '2020 Census Tract'],
      dtype='str')

In [6]:
df.size

2558194

In [7]:
df.shape

(150482, 17)

In [8]:
df.shape[0]

150482

In [9]:
df.shape[1]

17

In [10]:
df.index

RangeIndex(start=0, stop=150482, step=1)

In [11]:
np.array(df.columns)

array(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code',
       'Model Year', 'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility',
       'Electric Range', 'Base MSRP', 'Legislative District',
       'DOL Vehicle ID', 'Vehicle Location', 'Electric Utility',
       '2020 Census Tract'], dtype=object)

In [12]:
df.columns.tolist()

['VIN (1-10)',
 'County',
 'City',
 'State',
 'Postal Code',
 'Model Year',
 'Make',
 'Model',
 'Electric Vehicle Type',
 'Clean Alternative Fuel Vehicle (CAFV) Eligibility',
 'Electric Range',
 'Base MSRP',
 'Legislative District',
 'DOL Vehicle ID',
 'Vehicle Location',
 'Electric Utility',
 '2020 Census Tract']

In [13]:
df.sample(frac = 0.5)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
32249,7SAYGDEF0P,King,Issaquah,WA,98027.0,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,41.0,253075917,POINT (-122.03646 47.534065),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
145821,YV4ED3GB8N,Whatcom,Bellingham,WA,98229.0,2022,VOLVO,C40,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,40.0,205915174,POINT (-122.4569227 48.7470973),PUGET SOUND ENERGY INC||PUD NO 1 OF WHATCOM CO...,5.307300e+10
45870,5YJ3E1EC2P,Snohomish,Bothell,WA,98021.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,1.0,221540336,POINT (-122.179458 47.802589),PUGET SOUND ENERGY INC,5.306105e+10
91454,WVWKR7AU4K,Pierce,Puyallup,WA,98373.0,2019,VOLKSWAGEN,E-GOLF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,125,0,25.0,237667895,POINT (-122.2987976 47.13795),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.305307e+10
106310,5YJ3E1EA6J,Lewis,Pe Ell,WA,98572.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,20.0,287718154,POINT (-123.2983149 46.570015),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.304197e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,1C4JJXR61N,King,Redmond,WA,98052.0,2022,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,22,0,45.0,211235657,POINT (-122.12302 47.67668),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
87989,5YJ3E1EB8J,Pierce,Gig Harbor,WA,98332.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,26.0,220575071,POINT (-122.589645 47.342345),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.305307e+10
37788,1C4JJXN67P,King,Tukwila,WA,98188.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21,0,11.0,237745651,POINT (-122.29179 47.43473),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
125318,WA1VAAGE9M,Franklin,Pasco,WA,99301.0,2021,AUDI,E-TRON,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,9.0,156628223,POINT (-119.0982 46.232395),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF F...,5.302102e+10
22406,1C4JJXR64P,King,Tukwila,WA,98188.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21,0,11.0,238417049,POINT (-122.29179 47.43473),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

# Data Types Check

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150482 entries, 0 to 150481
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         150482 non-null  str
 1   County                                             150479 non-null  str
 2   City                                               150479 non-null  str
 3   State                                              150482 non-null  str
 4   Postal Code                                        150479 non-null  float64
 5   Model Year                                         150482 non-null  int64
 6   Make                                               150482 non-null  str
 7   Model                                              150482 non-null  str
 8   Electric Vehicle Type                              150482 non-null  str
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  150482 non-null  str
 10  Electric Range                                     150482 non-null  int64
 11  Base MSRP                                          150482 non-null  int64
 12  Legislative District                               150141 non-null  float64
 13  DOL Vehicle ID                                     150482 non-null  int64
 14  Vehicle Location                                   150475 non-null  str
 15  Electric Utility                                   150479 non-null  str
 16  2020 Census Tract                                  150479 non-null  float64
dtypes: float64(3), int64(4), str(10)
memory usage: 47.0 MB

In [15]:
df.memory_usage()

Index                                                    132
VIN (1-10)                                           2708676
County                                               2043533
City                                                 2459048
State                                                1504820
Postal Code                                          1203856
Model Year                                           1203856
Make                                                 2038946
Model                                                2162863
Electric Vehicle Type                                5987716
Clean Alternative Fuel Vehicle (CAFV) Eligibility    8500646
Electric Range                                       1203856
Base MSRP                                            1203856
Legislative District                                 1203856
DOL Vehicle ID                                       1203856
Vehicle Location                                     5512374
Electric Utility                                     7902490
2020 Census Tract                                    1203856
dtype: int64

In [16]:
df.dtypes

VIN (1-10)                                               str
County                                                   str
City                                                     str
State                                                    str
Postal Code                                          float64
Model Year                                             int64
Make                                                     str
Model                                                    str
Electric Vehicle Type                                    str
Clean Alternative Fuel Vehicle (CAFV) Eligibility        str
Electric Range                                         int64
Base MSRP                                              int64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                         str
Electric Utility                                         str
2020 Census Tract                                    float64
dtype: object

In [17]:
display(df.dtypes.value_counts())

str        10
int64       4
float64     3
Name: count, dtype: int64

## Memory Checking `

In [18]:
df.memory_usage()

Index                                                    132
VIN (1-10)                                           2708676
County                                               2043533
City                                                 2459048
State                                                1504820
Postal Code                                          1203856
Model Year                                           1203856
Make                                                 2038946
Model                                                2162863
Electric Vehicle Type                                5987716
Clean Alternative Fuel Vehicle (CAFV) Eligibility    8500646
Electric Range                                       1203856
Base MSRP                                            1203856
Legislative District                                 1203856
DOL Vehicle ID                                       1203856
Vehicle Location                                     5512374
Electric Utility                                     7902490
2020 Census Tract                                    1203856
dtype: int64

In [19]:
df.memory_usage(deep = True).value_counts()

1203856    7
132        1
2708676    1
2043533    1
2459048    1
1504820    1
2038946    1
2162863    1
5987716    1
8500646    1
5512374    1
7902490    1
Name: count, dtype: int64

In [20]:
memory = df.memory_usage(deep=True).sort_values(ascending=False)

display(memory)

Clean Alternative Fuel Vehicle (CAFV) Eligibility    8500646
Electric Utility                                     7902490
Electric Vehicle Type                                5987716
Vehicle Location                                     5512374
VIN (1-10)                                           2708676
City                                                 2459048
Model                                                2162863
County                                               2043533
Make                                                 2038946
State                                                1504820
Legislative District                                 1203856
Postal Code                                          1203856
Model Year                                           1203856
Electric Range                                       1203856
DOL Vehicle ID                                       1203856
Base MSRP                                            1203856
2020 Census Tract                                    1203856
Index                                                    132
dtype: int64

In [21]:
total_memory = df.memory_usage(deep=True).sum()

print(f"Total Memory: {total_memory / 1024**2:.2f} MB")

Total Memory: 46.97 MB

In [22]:
df.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', '2020 Census Tract'],
      dtype='str')

In [23]:
print("Total Columns:", df.shape[1])
print("String Columns:", len(df.select_dtypes(include=["object", "string"]).columns))
print("Numeric Columns:", len(df.select_dtypes(include=np.number).columns))

display(df.dtypes)

Total Columns: 17
String Columns: 10
Numeric Columns: 7

VIN (1-10)                                               str
County                                                   str
City                                                     str
State                                                    str
Postal Code                                          float64
Model Year                                             int64
Make                                                     str
Model                                                    str
Electric Vehicle Type                                    str
Clean Alternative Fuel Vehicle (CAFV) Eligibility        str
Electric Range                                         int64
Base MSRP                                              int64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                         str
Electric Utility                                         str
2020 Census Tract                                    float64
dtype: object

In [24]:
df

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,KM8K33AGXL,King,Seattle,WA,98103.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258,0,43.0,249675142,POINT (-122.34301 47.659185),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,1C4RJYB61N,King,Bothell,WA,98011.0,2022,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,1.0,233928502,POINT (-122.20578 47.762405),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,1C4RJYD61P,Yakima,Yakima,WA,98908.0,2023,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,14.0,229675939,POINT (-120.6027202 46.5965625),PACIFICORP,5.307700e+10
3,5YJ3E1EA7J,King,Kirkland,WA,98034.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,45.0,104714466,POINT (-122.209285 47.71124),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
4,WBY7Z8C5XJ,Thurston,Olympia,WA,98501.0,2018,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,97,0,22.0,185498386,POINT (-122.89692 47.043535),PUGET SOUND ENERGY INC,5.306701e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150477,WBY43AW05P,Grays Harbor,Montesano,WA,98563.0,2023,BMW,I4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,19.0,251204075,POINT (-123.60535 46.982215),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
150478,5YJ3E1EB7P,King,Seattle,WA,98104.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,43.0,241344414,POINT (-122.329075 47.6018),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
150479,5YJYGDEEXM,King,Seattle,WA,98109.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,43.0,180705626,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
150480,5UXTA6C08P,Snohomish,Mountlake Terrace,WA,98043.0,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,1.0,240473950,POINT (-122.30842 47.78416),PUGET SOUND ENERGY INC,5.306105e+10
150481,7SAYGDEF8N,Skagit,Mount Vernon,WA,98273.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,40.0,207667589,POINT (-122.338975 48.41333),PUGET SOUND ENERGY INC,5.305795e+10

## Null Check

In [25]:
df.isnull().sum()

VIN (1-10)                                             0
County                                                 3
City                                                   3
State                                                  0
Postal Code                                            3
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 341
DOL Vehicle ID                                         0
Vehicle Location                                       7
Electric Utility                                       3
2020 Census Tract                                      3
dtype: int64

In [26]:
df.notna().sum()

VIN (1-10)                                           150482
County                                               150479
City                                                 150479
State                                                150482
Postal Code                                          150479
Model Year                                           150482
Make                                                 150482
Model                                                150482
Electric Vehicle Type                                150482
Clean Alternative Fuel Vehicle (CAFV) Eligibility    150482
Electric Range                                       150482
Base MSRP                                            150482
Legislative District                                 150141
DOL Vehicle ID                                       150482
Vehicle Location                                     150475
Electric Utility                                     150479
2020 Census Tract                                    150479
dtype: int64

In [27]:
(df.isnull().sum() / len(df) * 100).sort_values(ascending=False).round(2)

Legislative District                                 0.23
Vehicle Location                                     0.00
2020 Census Tract                                    0.00
County                                               0.00
City                                                 0.00
Postal Code                                          0.00
Electric Utility                                     0.00
VIN (1-10)                                           0.00
State                                                0.00
Electric Vehicle Type                                0.00
Model                                                0.00
Make                                                 0.00
Model Year                                           0.00
Base MSRP                                            0.00
Electric Range                                       0.00
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0.00
DOL Vehicle ID                                       0.00
dtype: float64

In [28]:
missing = df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

Legislative District    341
Vehicle Location          7
County                    3
Postal Code               3
City                      3
Electric Utility          3
2020 Census Tract         3
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df[df.duplicated()]

Empty DataFrame
Columns: [VIN (1-10), County, City, State, Postal Code, Model Year, Make, Model, Electric Vehicle Type, Clean Alternative Fuel Vehicle (CAFV) Eligibility, Electric Range, Base MSRP, Legislative District, DOL Vehicle ID, Vehicle Location, Electric Utility, 2020 Census Tract]
Index: []

In [31]:
print(df.duplicated().mean() * 100)

0.0

## Unique Values

In [32]:
df.nunique().sort_values()

Electric Vehicle Type                                     2
Clean Alternative Fuel Vehicle (CAFV) Eligibility         3
Model Year                                               22
Base MSRP                                                31
Make                                                     37
State                                                    41
Legislative District                                     49
Electric Utility                                         76
Electric Range                                          102
Model                                                   127
County                                                  183
City                                                    683
Vehicle Location                                        822
Postal Code                                             823
2020 Census Tract                                      2079
VIN (1-10)                                             9529
DOL Vehicle ID                                       150482
dtype: int64

In [33]:
(df.nunique() / len(df) * 100).sort_values().round(2)

Electric Vehicle Type                                  0.00
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0.00
Model Year                                             0.01
Base MSRP                                              0.02
Make                                                   0.02
State                                                  0.03
Legislative District                                   0.03
Electric Utility                                       0.05
Electric Range                                         0.07
Model                                                  0.08
County                                                 0.12
City                                                   0.45
Vehicle Location                                       0.55
Postal Code                                            0.55
2020 Census Tract                                      1.38
VIN (1-10)                                             6.33
DOL Vehicle ID                                       100.00
dtype: float64

# Columns Inspection

In [34]:
df

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,KM8K33AGXL,King,Seattle,WA,98103.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258,0,43.0,249675142,POINT (-122.34301 47.659185),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,1C4RJYB61N,King,Bothell,WA,98011.0,2022,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,1.0,233928502,POINT (-122.20578 47.762405),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,1C4RJYD61P,Yakima,Yakima,WA,98908.0,2023,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,14.0,229675939,POINT (-120.6027202 46.5965625),PACIFICORP,5.307700e+10
3,5YJ3E1EA7J,King,Kirkland,WA,98034.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,45.0,104714466,POINT (-122.209285 47.71124),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
4,WBY7Z8C5XJ,Thurston,Olympia,WA,98501.0,2018,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,97,0,22.0,185498386,POINT (-122.89692 47.043535),PUGET SOUND ENERGY INC,5.306701e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150477,WBY43AW05P,Grays Harbor,Montesano,WA,98563.0,2023,BMW,I4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,19.0,251204075,POINT (-123.60535 46.982215),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
150478,5YJ3E1EB7P,King,Seattle,WA,98104.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,43.0,241344414,POINT (-122.329075 47.6018),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
150479,5YJYGDEEXM,King,Seattle,WA,98109.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,43.0,180705626,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
150480,5UXTA6C08P,Snohomish,Mountlake Terrace,WA,98043.0,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,1.0,240473950,POINT (-122.30842 47.78416),PUGET SOUND ENERGY INC,5.306105e+10
150481,7SAYGDEF8N,Skagit,Mount Vernon,WA,98273.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,40.0,207667589,POINT (-122.338975 48.41333),PUGET SOUND ENERGY INC,5.305795e+10

In [35]:
df.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', '2020 Census Tract'],
      dtype='str')

In [36]:
df["VIN (1-10)"].unique()

<ArrowStringArray>
['KM8K33AGXL', '1C4RJYB61N', '1C4RJYD61P', '5YJ3E1EA7J', 'WBY7Z8C5XJ',
 '5YJ3E1EAXL', '2C4RC1N77H', '5YJYGDEE3L', '5YJ3E1EA1J', '7SAYGDEF0P',
 ...
 '7JRBR0FZ7M', '4JGDA6DBXH', '1FTZR081XY', '50EA1DCA2N', 'WB533CF03R',
 '1FMCU0EZ8M', '7FCTGAAL0P', 'WA1CAAGE9R', 'WA1G2BFZ5N', 'JN1CF0BB5P']
Length: 9529, dtype: str

In [37]:
df["VIN (1-10)"].nunique()

9529

In [41]:
df["County"].unique()

<ArrowStringArray>
[       'King',      'Yakima',    'Thurston',   'Snohomish',      'Island',
      'Kitsap',     'Whitman',      'Skagit',    'Kittitas', 'Walla Walla',
 ...
    'Kootenai',  'Williamson',       'Sarpy',  'Las Animas',   'St. Clair',
    'Hennepin',        'Maui',        'Bell',  'Portsmouth',     'Suffolk']
Length: 184, dtype: str

In [42]:
df["County"].nunique()

183

In [45]:
### Using loop to inspection all columns 

for col in df.columns:
    print("columns :",col)
    print(df[col])
    print(df[col].unique())
    print(df[col].nunique())
    print("=="*20)

columns : VIN (1-10)
0         KM8K33AGXL
1         1C4RJYB61N
2         1C4RJYD61P
3         5YJ3E1EA7J
4         WBY7Z8C5XJ
             ...
150477    WBY43AW05P
150478    5YJ3E1EB7P
150479    5YJYGDEEXM
150480    5UXTA6C08P
150481    7SAYGDEF8N
Name: VIN (1-10), Length: 150482, dtype: str
<ArrowStringArray>
['KM8K33AGXL', '1C4RJYB61N', '1C4RJYD61P', '5YJ3E1EA7J', 'WBY7Z8C5XJ',
 '5YJ3E1EAXL', '2C4RC1N77H', '5YJYGDEE3L', '5YJ3E1EA1J', '7SAYGDEF0P',
 ...
 '7JRBR0FZ7M', '4JGDA6DBXH', '1FTZR081XY', '50EA1DCA2N', 'WB533CF03R',
 '1FMCU0EZ8M', '7FCTGAAL0P', 'WA1CAAGE9R', 'WA1G2BFZ5N', 'JN1CF0BB5P']
Length: 9529, dtype: str
9529
========================================
columns : County
0                 King
1                 King
2               Yakima
3                 King
4             Thurston
              ...
150477    Grays Harbor
150478            King
150479            King
150480       Snohomish
150481          Skagit
Name: County, Length: 150482, dtype: str
<ArrowStringArray>
[       'King',      'Yakima',    'Thurston',   'Snohomish',      'Island',
      'Kitsap',     'Whitman',      'Skagit',    'Kittitas', 'Walla Walla',
 ...
    'Kootenai',  'Williamson',       'Sarpy',  'Las Animas',   'St. Clair',
    'Hennepin',        'Maui',        'Bell',  'Portsmouth',     'Suffolk']
Length: 184, dtype: str
183
========================================
columns : City
0                   Seattle
1                   Bothell
2                    Yakima
3                  Kirkland
4                   Olympia
                ...
150477            Montesano
150478              Seattle
150479              Seattle
150480    Mountlake Terrace
150481         Mount Vernon
Name: City, Length: 150482, dtype: str
<ArrowStringArray>
[      'Seattle',       'Bothell',        'Yakima',      'Kirkland',
       'Olympia',    'Marysville',          'Kent',   'Woodinville',
    'Coupeville',      'Bellevue',
 ...
       'Alameda',       'Prosper',       'Killeen',         'Tampa',
     'Camarillo',      'Coronado',       'Suffolk',    'Middletown',
     'Ewa Beach', 'Ellicott City']
Length: 684, dtype: str
683
========================================
columns : State
0         WA
1         WA
2         WA
3         WA
4         WA
          ..
150477    WA
150478    WA
150479    WA
150480    WA
150481    WA
Name: State, Length: 150482, dtype: str
<ArrowStringArray>
['WA', 'CA', 'IL', 'NE', 'MO', 'AZ', 'VA', 'KY', 'NC', 'MD', 'DC', 'WY', 'GA',
 'OR', 'FL', 'MS', 'TX', 'AL', 'HI', 'CO', 'CT', 'LA', 'MT', 'NV', 'NY', 'NJ',
 'OH', 'DE', 'PA', 'IN', 'NH', 'BC', 'AR', 'ID', 'UT', 'SC', 'KS', 'AK', 'AP',
 'MA', 'MN']
Length: 41, dtype: str
41
========================================
columns : Postal Code
0         98103.0
1         98011.0
2         98908.0
3         98034.0
4         98501.0
           ...
150477    98563.0
150478    98104.0
150479    98109.0
150480    98043.0
150481    98273.0
Name: Postal Code, Length: 150482, dtype: float64
[98103. 98011. 98908. 98034. 98501. 98271. 98042. 98072. 98239. 98004.
 98033. 98367. 98366. 98275. 98052. 98579. 98112. 98125. 98311. 98370.
 98312. 98108. 98258. 98383. 98346. 98506. 98022. 98109. 98006. 98133.
 98002. 98936. 98947. 98057. 98008. 98188. 98392. 98277. 98012. 98177.
 98380. 98058. 98272. 98110. 98155. 98597. 98028. 98502. 98168. 98292.
 98056. 98039. 98122. 98021. 98296. 98948. 98144. 98204. 98036. 98029.
 98310. 98107. 98117. 98092. 98007. 98503. 98903. 98942. 98199. 98146.
 98105. 98101. 98902. 98516. 98513. 98512. 98115. 98020. 98340. 98119.
 98178. 98026. 98589. 98074. 98031. 98270. 99163. 98576. 98273. 98922.
 98059. 98233. 98208. 98166. 98221. 98102. 98121. 98257. 99362. 99205.
 98087. 98005. 98274. 98203. 98237. 98901. 98037. 98249. 98826. 98148.
 98801. 98837. 99207. 99115. 98284. 98116. 98232. 98926. 98315. 98055.
 98198. 99167. 99109. 98043. 98236. 98070. 98201. 98943. 98260. 98815.
 98822. 98683. 98030. 98252. 99114. 98682. 98858. 98629. 98498. 98606.
 98368. 98662. 98045. 98685. 98686. 98674. 98359. 98106. 98382. 98047.
 98603. 98001. 98632. 99026. 98104. 98075. 98027. 98320. 98625. 98671.
 98663. 98607. 98023. 98019. 98604. 98684. 98660. 98365. 98223. 98664.
 98467. 98337. 98040. 98661. 98645. 98003. 98626. 98642. 98290. 98407.
 98053. 98409. 98388. 98439. 98665. 99004. 99354. 99223. 98349. 98024.
 98944. 98134. 98466. 98611. 98532. 98937. 99212. 98672. 98930. 98569.
 98675. 98601. 98376. 98371. 98520. 98390. 98531. 98241. 99336. 98358.
 98605. 98374. 98335. 99403. 98354. 98051. 98282. 98391. 98250. 98362.
 98342. 98329. 98225. 98932. 98038. 99301. 98226. 98294. 98333. 98339.
 98404. 98363. 98345. 98823. 99027. 98332. 98405. 99006. 99037. 98032.
 98841. 98584. 98433. 98014. 98635. 98935. 98951. 98953. 99201. 98406.
 98526. 99208. 98262. 98499. 98136. 98331. 98244. 98248. 98065. 98338.
 98530. 98010. 98126. 98251. 98325. 98649. 98938. 98118. 98923. 98620.
 98077. 98288. 98253. 98528. 99202. 98229. 99352. 99349. 99216. 99019.
 98580. 98833. 99338. 98264. 98445. 98856. 98862. 98816. 98857. 98638.
 98631. 98802. 98444. 99218. 99030. 98596. 98373. 99025. 98360. 99344.
 98261. 98372. 99206. 98640. 98235. 98321. 98844. 99224. 98357. 99353.
 99156. 98303. 99016. 98831. 99328. 98612. 99203. 98245. 98403. 98524.
 99204. 99023. 98934. 98644. 98446. 98355. 98328. 98843. 99217. 99323.
 98563. 98402. 98408. 99022. 98624. 99130. 98651. 99021. 98230. 99337.
 99125. 99356. 98610. 98591. 98327. 94901. 98848. 98387. 99005. 98394.
 99324. 98068. 98304. 98950. 98592. 99326. 98279. 98847. 98465. 98617.
 99350. 98550. 98593. 99161. 98401. 98385. 98164. 99341. 98256. 99169.
 98422. 98577. 98639. 98564. 99036. 98855. 98361. 99357. 98266. 98849.
 98925. 98424. 98537. 99402. 98546. 98828. 99029. 98356. 98421. 98541.
 98281. 98547. 60048. 98585. 98812. 99003. 98542. 99001. 68135. 98375.
 99170. 98595. 98247. 98648. 98650. 98834. 92131. 98850. 98326. 99141.
 99009. 98557. 98418. 99134. 99343. 99123. 98588. 98940. 64079. 99126.
 93555. 99320. 60035. 98283. 99008. 98548. 98941. 85281. 98555. 99011.
 98438. 98570. 23238. 90621. 99330. 98568. 40026. 98314. 98276. 98840.
 99113. 98571. 28376. 99111. 98587. 98344. 98297. 98673. 98538. 99119.
 98533. 98286. 21401. 98582. 98295. 21701. 99361. 20003. 68102. 99185.
 82001. 90249. 99139. 98814. 99017. 94565. 99031. 98323. 30030. 99122.
 62281. 98224. 98586. 99166. 98240. 98443. 92058. 99180. 99360. 98158.
 97214. 98851. 22554. 34242. 98206. 98634. 99347. 99148. 99173. 20732.
 98846. 99155. 98619. 98377. 98641. 92102. 98535. 39531. 92057. 92277.
 78251. 99121. 21157. 92595. 99159. 99181. 98590. 98572. 36877. 98336.
 99147. 99018. 96740. 94303. 78412. 99138. 99137. 93245. 98830. 99013.
 28305. 98381. 99118. 98220. 92106. 20002. 98845. 99116. 33547. 79911.
 95051. 99033. 80925. 93436. 92585. 98614.  6443. 71446. 23321. 97304.
 99110. 64084. 76310. 59106. 98267. 99133. 96752. 22151. 28390. 31088.
 85086. 95833. 95062. 98243. 98946. 20105. 21037. 92620. 98050. 75244.
 98263. 89029. 12833. 95014. 98832. 99039. 92154.  8641. 98613. 23185.
 61201. 89138. 45243. 19901. 22180. 80919. 97756. 30013. 96734. 99135.
 93041. 60077. 99101. 20007. 23455. 19131. 98616. 21113. 78254.  6355.
 21012. 92103. 22304. 46342. 98670. 79927. 98396. 98305. 20744.  6371.
 98583. 98643. 85248. 94707. 98565. 20906. 98351. 20653. 28545. 92101.
 92124. 22308. 20774. 23518. 90620. 98536. 30024.  3804. 98647. 23508.
 21040. 98621. 99179. 99129. 60605. 98562. 82801. 95688. 99117. 98527.
 13638. 70461. 17050. 90802. 20878. 98952. 28387. 12401. 28312. 95476.
 33131. 92056. 92308. 95054. 99032. 92114. 32792.  8048. 27958. 95131.
    nan 94710. 96818. 78121. 98504. 91913. 85250. 90064. 76092. 22903.
 23602. 98330. 94559. 95112. 80547. 20637.  7302. 94043. 72207. 86351.
 95661. 92201. 90005. 76528. 20762. 63137. 92647. 42701. 93940. 35124.
 83648. 60004. 98507. 10308. 60527. 98124. 98853. 92672. 99171.  8055.
 97330.  7003. 40121. 23456. 21036.  8202. 97367. 70037. 84121. 92703.
 33326. 94535. 60201. 98227. 29486. 66043. 95401. 23150. 29909. 22405.
 98813. 20895. 29483.  6379. 78233. 97703. 22307. 20171. 29404. 36619.
 23503. 99346. 32506. 92660. 99577. 89166. 77539. 99143. 13603. 27332.
 21756. 20854. 97404. 20603. 99140. 75026. 61822. 95120. 20879. 80019.
 23462. 33487. 80504. 98280. 46802. 80923. 99131. 95817. 90016. 98575.
 92130. 34108. 80111.  6385.  1824. 21076. 22015. 94510. 89129. 91801.
  8033. 90713. 92310. 95377. 89118. 98411. 23464. 78748. 80501. 20755.
 85212. 92109. 94556. 89135. 92618. 98821.  1730. 20814. 92051. 27205.
 67218. 94536. 99034. 93560. 84115. 91915. 83876. 78681. 68123. 30905.
 99371. 27516. 20024. 81082. 62220. 12866. 55408. 75074.  7103. 21054.
 93001. 98255. 85040. 20815. 96753. 85395.  1731. 93955. 97477. 94501.
 75078. 76542. 95135. 33621. 78414. 93010. 92107. 92118. 95828. 23707.
 23435. 21769. 96706. 21042.]
823
========================================
columns : Model Year
0         2020
1         2022
2         2023
3         2018
4         2018
          ...
150477    2023
150478    2023
150479    2021
150480    2023
150481    2022
Name: Model Year, Length: 150482, dtype: int64
[2020 2022 2023 2018 2017 2016 2019 2013 2015 2014 2021 2011 2012 2024
 2010 2008 2002 2000 1998 2003 1999 1997]
22
========================================
columns : Make
0         HYUNDAI
1            JEEP
2            JEEP
3           TESLA
4             BMW
           ...
150477        BMW
150478      TESLA
150479      TESLA
150480        BMW
150481      TESLA
Name: Make, Length: 150482, dtype: str
<ArrowStringArray>
[             'HYUNDAI',                 'JEEP',                'TESLA',
                  'BMW',             'CHRYSLER',                 'FORD',
               'TOYOTA',                 'AUDI',               'NISSAN',
                  'KIA',            'CHEVROLET',           'VOLKSWAGEN',
                 'FIAT',                 'MINI',                'SMART',
               'RIVIAN',                'VOLVO',              'PORSCHE',
                'HONDA',           'MITSUBISHI',               'SUBARU',
             'POLESTAR',        'MERCEDES-BENZ',             'CADILLAC',
               'JAGUAR',              'LINCOLN',              'GENESIS',
                'LUCID',                'LEXUS',               'FISKER',
                'MAZDA',           'LAND ROVER',                'TH!NK',
       'AZURE DYNAMICS',           'ALFA ROMEO', 'WHEEGO ELECTRIC CARS',
              'BENTLEY']
Length: 37, dtype: str
37
========================================
columns : Model
0                   KONA
1         GRAND CHEROKEE
2         GRAND CHEROKEE
3                MODEL 3
4                     I3
               ...
150477                I4
150478           MODEL 3
150479           MODEL Y
150480                X5
150481           MODEL Y
Name: Model, Length: 150482, dtype: str
<ArrowStringArray>
[          'KONA', 'GRAND CHEROKEE',        'MODEL 3',             'I3',
       'PACIFICA',        'MODEL Y',         'FUSION',    'PRIUS PRIME',
         'E-TRON',           'LEAF',
 ...
        'S-CLASS',         'RANGER',           'GV70',         'TONALE',
         'WHEEGO',            '918',    'FLYING SPUR',          '745LE',
    'S-10 PICKUP',       'BENTAYGA']
Length: 127, dtype: str
127
========================================
columns : Electric Vehicle Type
0                 Battery Electric Vehicle (BEV)
1         Plug-in Hybrid Electric Vehicle (PHEV)
2         Plug-in Hybrid Electric Vehicle (PHEV)
3                 Battery Electric Vehicle (BEV)
4         Plug-in Hybrid Electric Vehicle (PHEV)
                           ...
150477            Battery Electric Vehicle (BEV)
150478            Battery Electric Vehicle (BEV)
150479            Battery Electric Vehicle (BEV)
150480    Plug-in Hybrid Electric Vehicle (PHEV)
150481            Battery Electric Vehicle (BEV)
Name: Electric Vehicle Type, Length: 150482, dtype: str
<ArrowStringArray>
['Battery Electric Vehicle (BEV)', 'Plug-in Hybrid Electric Vehicle (PHEV)']
Length: 2, dtype: str
2
========================================
columns : Clean Alternative Fuel Vehicle (CAFV) Eligibility
0                   Clean Alternative Fuel Vehicle Eligible
1                     Not eligible due to low battery range
2                     Not eligible due to low battery range
3                   Clean Alternative Fuel Vehicle Eligible
4                   Clean Alternative Fuel Vehicle Eligible
                                ...
150477    Eligibility unknown as battery range has not b...
150478    Eligibility unknown as battery range has not b...
150479    Eligibility unknown as battery range has not b...
150480              Clean Alternative Fuel Vehicle Eligible
150481    Eligibility unknown as battery range has not b...
Name: Clean Alternative Fuel Vehicle (CAFV) Eligibility, Length: 150482, dtype: str
<ArrowStringArray>
[                     'Clean Alternative Fuel Vehicle Eligible',
                        'Not eligible due to low battery range',
 'Eligibility unknown as battery range has not been researched']
Length: 3, dtype: str
3
========================================
columns : Electric Range
0         258
1          25
2          25
3         215
4          97
         ...
150477      0
150478      0
150479      0
150480     30
150481      0
Name: Electric Range, Length: 150482, dtype: int64
[258  25 215  97 266  33 291   0  19 220 204  84  26  13 249  38 103 322
 125 330 222 239  73 259  75  20 150  16  32  76  21 151 200  72 149 238
 289 208  34  53  30  81 110 210  22  58  17  18  87   6  93 308  14 107
 293  35  47  23 153  68 270  42 233  31 234  12  41 265  83  37  82  29
 203  10  40  24 114  39   8 126 218  15 124 337 111  27 192 245  28 170
  62 100  48  56  95   9  36  11  51  57  59  74]
102
========================================
columns : Base MSRP
0         0
1         0
2         0
3         0
4         0
         ..
150477    0
150478    0
150479    0
150480    0
150481    0
Name: Base MSRP, Length: 150482, dtype: int64
[     0  69900  31950  52900  32250  90700  54950  36900  59900  45600
  52650  39995  53400  64950  33950 102000  75095 110950  44100  81100
 184400  36800  43700  55700  34995  91250 109000  98950  89100  32995
 845000]
31
========================================
columns : Legislative District
0         43.0
1          1.0
2         14.0
3         45.0
4         22.0
          ...
150477    19.0
150478    43.0
150479    43.0
150480     1.0
150481    40.0
Name: Legislative District, Length: 150482, dtype: float64
[43.  1. 14. 45. 22. 38. 47. 10. 48. 26. 21. 20. 46. 23. 39. 35. 11. 44.
 31. 41. 32. 15. 33.  2. 36. 37.  5. 34. 13.  9. 40. 16.  3. 12.  7. 18.
 17. 28. 24. 30. 19. 49. 27. 29.  6.  8.  4. 25. 42. nan]
49
========================================
columns : DOL Vehicle ID
0         249675142
1         233928502
2         229675939
3         104714466
4         185498386
            ...
150477    251204075
150478    241344414
150479    180705626
150480    240473950
150481    207667589
Name: DOL Vehicle ID, Length: 150482, dtype: int64
[249675142 233928502 229675939 ... 180705626 240473950 207667589]
150482
========================================
columns : Vehicle Location
0            POINT (-122.34301 47.659185)
1            POINT (-122.20578 47.762405)
2         POINT (-120.6027202 46.5965625)
3            POINT (-122.209285 47.71124)
4            POINT (-122.89692 47.043535)
                       ...
150477       POINT (-123.60535 46.982215)
150478        POINT (-122.329075 47.6018)
150479       POINT (-122.34848 47.632405)
150480        POINT (-122.30842 47.78416)
150481       POINT (-122.338975 48.41333)
Name: Vehicle Location, Length: 150482, dtype: str
<ArrowStringArray>
[   'POINT (-122.34301 47.659185)',    'POINT (-122.20578 47.762405)',
 'POINT (-120.6027202 46.5965625)',    'POINT (-122.209285 47.71124)',
    'POINT (-122.89692 47.043535)',   'POINT (-122.1713847 48.10433)',
    'POINT (-122.111625 47.36078)',    'POINT (-122.151665 47.75855)',
 'POINT (-122.6880708 48.2179983)',    'POINT (-122.201905 47.61385)',
 ...
      'POINT (-97.365265 27.6835)',    'POINT (-119.042975 34.22104)',
   'POINT (-117.245975 32.746635)',      'POINT (-117.1777 32.68979)',
 'POINT (-121.4242477 38.5024987)',     'POINT (-76.34389 36.829805)',
      'POINT (-76.42047 36.87704)',      'POINT (-77.54559 39.44235)',
    'POINT (-158.019325 21.33516)',     'POINT (-76.83207 39.276485)']
Length: 823, dtype: str
822
========================================
columns : Electric Utility
0              CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
1             PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
2                                                PACIFICORP
3             PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
4                                    PUGET SOUND ENERGY INC
                                ...
150477    BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...
150478         CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
150479         CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
150480                               PUGET SOUND ENERGY INC
150481                               PUGET SOUND ENERGY INC
Name: Electric Utility, Length: 150482, dtype: str
<ArrowStringArray>
[                                                                    'CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)',
                                                                    'PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)',
                                                                                                       'PACIFICORP',
                                                                                           'PUGET SOUND ENERGY INC',
                                                                                                      'AVISTA CORP',
                                                                                'NO KNOWN ELECTRIC UTILITY SERVICE',
                                                                                    'MODERN ELECTRIC WATER COMPANY',
                                                                                        'PUD NO 1 OF CHELAN COUNTY',
                                                                                         'PUD NO 2 OF GRANT COUNTY',
                                                 'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLARK COUNTY - (WA)',
                                                                                       'PUD NO 1 OF DOUGLAS COUNTY',
                                  'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY',
                            'BONNEVILLE POWER ADMINISTRATION||PUGET SOUND ENERGY INC||PUD NO 1 OF JEFFERSON COUNTY',
                                                      'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF COWLITZ COUNTY',
                           'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF MASON COUNTY|PUD NO 1 OF JEFFERSON COUNTY',
                                                      'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLALLAM COUNTY',
                                     'BONNEVILLE POWER ADMINISTRATION||PACIFICORP||PUD NO 1 OF CLARK COUNTY - (WA)',
               'BONNEVILLE POWER ADMINISTRATION||TOWN OF STEILACOOM|CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY',
                                       'BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||INLAND POWER & LIGHT COMPANY',
                                                         'BONNEVILLE POWER ADMINISTRATION||CITY OF RICHLAND - (WA)',
                                                                      'CITY OF TACOMA - (WA)||TANNER ELECTRIC COOP',
                                          'BONNEVILLE POWER ADMINISTRATION||PACIFICORP||BENTON RURAL ELECTRIC ASSN',
                                                       'BONNEVILLE POWER ADMINISTRATION||PUD 1 OF SNOHOMISH COUNTY',

In [46]:
constant_cols = [
    col for col in df.columns
    if df[col].nunique() <= 1
]

print(constant_cols)

[]

In [47]:
for col in df.columns:
    top_frequency = df[col].value_counts(normalize=True, dropna=False).iloc[0]
    
    if top_frequency > 0.95:
        print(col, round(top_frequency * 100, 2), "%")

State 99.77 %
Base MSRP 97.7 %

## Statistic's

In [50]:
df.describe(include = "all")

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
count,150482,150479,150479,150482,150479.000000,150482.000000,150482,150482,150482,150482,150482.000000,150482.000000,150141.000000,1.504820e+05,150475,150479,1.504790e+05
unique,9529,183,683,41,NaN,NaN,37,127,2,3,NaN,NaN,NaN,NaN,822,76,NaN
top,7SAYGDEE7P,King,Seattle,WA,NaN,NaN,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,NaN,NaN,NaN,NaN,POINT (-122.12302 47.67668),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),NaN
freq,807,79075,25675,150141,NaN,NaN,68983,28502,116807,69698,NaN,NaN,NaN,NaN,3869,55634,NaN
mean,NaN,NaN,NaN,NaN,98168.344154,2020.005436,NaN,NaN,NaN,NaN,67.877839,1312.644735,29.343950,2.111122e+08,NaN,NaN,5.297195e+10
std,NaN,NaN,NaN,NaN,2473.612184,3.015209,NaN,NaN,NaN,NaN,96.230009,9231.310215,14.824829,8.196388e+07,NaN,NaN,1.638841e+09
min,NaN,NaN,NaN,NaN,1730.000000,1997.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,4.385000e+03,NaN,NaN,1.081042e+09
25%,NaN,NaN,NaN,NaN,98052.000000,2018.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,18.000000,1.693473e+08,NaN,NaN,5.303301e+10
50%,NaN,NaN,NaN,NaN,98122.000000,2021.000000,NaN,NaN,NaN,NaN,18.000000,0.000000,33.000000,2.150306e+08,NaN,NaN,5.303303e+10
75%,NaN,NaN,NaN,NaN,98370.000000,2023.000000,NaN,NaN,NaN,NaN,97.000000,0.000000,43.000000,2.399119e+08,NaN,NaN,5.305307e+10
max,NaN,NaN,NaN,NaN,99577.000000,2024.000000,NaN,NaN,NaN,NaN,337.000000,845000.000000,49.000000,4.792548e+08,NaN,NaN,5.603300e+10

In [49]:
df.describe(include = "number").T

,count,mean,std,min,25%,50%,75%,max
Postal Code,150479.0,9.816834e+04,2.473612e+03,1.730000e+03,9.805200e+04,9.812200e+04,9.837000e+04,9.957700e+04
Model Year,150482.0,2.020005e+03,3.015209e+00,1.997000e+03,2.018000e+03,2.021000e+03,2.023000e+03,2.024000e+03
Electric Range,150482.0,6.787784e+01,9.623001e+01,0.000000e+00,0.000000e+00,1.800000e+01,9.700000e+01,3.370000e+02
Base MSRP,150482.0,1.312645e+03,9.231310e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.450000e+05
Legislative District,150141.0,2.934395e+01,1.482483e+01,1.000000e+00,1.800000e+01,3.300000e+01,4.300000e+01,4.900000e+01
DOL Vehicle ID,150482.0,2.111122e+08,8.196388e+07,4.385000e+03,1.693473e+08,2.150306e+08,2.399119e+08,4.792548e+08
2020 Census Tract,150479.0,5.297195e+10,1.638841e+09,1.081042e+09,5.303301e+10,5.303303e+10,5.305307e+10,5.603300e+10

In [53]:
for col in df.columns:
    print(f"\n{'=' * 50}")
    print(f"Column: {col}")
    print(f"{'=' * 50}")
    
    display(df[col].describe())

==================================================
Column: VIN (1-10)
==================================================

count         150482
unique          9529
top       7SAYGDEE7P
freq             807
Name: VIN (1-10), dtype: object

==================================================
Column: County
==================================================

count     150479
unique       183
top         King
freq       79075
Name: County, dtype: object

==================================================
Column: City
==================================================

count      150479
unique        683
top       Seattle
freq        25675
Name: City, dtype: object

==================================================
Column: State
==================================================

count     150482
unique        41
top           WA
freq      150141
Name: State, dtype: object

==================================================
Column: Postal Code
==================================================

count    150479.000000
mean      98168.344154
std        2473.612184
min        1730.000000
25%       98052.000000
50%       98122.000000
75%       98370.000000
max       99577.000000
Name: Postal Code, dtype: float64

==================================================
Column: Model Year
==================================================

count    150482.000000
mean       2020.005436
std           3.015209
min        1997.000000
25%        2018.000000
50%        2021.000000
75%        2023.000000
max        2024.000000
Name: Model Year, dtype: float64

==================================================
Column: Make
==================================================

count     150482
unique        37
top        TESLA
freq       68983
Name: Make, dtype: object

==================================================
Column: Model
==================================================

count      150482
unique        127
top       MODEL Y
freq        28502
Name: Model, dtype: object

==================================================
Column: Electric Vehicle Type
==================================================

count                             150482
unique                                 2
top       Battery Electric Vehicle (BEV)
freq                              116807
Name: Electric Vehicle Type, dtype: object

==================================================
Column: Clean Alternative Fuel Vehicle (CAFV) Eligibility
==================================================

count                                                150482
unique                                                    3
top       Eligibility unknown as battery range has not b...
freq                                                  69698
Name: Clean Alternative Fuel Vehicle (CAFV) Eligibility, dtype: object

==================================================
Column: Electric Range
==================================================

count    150482.000000
mean         67.877839
std          96.230009
min           0.000000
25%           0.000000
50%          18.000000
75%          97.000000
max         337.000000
Name: Electric Range, dtype: float64

==================================================
Column: Base MSRP
==================================================

count    150482.000000
mean       1312.644735
std        9231.310215
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max      845000.000000
Name: Base MSRP, dtype: float64

==================================================
Column: Legislative District
==================================================

count    150141.000000
mean         29.343950
std          14.824829
min           1.000000
25%          18.000000
50%          33.000000
75%          43.000000
max          49.000000
Name: Legislative District, dtype: float64

==================================================
Column: DOL Vehicle ID
==================================================

count    1.504820e+05
mean     2.111122e+08
std      8.196388e+07
min      4.385000e+03
25%      1.693473e+08
50%      2.150306e+08
75%      2.399119e+08
max      4.792548e+08
Name: DOL Vehicle ID, dtype: float64

==================================================
Column: Vehicle Location
==================================================

count                          150475
unique                            822
top       POINT (-122.12302 47.67668)
freq                             3869
Name: Vehicle Location, dtype: object

==================================================
Column: Electric Utility
==================================================

count                                            150479
unique                                               76
top       PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
freq                                              55634
Name: Electric Utility, dtype: object

==================================================
Column: 2020 Census Tract
==================================================

count    1.504790e+05
mean     5.297195e+10
std      1.638841e+09
min      1.081042e+09
25%      5.303301e+10
50%      5.303303e+10
75%      5.305307e+10
max      5.603300e+10
Name: 2020 Census Tract, dtype: float64

In [54]:
for col in df.columns:
    print(f"\n{'=' * 60}")
    print(f"Column: {col}")
    print(f"Data Type: {df[col].dtype}")
    print(f"Missing Values: {df[col].isna().sum()}")
    print(f"Unique Values: {df[col].nunique()}")
    print(f"Duplicate Values: {df[col].duplicated().sum()}")
    
    display(df[col].describe())

============================================================
Column: VIN (1-10)
Data Type: str
Missing Values: 0
Unique Values: 9529
Duplicate Values: 140953

count         150482
unique          9529
top       7SAYGDEE7P
freq             807
Name: VIN (1-10), dtype: object

============================================================
Column: County
Data Type: str
Missing Values: 3
Unique Values: 183
Duplicate Values: 150298

count     150479
unique       183
top         King
freq       79075
Name: County, dtype: object

============================================================
Column: City
Data Type: str
Missing Values: 3
Unique Values: 683
Duplicate Values: 149798

count      150479
unique        683
top       Seattle
freq        25675
Name: City, dtype: object

============================================================
Column: State
Data Type: str
Missing Values: 0
Unique Values: 41
Duplicate Values: 150441

count     150482
unique        41
top           WA
freq      150141
Name: State, dtype: object

============================================================
Column: Postal Code
Data Type: float64
Missing Values: 3
Unique Values: 823
Duplicate Values: 149658

count    150479.000000
mean      98168.344154
std        2473.612184
min        1730.000000
25%       98052.000000
50%       98122.000000
75%       98370.000000
max       99577.000000
Name: Postal Code, dtype: float64

============================================================
Column: Model Year
Data Type: int64
Missing Values: 0
Unique Values: 22
Duplicate Values: 150460

count    150482.000000
mean       2020.005436
std           3.015209
min        1997.000000
25%        2018.000000
50%        2021.000000
75%        2023.000000
max        2024.000000
Name: Model Year, dtype: float64

============================================================
Column: Make
Data Type: str
Missing Values: 0
Unique Values: 37
Duplicate Values: 150445

count     150482
unique        37
top        TESLA
freq       68983
Name: Make, dtype: object

============================================================
Column: Model
Data Type: str
Missing Values: 0
Unique Values: 127
Duplicate Values: 150355

count      150482
unique        127
top       MODEL Y
freq        28502
Name: Model, dtype: object

============================================================
Column: Electric Vehicle Type
Data Type: str
Missing Values: 0
Unique Values: 2
Duplicate Values: 150480

count                             150482
unique                                 2
top       Battery Electric Vehicle (BEV)
freq                              116807
Name: Electric Vehicle Type, dtype: object

============================================================
Column: Clean Alternative Fuel Vehicle (CAFV) Eligibility
Data Type: str
Missing Values: 0
Unique Values: 3
Duplicate Values: 150479

count                                                150482
unique                                                    3
top       Eligibility unknown as battery range has not b...
freq                                                  69698
Name: Clean Alternative Fuel Vehicle (CAFV) Eligibility, dtype: object

============================================================
Column: Electric Range
Data Type: int64
Missing Values: 0
Unique Values: 102
Duplicate Values: 150380

count    150482.000000
mean         67.877839
std          96.230009
min           0.000000
25%           0.000000
50%          18.000000
75%          97.000000
max         337.000000
Name: Electric Range, dtype: float64

============================================================
Column: Base MSRP
Data Type: int64
Missing Values: 0
Unique Values: 31
Duplicate Values: 150451

count    150482.000000
mean       1312.644735
std        9231.310215
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max      845000.000000
Name: Base MSRP, dtype: float64

============================================================
Column: Legislative District
Data Type: float64
Missing Values: 341
Unique Values: 49
Duplicate Values: 150432

count    150141.000000
mean         29.343950
std          14.824829
min           1.000000
25%          18.000000
50%          33.000000
75%          43.000000
max          49.000000
Name: Legislative District, dtype: float64

============================================================
Column: DOL Vehicle ID
Data Type: int64
Missing Values: 0
Unique Values: 150482
Duplicate Values: 0

count    1.504820e+05
mean     2.111122e+08
std      8.196388e+07
min      4.385000e+03
25%      1.693473e+08
50%      2.150306e+08
75%      2.399119e+08
max      4.792548e+08
Name: DOL Vehicle ID, dtype: float64

============================================================
Column: Vehicle Location
Data Type: str
Missing Values: 7
Unique Values: 822
Duplicate Values: 149659

count                          150475
unique                            822
top       POINT (-122.12302 47.67668)
freq                             3869
Name: Vehicle Location, dtype: object

============================================================
Column: Electric Utility
Data Type: str
Missing Values: 3
Unique Values: 76
Duplicate Values: 150405

count                                            150479
unique                                               76
top       PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
freq                                              55634
Name: Electric Utility, dtype: object

============================================================
Column: 2020 Census Tract
Data Type: float64
Missing Values: 3
Unique Values: 2079
Duplicate Values: 148402

count    1.504790e+05
mean     5.297195e+10
std      1.638841e+09
min      1.081042e+09
25%      5.303301e+10
50%      5.303303e+10
75%      5.305307e+10
max      5.603300e+10
Name: 2020 Census Tract, dtype: float64

In [55]:
df.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', '2020 Census Tract'],
      dtype='str')

In [58]:
df.rename(columns={
    "VIN (1-10)": "VIN",
    "County": "County",
    "Postal Code": "Postal_Code",
    "Model Year": "Model_Year",
    "Electric Vehicle Type": "EV_Type",
    "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "CAFV_Eligibility",
    "Electric Range": "Electric_Range",
    "Base MSRP": "Base_MSRP",
    "DOL Vehicle ID": "Vehicle_ID",
    "Vehicle Location": "Vehicle_Location",
    "Electric Utility": "Electric_Utility",
    "2020 Census Tract": "Census_Tract"
}, inplace=True)

print(df.columns.tolist())

['VIN', 'County', 'City', 'State', 'Postal_Code', 'Model_Year', 'Make', 'Model', 'EV_Type', 'CAFV_Eligibility', 'Electric_Range', 'Base_MSRP', 'Legislative District', 'Vehicle_ID', 'Vehicle_Location', 'Electric_Utility', 'Census_Tract']

In [59]:
display(len(df.columns))

17

In [60]:
df

,VIN,County,City,State,Postal_Code,Model_Year,Make,Model,EV_Type,CAFV_Eligibility,Electric_Range,Base_MSRP,Legislative District,Vehicle_ID,Vehicle_Location,Electric_Utility,Census_Tract
0,KM8K33AGXL,King,Seattle,WA,98103.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258,0,43.0,249675142,POINT (-122.34301 47.659185),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,1C4RJYB61N,King,Bothell,WA,98011.0,2022,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,1.0,233928502,POINT (-122.20578 47.762405),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,1C4RJYD61P,Yakima,Yakima,WA,98908.0,2023,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,14.0,229675939,POINT (-120.6027202 46.5965625),PACIFICORP,5.307700e+10
3,5YJ3E1EA7J,King,Kirkland,WA,98034.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,45.0,104714466,POINT (-122.209285 47.71124),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
4,WBY7Z8C5XJ,Thurston,Olympia,WA,98501.0,2018,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,97,0,22.0,185498386,POINT (-122.89692 47.043535),PUGET SOUND ENERGY INC,5.306701e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150477,WBY43AW05P,Grays Harbor,Montesano,WA,98563.0,2023,BMW,I4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,19.0,251204075,POINT (-123.60535 46.982215),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,5.302700e+10
150478,5YJ3E1EB7P,King,Seattle,WA,98104.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,43.0,241344414,POINT (-122.329075 47.6018),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
150479,5YJYGDEEXM,King,Seattle,WA,98109.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,43.0,180705626,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
150480,5UXTA6C08P,Snohomish,Mountlake Terrace,WA,98043.0,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,1.0,240473950,POINT (-122.30842 47.78416),PUGET SOUND ENERGY INC,5.306105e+10
150481,7SAYGDEF8N,Skagit,Mount Vernon,WA,98273.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,40.0,207667589,POINT (-122.338975 48.41333),PUGET SOUND ENERGY INC,5.305795e+10

In [61]:
df.isnull().sum()

VIN                       0
County                    3
City                      3
State                     0
Postal_Code               3
Model_Year                0
Make                      0
Model                     0
EV_Type                   0
CAFV_Eligibility          0
Electric_Range            0
Base_MSRP                 0
Legislative District    341
Vehicle_ID                0
Vehicle_Location          7
Electric_Utility          3
Census_Tract              3
dtype: int64

In [65]:
missing = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_%": (df.isna().mean() * 100).round(2)
})

missing = missing[missing["Missing_Count"] > 0].sort_values(
    "Missing_Count",
    ascending=False
)

display(missing)

                      Missing_Count  Missing_%
Legislative District            341       0.23
Vehicle_Location                  7       0.00
County                            3       0.00
Postal_Code                       3       0.00
City                              3       0.00
Electric_Utility                  3       0.00
Census_Tract                      3       0.00

In [66]:
missing_cols = missing.index.tolist()

display(df[df[missing_cols].isna().any(axis=1)])

,VIN,County,City,State,Postal_Code,Model_Year,Make,Model,EV_Type,CAFV_Eligibility,Electric_Range,Base_MSRP,Legislative District,Vehicle_ID,Vehicle_Location,Electric_Utility,Census_Tract
63985,KNDCD3LD6N,Marin,San Rafael,CA,94901.0,2022,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26,0,NaN,181521700,POINT (-122.5260879 37.9702346),NON WASHINGTON STATE ELECTRIC UTILITY,6.041111e+09
76254,WA11AAGE5P,Lake,Libertyville,IL,60048.0,2023,AUDI,E-TRON,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,237839185,POINT (-87.95161 42.28444),NON WASHINGTON STATE ELECTRIC UTILITY,1.709786e+10
77059,2C4RC1N72J,Douglas,Omaha,NE,68135.0,2018,CHRYSLER,PACIFICA,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,33,0,NaN,322474764,POINT (-96.1699821 41.1973705),NON WASHINGTON STATE ELECTRIC UTILITY,3.105501e+10
78462,5YJYGDED0M,San Diego,San Diego,CA,92131.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,187492175,POINT (-117.090485 32.932535),NON WASHINGTON STATE ELECTRIC UTILITY,6.073017e+09
80649,5YJYGDEF3L,Platte,Platte City,MO,64079.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291,0,NaN,132400684,POINT (-94.77962 39.36557),NON WASHINGTON STATE ELECTRIC UTILITY,2.916503e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150138,JTDKN3DP2E,Honolulu,Honolulu,HI,96818.0,2014,TOYOTA,PRIUS PLUG-IN,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,6,0,NaN,209333078,POINT (-157.9124 21.343675),NON WASHINGTON STATE ELECTRIC UTILITY,1.500301e+10
150143,JTMEB3FV8P,Frederick,Middletown,MD,21769.0,2023,TOYOTA,RAV4 PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42,0,NaN,251425919,POINT (-77.54559 39.44235),NON WASHINGTON STATE ELECTRIC UTILITY,2.402175e+10
150161,5YJ3E1EA0L,San Diego,Chula Vista,CA,91913.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,266,0,NaN,215073008,POINT (-116.979155 32.627645),NON WASHINGTON STATE ELECTRIC UTILITY,6.073013e+09
150179,1C4JJXP69M,Honolulu,Ewa Beach,HI,96706.0,2021,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,NaN,185357882,POINT (-158.019325 21.33516),NON WASHINGTON STATE ELECTRIC UTILITY,1.500301e+10
150473,YV4BR0CZ5N,Howard,Ellicott City,MD,21042.0,2022,VOLVO,XC90,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,18,0,NaN,185596036,POINT (-76.83207 39.276485),NON WASHINGTON STATE ELECTRIC UTILITY,2.402760e+10

In [68]:
display(
    df[df["Legislative District"].isna()]
    [["State", "City", "Postal_Code", "Legislative District"]]
    .head(20)
)

      State           City  Postal_Code  Legislative District
63985    CA     San Rafael      94901.0                   NaN
76254    IL   Libertyville      60048.0                   NaN
77059    NE          Omaha      68135.0                   NaN
78462    CA      San Diego      92131.0                   NaN
80649    MO    Platte City      64079.0                   NaN
81475    CA     Ridgecrest      93555.0                   NaN
81704    IL  Highland Park      60035.0                   NaN
82705    AZ          Tempe      85281.0                   NaN
84601    VA        Henrico      23238.0                   NaN
84909    CA     Buena Park      90621.0                   NaN
85620    KY         Goshen      40026.0                   NaN
87358    NC        Raeford      28376.0                   NaN
89348    CA     Buena Park      90621.0                   NaN
89642    MD      Annapolis      21401.0                   NaN
90637    MD      Frederick      21701.0                   NaN
90736    DC     Washington      20003.0                   NaN
90966    NE          Omaha      68102.0                   NaN
91494    WY       Cheyenne      82001.0                   NaN
91732    CA        Gardena      90249.0                   NaN
91891    IL   Libertyville      60048.0                   NaN

In [69]:
categorical_cols = [
    "County",
    "City",
    "Vehicle_Location",
    "Electric_Utility"
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [72]:
df[categorical_cols].isna().sum()

County              0
City                0
Vehicle_Location    0
Electric_Utility    0
dtype: int64

In [73]:
df["Legislative District"] = df["Legislative District"].fillna(
    df["Legislative District"].median(), inplace = True
)

In [75]:
df['Legislative District']

0         43.0
1          1.0
2         14.0
3         45.0
4         22.0
          ...
150477    19.0
150478    43.0
150479    43.0
150480     1.0
150481    40.0
Name: Legislative District, Length: 150482, dtype: float64

In [76]:
df["Census_Tract"].isnull().sum()

np.int64(3)

In [78]:
print(df["Census_Tract"].dtype)

float64

In [79]:
df["Census_Tract"] = df["Census_Tract"].astype("string")

In [80]:
print(df["Census_Tract"].dtype)

string

In [81]:
display(df["Census_Tract"].describe())

count            150479
unique             2079
top       53033028200.0
freq               1758
Name: Census_Tract, dtype: object

In [84]:
df.Postal_Code.dtype

dtype('float64')

In [85]:
df["Postal_Code"] = df["Postal_Code"].astype("string")

In [86]:
df.Postal_Code.dtype

In [87]:
df.Postal_Code

0         98103.0
1         98011.0
2         98908.0
3         98034.0
4         98501.0
           ...
150477    98563.0
150478    98104.0
150479    98109.0
150480    98043.0
150481    98273.0
Name: Postal_Code, Length: 150482, dtype: string

In [88]:
df.VIN.dtype

In [89]:
df.Vehicle_ID.dtype

dtype('int64')

In [90]:
df["Vehicle_ID"] = df["Vehicle_ID"].astype("string")

In [91]:
df.Vehicle_ID.dtype

In [92]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150482 entries, 0 to 150481
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   VIN                   150482 non-null  str
 1   County                150482 non-null  str
 2   City                  150482 non-null  str
 3   State                 150482 non-null  str
 4   Postal_Code           150479 non-null  string
 5   Model_Year            150482 non-null  int64
 6   Make                  150482 non-null  str
 7   Model                 150482 non-null  str
 8   EV_Type               150482 non-null  str
 9   CAFV_Eligibility      150482 non-null  str
 10  Electric_Range        150482 non-null  int64
 11  Base_MSRP             150482 non-null  int64
 12  Legislative District  150482 non-null  float64
 13  Vehicle_ID            150482 non-null  string
 14  Vehicle_Location      150482 non-null  str
 15  Electric_Utility      150482 non-null  str
 16  Census_Tract          150479 non-null  string
dtypes: float64(1), int64(3), str(10), string(3)
memory usage: 51.1 MB

In [93]:
df.isnull().sum()

VIN                     0
County                  0
City                    0
State                   0
Postal_Code             3
Model_Year              0
Make                    0
Model                   0
EV_Type                 0
CAFV_Eligibility        0
Electric_Range          0
Base_MSRP               0
Legislative District    0
Vehicle_ID              0
Vehicle_Location        0
Electric_Utility        0
Census_Tract            3
dtype: int64

In [94]:
display(
    df[df["Postal_Code"].isnull() | df["Census_Tract"].isnull()]
    [["VIN", "County", "City", "State", "Postal_Code", "Census_Tract"]]
)

               VIN County     City State Postal_Code Census_Tract
133103  5YJRE11B48   King  Seattle    BC        <NA>         <NA>
136622  5YJ3E1EA5K   King  Seattle    BC        <NA>         <NA>
140136  1N4AZ0CP1D   King  Seattle    AP        <NA>         <NA>

In [95]:
df["Postal_Code"] = df["Postal_Code"].fillna("Unknown")
df["Census_Tract"] = df["Census_Tract"].fillna("Unknown")

In [98]:
df[["Postal_Code","Census_Tract"]].isnull().sum()

Postal_Code     0
Census_Tract    0
dtype: int64

In [99]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150482 entries, 0 to 150481
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   VIN                   150482 non-null  str
 1   County                150482 non-null  str
 2   City                  150482 non-null  str
 3   State                 150482 non-null  str
 4   Postal_Code           150482 non-null  string
 5   Model_Year            150482 non-null  int64
 6   Make                  150482 non-null  str
 7   Model                 150482 non-null  str
 8   EV_Type               150482 non-null  str
 9   CAFV_Eligibility      150482 non-null  str
 10  Electric_Range        150482 non-null  int64
 11  Base_MSRP             150482 non-null  int64
 12  Legislative District  150482 non-null  float64
 13  Vehicle_ID            150482 non-null  string
 14  Vehicle_Location      150482 non-null  str
 15  Electric_Utility      150482 non-null  str
 16  Census_Tract          150482 non-null  string
dtypes: float64(1), int64(3), str(10), string(3)
memory usage: 51.0 MB

In [101]:
df["Legislative_District"] = df["Legislative District"].astype("Int64")

In [102]:
df.Legislative_District.dtype

Int64Dtype()

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150482 entries, 0 to 150481
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   VIN                   150482 non-null  str
 1   County                150482 non-null  str
 2   City                  150482 non-null  str
 3   State                 150482 non-null  str
 4   Postal_Code           150482 non-null  string
 5   Model_Year            150482 non-null  int64
 6   Make                  150482 non-null  str
 7   Model                 150482 non-null  str
 8   EV_Type               150482 non-null  str
 9   CAFV_Eligibility      150482 non-null  str
 10  Electric_Range        150482 non-null  int64
 11  Base_MSRP             150482 non-null  int64
 12  Legislative District  150482 non-null  Int64
 13  Vehicle_ID            150482 non-null  string
 14  Vehicle_Location      150482 non-null  str
 15  Electric_Utility      150482 non-null  str
 16  Census_Tract          150482 non-null  string
 17  Legislative_District  150482 non-null  Int64
dtypes: Int64(2), int64(3), str(10), string(3)
memory usage: 52.5 MB

In [104]:
df.isnull().sum()

VIN                     0
County                  0
City                    0
State                   0
Postal_Code             0
Model_Year              0
Make                    0
Model                   0
EV_Type                 0
CAFV_Eligibility        0
Electric_Range          0
Base_MSRP               0
Legislative District    0
Vehicle_ID              0
Vehicle_Location        0
Electric_Utility        0
Census_Tract            0
Legislative_District    0
dtype: int64

In [105]:
df.columns

Index(['VIN', 'County', 'City', 'State', 'Postal_Code', 'Model_Year', 'Make',
       'Model', 'EV_Type', 'CAFV_Eligibility', 'Electric_Range', 'Base_MSRP',
       'Legislative District', 'Vehicle_ID', 'Vehicle_Location',
       'Electric_Utility', 'Census_Tract', 'Legislative_District'],
      dtype='str')

In [108]:
for col in df.columns:
    count = df[col].value_counts(dropna=False)
    percent = df[col].value_counts(normalize=True, dropna=False) * 100

    result = pd.DataFrame({
        "Count": count,
        "Percentage": percent.round(2)
    })

    print(f"\n{'=' * 60}")
    print(f"Column: {col}")
    display(result)

============================================================
Column: VIN

            Count  Percentage
VIN
7SAYGDEE7P    807        0.54
7SAYGDEE6P    802        0.53
7SAYGDEE8P    775        0.52
7SAYGDEE2P    775        0.52
7SAYGDEEXP    772        0.51
...           ...         ...
1FMCU0EZ8M      1        0.00
7FCTGAAL0P      1        0.00
WA1CAAGE9R      1        0.00
WA1G2BFZ5N      1        0.00
JN1CF0BB5P      1        0.00

[9529 rows x 2 columns]

============================================================
Column: County

            Count  Percentage
County
King        79078       52.55
Snohomish   17307       11.50
Pierce      11542        7.67
Clark        8855        5.88
Thurston     5403        3.59
...           ...         ...
Hennepin        1        0.00
Maui            1        0.00
Bell            1        0.00
Portsmouth      1        0.00
Suffolk         1        0.00

[183 rows x 2 columns]

============================================================
Column: City

               Count  Percentage
City
Seattle        25678       17.06
Bellevue        7691        5.11
Redmond         5502        3.66
Vancouver       5310        3.53
Bothell         4861        3.23
...              ...         ...
Coronado           1        0.00
Suffolk            1        0.00
Middletown         1        0.00
Ewa Beach          1        0.00
Ellicott City      1        0.00

[683 rows x 2 columns]

============================================================
Column: State

        Count  Percentage
State
WA     150141       99.77
CA         92        0.06
VA         35        0.02
MD         33        0.02
TX         20        0.01
NC         13        0.01
IL         12        0.01
AZ         11        0.01
CO         11        0.01
FL          9        0.01
NJ          9        0.01
OR          8        0.01
HI          8        0.01
CT          7        0.00
NY          7        0.00
NV          6        0.00
SC          6        0.00
DC          5        0.00
GA          5        0.00
MO          4        0.00
NE          3        0.00
KY          3        0.00
AL          3        0.00
LA          3        0.00
MA          3        0.00
WY          2        0.00
OH          2        0.00
PA          2        0.00
IN          2        0.00
BC          2        0.00
AR          2        0.00
ID          2        0.00
UT          2        0.00
KS          2        0.00
MS          1        0.00
MT          1        0.00
DE          1        0.00
NH          1        0.00
AK          1        0.00
AP          1        0.00
MN          1        0.00

============================================================
Column: Postal_Code

             Count  Percentage
Postal_Code
98052.0       3869        2.57
98012.0       2753        1.83
98033.0       2619        1.74
98006.0       2457        1.63
98004.0       2456        1.63
...            ...         ...
23707.0          1         0.0
23435.0          1         0.0
21769.0          1         0.0
96706.0          1         0.0
21042.0          1         0.0

[824 rows x 2 columns]

============================================================
Column: Model_Year

            Count  Percentage
Model_Year
2023        37079       24.64
2022        27799       18.47
2021        18684       12.42
2018        14441        9.60
2020        11294        7.51
2019        10717        7.12
2017         8574        5.70
2016         5650        3.75
2015         4934        3.28
2013         4566        3.03
2014         3613        2.40
2012         1633        1.09
2011          796        0.53
2024          642        0.43
2010           24        0.02
2008           19        0.01
2000            8        0.01
1999            4        0.00
2002            2        0.00
1998            1        0.00
2003            1        0.00
1997            1        0.00

============================================================
Column: Make

                      Count  Percentage
Make
TESLA                 68983       45.84
NISSAN                13497        8.97
CHEVROLET             12026        7.99
FORD                   7614        5.06
BMW                    6439        4.28
KIA                    6198        4.12
TOYOTA                 5223        3.47
VOLKSWAGEN             4074        2.71
VOLVO                  3536        2.35
JEEP                   3292        2.19
HYUNDAI                3171        2.11
AUDI                   3006        2.00
CHRYSLER               2642        1.76
RIVIAN                 2483        1.65
MERCEDES-BENZ          1054        0.70
PORSCHE                1028        0.68
MITSUBISHI              849        0.56
HONDA                   810        0.54
FIAT                    806        0.54
MINI                    791        0.53
POLESTAR                764        0.51
SUBARU                  623        0.41
SMART                   274        0.18
LINCOLN                 229        0.15
JAGUAR                  228        0.15
LUCID                   190        0.13
CADILLAC                176        0.12
LEXUS                   138        0.09
MAZDA                   136        0.09
GENESIS                 107        0.07
LAND ROVER               47        0.03
FISKER                   17        0.01
ALFA ROMEO               12        0.01
AZURE DYNAMICS            9        0.01
TH!NK                     5        0.00
WHEEGO ELECTRIC CARS      3        0.00
BENTLEY                   2        0.00

============================================================
Column: Model

             Count  Percentage
Model
MODEL Y      28502       18.94
MODEL 3      27709       18.41
LEAF         13187        8.76
MODEL S       7611        5.06
BOLT EV       5733        3.81
...            ...         ...
745LE            2        0.00
918              1        0.00
FLYING SPUR      1        0.00
S-10 PICKUP      1        0.00
BENTAYGA         1        0.00

[127 rows x 2 columns]

============================================================
Column: EV_Type

                                         Count  Percentage
EV_Type
Battery Electric Vehicle (BEV)          116807       77.62
Plug-in Hybrid Electric Vehicle (PHEV)   33675       22.38

============================================================
Column: CAFV_Eligibility

                                                    Count  Percentage
CAFV_Eligibility
Eligibility unknown as battery range has not be...  69698       46.32
Clean Alternative Fuel Vehicle Eligible             62951       41.83
Not eligible due to low battery range               17833       11.85

============================================================
Column: Electric_Range

                Count  Percentage
Electric_Range
0               69698       46.32
215              6490        4.31
220              4125        2.74
84               4023        2.67
238              3611        2.40
...               ...         ...
74                  4        0.00
95                  3        0.00
11                  2        0.00
57                  1        0.00
59                  1        0.00

[102 rows x 2 columns]

============================================================
Column: Base_MSRP

            Count  Percentage
Base_MSRP
0          147027       97.70
69900        1441        0.96
31950         399        0.27
52900         218        0.14
32250         152        0.10
59900         134        0.09
54950         133        0.09
39995         117        0.08
36900         101        0.07
44100          97        0.06
45600          84        0.06
64950          83        0.06
33950          74        0.05
52650          68        0.05
34995          64        0.04
36800          53        0.04
55700          50        0.03
53400          34        0.02
110950         21        0.01
90700          19        0.01
81100          19        0.01
98950          19        0.01
102000         17        0.01
75095          15        0.01
184400         11        0.01
43700          10        0.01
109000          7        0.00
89100           6        0.00
91250           5        0.00
32995           3        0.00
845000          1        0.00

============================================================
Column: Legislative District

                      Count  Percentage
Legislative District
41                     9969        6.62
45                     9171        6.09
48                     8419        5.59
1                      6510        4.33
36                     6494        4.32
5                      6348        4.22
46                     5955        3.96
11                     5837        3.88
43                     5789        3.85
37                     4498        2.99
34                     4429        2.94
18                     4012        2.67
44                     3790        2.52
22                     3707        2.46
21                     3652        2.43
32                     3627        2.41
33                     3422        2.27
40                     3349        2.23
23                     3308         2.2
26                     2992        1.99
47                     2685        1.78
10                     2624        1.74
31                     2592        1.72
17                     2576        1.71
39                     2173        1.44
27                     2121        1.41
24                     2104         1.4
42                     2078        1.38
35                     2057        1.37
49                     2035        1.35
28                     1958         1.3
30                     1776        1.18
2                      1636        1.09
8                      1523        1.01
25                     1517        1.01
38                     1411        0.94
6                      1344        0.89
12                     1338        0.89
20                     1294        0.86
4                      1174        0.78
13                      982        0.65
29                      972        0.65
14                      963        0.64
19                      886        0.59
9                       839        0.56
16                      756         0.5
3                       732        0.49
7                       696        0.46
15                      362        0.24

============================================================
Column: Vehicle_ID

            Count  Percentage
Vehicle_ID
249675142       1         0.0
233928502       1         0.0
229675939       1         0.0
104714466       1         0.0
185498386       1         0.0
...           ...         ...
251204075       1         0.0
241344414       1         0.0
180705626       1         0.0
240473950       1         0.0
207667589       1         0.0

[150482 rows x 2 columns]

============================================================
Column: Vehicle_Location

                                Count  Percentage
Vehicle_Location
POINT (-122.12302 47.67668)      3876        2.58
POINT (-122.1876761 47.820517)   2753        1.83
POINT (-122.20264 47.6785)       2619        1.74
POINT (-122.16937 47.571015)     2457        1.63
POINT (-122.201905 47.61385)     2456        1.63
...                               ...         ...
POINT (-76.34389 36.829805)         1        0.00
POINT (-76.42047 36.87704)          1        0.00
POINT (-77.54559 39.44235)          1        0.00
POINT (-158.019325 21.33516)        1        0.00
POINT (-76.83207 39.276485)         1        0.00

[822 rows x 2 columns]

============================================================
Column: Electric_Utility

                                                    Count  Percentage
Electric_Utility
PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       55637       36.97
PUGET SOUND ENERGY INC                              29865       19.85
CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)        27268       18.12
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CL...   8643        5.74
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...   6622        4.40
PUGET SOUND ENERGY INC||PUD NO 1 OF WHATCOM COUNTY   3443        2.29
BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||I...   2244        1.49
BONNEVILLE POWER ADMINISTRATION||PUD 1 OF SNOHO...   1341        0.89
PACIFICORP                                           1102        0.73
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF BE...   1048        0.70
MODERN ELECTRIC WATER COMPANY                         917        0.61
PUD NO 1 OF CHELAN COUNTY                             863        0.57
BONNEVILLE POWER ADMINISTRATION||PUGET SOUND EN...    854        0.57
BONNEVILLE POWER ADMINISTRATION||ORCAS POWER & ...    840        0.56
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CO...    762        0.51
BONNEVILLE POWER ADMINISTRATION||CITY OF RICHLA...    752        0.50
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CL...    731        0.49
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...    615        0.41
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF GR...    518        0.34
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF FR...    479        0.32
PUD NO 2 OF GRANT COUNTY                              452        0.30
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...    385        0.26
NON WASHINGTON STATE ELECTRIC UTILITY                 338        0.22
AVISTA CORP                                           323        0.21
BONNEVILLE POWER ADMINISTRATION||VERA IRRIGATIO...    307        0.20
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...    294        0.20
PUD NO 1 OF DOUGLAS COUNTY                            293        0.19
BONNEVILLE POWER ADMINISTRATION||INLAND POWER &...    276        0.18
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF KL...    239        0.16
NO KNOWN ELECTRIC UTILITY SERVICE                     209        0.14
BONNEVILLE POWER ADMINISTRATION||PACIFICORP||PU...    203        0.13
CITY OF TACOMA - (WA)||TANNER ELECTRIC COOP           202        0.13
BONNEVILLE POWER ADMINISTRATION||CITY OF PORT A...    185        0.12
CITY OF BLAINE - (WA)||PUD NO 1 OF WHATCOM COUNTY     179        0.12
BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF PA...    177        0.12
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF SK...    164        0.11
BONNEVILLE POWER ADMINISTRATION||TOWN OF STEILA...    153        0.10
BONNEVILLE POWER ADMINISTRATION||CITY OF CENTRA...    152        0.10
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...    130        0.09
OKANOGAN COUNTY ELEC COOP, INC                        120        0.08
BONNEVILLE POWER ADMINISTRATION||CITY OF ELLENS...    104        0.07
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...     99        0.07
PUD NO 1 OF OKANOGAN COUNTY                            89        0.06
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...     89        0.06
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...     87        0.06
BONNEVILLE POWER ADMINISTRATION||PACIFICORP||BE...     85        0.06
BONNEVILLE POWER ADMINISTRATION||CITY OF MILTON...     68        0.05
BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||P...     60        0.04
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF WA...     49        0.03
PUD NO 1 OF PEND OREILLE COUNTY                        47        0.03
PUD NO 1 OF WHATCOM COUNTY                             41        0.03
BONNEVILLE POWER ADMINISTRATION||TOWN OF RUSTON...     41        0.03
BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||B...     37        0.02
CITY OF CHENEY - (WA)                                  36        0.02
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...     33        0.02
BONNEVILLE POWER ADMINISTRATION||BIG BEND ELECT...     30        0.02
BONNEVILLE POWER ADMINISTRATION||TOWN OF EATONV...     25        0.02
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF MA...     20        0.01
CITY OF TACOMA - (WA)                                  18        0.01
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF KI...     15        0.01
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF FE...     15        0.01
BONNEVILLE POWER ADMINISTRATION||PACIFICORP||CO...     14        0.01
BONNEVILLE POWER ADMINISTRATION||CITY OF MCCLEA...     14        0.01
BONNEVILLE POWER ADMINISTRATION||COLUMBIA RURAL...     13        0.01
CITY OF CHEWELAH                                        6        0.00
CITY OF SUMAS - (WA)||PUD NO 1 OF WHATCOM COUNTY        5        0.00
BONNEVILLE POWER ADMINISTRATION||BENTON RURAL E...      3        0.00
PORTLAND GENERAL ELECTRIC CO                            3        0.00
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA...      2        0.00
BONNEVILLE POWER ADMINISTRATION||CITY OF COULEE...      2        0.00
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF AS...      2        0.00
CITY OF SEATTLE - (WA)                                  1        0.00
BONNEVILLE POWER ADMINISTRATION||PENINSULA LIGH...      1        0.00
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF AS...      1        0.00
BONNEVILLE POWER ADMINISTRATION||NESPELEM VALLE...      1        0.00
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF JE...      1        0.00

============================================================
Column: Census_Tract

               Count  Percentage
Census_Tract
53033028200.0   1758        1.17
53033028500.0    963        0.64
53033032321.0    699        0.46
53033009300.0    558        0.37
53033026200.0    531        0.35
...              ...         ...
6095252801.0       1         0.0
51800075203.0      1         0.0
24021752602.0      1         0.0
15003008410.0      1         0.0
24027602201.0      1         0.0

[2080 rows x 2 columns]

============================================================
Column: Legislative_District

                      Count  Percentage
Legislative_District
41                     9969        6.62
45                     9171        6.09
48                     8419        5.59
1                      6510        4.33
36                     6494        4.32
5                      6348        4.22
46                     5955        3.96
11                     5837        3.88
43                     5789        3.85
37                     4498        2.99
34                     4429        2.94
18                     4012        2.67
44                     3790        2.52
22                     3707        2.46
21                     3652        2.43
32                     3627        2.41
33                     3422        2.27
40                     3349        2.23
23                     3308         2.2
26                     2992        1.99
47                     2685        1.78
10                     2624        1.74
31                     2592        1.72
17                     2576        1.71
39                     2173        1.44
27                     2121        1.41
24                     2104         1.4
42                     2078        1.38
35                     2057        1.37
49                     2035        1.35
28                     1958         1.3
30                     1776        1.18
2                      1636        1.09
8                      1523        1.01
25                     1517        1.01
38                     1411        0.94
6                      1344        0.89
12                     1338        0.89
20                     1294        0.86
4                      1174        0.78
13                      982        0.65
29                      972        0.65
14                      963        0.64
19                      886        0.59
9                       839        0.56
16                      756         0.5
3                       732        0.49
7                       696        0.46
15                      362        0.24

In [109]:
for col in df.columns:
    count = df[col].value_counts(dropna=False)
    
    result = pd.DataFrame({
        "Count": count,
        "Percentage": (count / len(df) * 100).round(2),
        "Cumulative %": (count / len(df) * 100).cumsum().round(2)
    })

    print(f"\n{'=' * 60}")
    print(f"Column: {col}")
    display(result)

============================================================
Column: VIN

            Count  Percentage  Cumulative %
VIN
7SAYGDEE7P    807        0.54          0.54
7SAYGDEE6P    802        0.53          1.07
7SAYGDEE8P    775        0.52          1.58
7SAYGDEE2P    775        0.52          2.10
7SAYGDEEXP    772        0.51          2.61
...           ...         ...           ...
1FMCU0EZ8M      1        0.00        100.00
7FCTGAAL0P      1        0.00        100.00
WA1CAAGE9R      1        0.00        100.00
WA1G2BFZ5N      1        0.00        100.00
JN1CF0BB5P      1        0.00        100.00

[9529 rows x 3 columns]

============================================================
Column: County

            Count  Percentage  Cumulative %
County
King        79078       52.55         52.55
Snohomish   17307       11.50         64.05
Pierce      11542        7.67         71.72
Clark        8855        5.88         77.61
Thurston     5403        3.59         81.20
...           ...         ...           ...
Hennepin        1        0.00        100.00
Maui            1        0.00        100.00
Bell            1        0.00        100.00
Portsmouth      1        0.00        100.00
Suffolk         1        0.00        100.00

[183 rows x 3 columns]

============================================================
Column: City

               Count  Percentage  Cumulative %
City
Seattle        25678       17.06         17.06
Bellevue        7691        5.11         22.17
Redmond         5502        3.66         25.83
Vancouver       5310        3.53         29.36
Bothell         4861        3.23         32.59
...              ...         ...           ...
Coronado           1        0.00        100.00
Suffolk            1        0.00        100.00
Middletown         1        0.00        100.00
Ewa Beach          1        0.00        100.00
Ellicott City      1        0.00        100.00

[683 rows x 3 columns]

============================================================
Column: State

        Count  Percentage  Cumulative %
State
WA     150141       99.77         99.77
CA         92        0.06         99.83
VA         35        0.02         99.86
MD         33        0.02         99.88
TX         20        0.01         99.89
NC         13        0.01         99.90
IL         12        0.01         99.91
AZ         11        0.01         99.92
CO         11        0.01         99.92
FL          9        0.01         99.93
NJ          9        0.01         99.94
OR          8        0.01         99.94
HI          8        0.01         99.95
CT          7        0.00         99.95
NY          7        0.00         99.96
NV          6        0.00         99.96
SC          6        0.00         99.96
DC          5        0.00         99.97
GA          5        0.00         99.97
MO          4        0.00         99.97
NE          3        0.00         99.98
KY          3        0.00         99.98
AL          3        0.00         99.98
LA          3        0.00         99.98
MA          3        0.00         99.98
WY          2        0.00         99.98
OH          2        0.00         99.99
PA          2        0.00         99.99
IN          2        0.00         99.99
BC          2        0.00         99.99
AR          2        0.00         99.99
ID          2        0.00         99.99
UT          2        0.00         99.99
KS          2        0.00        100.00
MS          1        0.00        100.00
MT          1        0.00        100.00
DE          1        0.00        100.00
NH          1        0.00        100.00
AK          1        0.00        100.00
AP          1        0.00        100.00
MN          1        0.00        100.00

============================================================
Column: Postal_Code

             Count  Percentage  Cumulative %
Postal_Code
98052.0       3869        2.57          2.57
98012.0       2753        1.83           4.4
98033.0       2619        1.74          6.14
98006.0       2457        1.63          7.77
98004.0       2456        1.63          9.41
...            ...         ...           ...
23707.0          1         0.0         100.0
23435.0          1         0.0         100.0
21769.0          1         0.0         100.0
96706.0          1         0.0         100.0
21042.0          1         0.0         100.0

[824 rows x 3 columns]

============================================================
Column: Model_Year

            Count  Percentage  Cumulative %
Model_Year
2023        37079       24.64         24.64
2022        27799       18.47         43.11
2021        18684       12.42         55.53
2018        14441        9.60         65.13
2020        11294        7.51         72.63
2019        10717        7.12         79.75
2017         8574        5.70         85.45
2016         5650        3.75         89.21
2015         4934        3.28         92.48
2013         4566        3.03         95.52
2014         3613        2.40         97.92
2012         1633        1.09         99.00
2011          796        0.53         99.53
2024          642        0.43         99.96
2010           24        0.02         99.98
2008           19        0.01         99.99
2000            8        0.01         99.99
1999            4        0.00        100.00
2002            2        0.00        100.00
1998            1        0.00        100.00
2003            1        0.00        100.00
1997            1        0.00        100.00

============================================================
Column: Make

                      Count  Percentage  Cumulative %
Make
TESLA                 68983       45.84         45.84
NISSAN                13497        8.97         54.81
CHEVROLET             12026        7.99         62.80
FORD                   7614        5.06         67.86
BMW                    6439        4.28         72.14
KIA                    6198        4.12         76.26
TOYOTA                 5223        3.47         79.73
VOLKSWAGEN             4074        2.71         82.44
VOLVO                  3536        2.35         84.79
JEEP                   3292        2.19         86.98
HYUNDAI                3171        2.11         89.08
AUDI                   3006        2.00         91.08
CHRYSLER               2642        1.76         92.84
RIVIAN                 2483        1.65         94.49
MERCEDES-BENZ          1054        0.70         95.19
PORSCHE                1028        0.68         95.87
MITSUBISHI              849        0.56         96.43
HONDA                   810        0.54         96.97
FIAT                    806        0.54         97.51
MINI                    791        0.53         98.03
POLESTAR                764        0.51         98.54
SUBARU                  623        0.41         98.95
SMART                   274        0.18         99.14
LINCOLN                 229        0.15         99.29
JAGUAR                  228        0.15         99.44
LUCID                   190        0.13         99.57
CADILLAC                176        0.12         99.68
LEXUS                   138        0.09         99.78
MAZDA                   136        0.09         99.87
GENESIS                 107        0.07         99.94
LAND ROVER               47        0.03         99.97
FISKER                   17        0.01         99.98
ALFA ROMEO               12        0.01         99.99
AZURE DYNAMICS            9        0.01         99.99
TH!NK                     5        0.00        100.00
WHEEGO ELECTRIC CARS      3        0.00        100.00
BENTLEY                   2        0.00        100.00

============================================================
Column: Model

             Count  Percentage  Cumulative %
Model
MODEL Y      28502       18.94         18.94
MODEL 3      27709       18.41         37.35
LEAF         13187        8.76         46.12
MODEL S       7611        5.06         51.17
BOLT EV       5733        3.81         54.98
...            ...         ...           ...
745LE            2        0.00        100.00
918              1        0.00        100.00
FLYING SPUR      1        0.00        100.00
S-10 PICKUP      1        0.00        100.00
BENTAYGA         1        0.00        100.00

[127 rows x 3 columns]

============================================================
Column: EV_Type

                                         Count  Percentage  Cumulative %
EV_Type
Battery Electric Vehicle (BEV)          116807       77.62         77.62
Plug-in Hybrid Electric Vehicle (PHEV)   33675       22.38        100.00

============================================================
Column: CAFV_Eligibility

,Count,Percentage,Cumulative %
CAFV_Eligibility,,,
Eligibility unknown as battery range has not been researched,69698,46.32,46.32
Clean Alternative Fuel Vehicle Eligible,62951,41.83,88.15
Not eligible due to low battery range,17833,11.85,100.00

============================================================
Column: Electric_Range

                Count  Percentage  Cumulative %
Electric_Range
0               69698       46.32         46.32
215              6490        4.31         50.63
220              4125        2.74         53.37
84               4023        2.67         56.04
238              3611        2.40         58.44
...               ...         ...           ...
74                  4        0.00        100.00
95                  3        0.00        100.00
11                  2        0.00        100.00
57                  1        0.00        100.00
59                  1        0.00        100.00

[102 rows x 3 columns]

============================================================
Column: Base_MSRP

            Count  Percentage  Cumulative %
Base_MSRP
0          147027       97.70         97.70
69900        1441        0.96         98.66
31950         399        0.27         98.93
52900         218        0.14         99.07
32250         152        0.10         99.17
59900         134        0.09         99.26
54950         133        0.09         99.35
39995         117        0.08         99.43
36900         101        0.07         99.49
44100          97        0.06         99.56
45600          84        0.06         99.62
64950          83        0.06         99.67
33950          74        0.05         99.72
52650          68        0.05         99.76
34995          64        0.04         99.81
36800          53        0.04         99.84
55700          50        0.03         99.88
53400          34        0.02         99.90
110950         21        0.01         99.91
90700          19        0.01         99.92
81100          19        0.01         99.94
98950          19        0.01         99.95
102000         17        0.01         99.96
75095          15        0.01         99.97
184400         11        0.01         99.98
43700          10        0.01         99.99
109000          7        0.00         99.99
89100           6        0.00         99.99
91250           5        0.00        100.00
32995           3        0.00        100.00
845000          1        0.00        100.00

============================================================
Column: Legislative District

                      Count  Percentage  Cumulative %
Legislative District
41                     9969        6.62          6.62
45                     9171        6.09         12.72
48                     8419        5.59         18.31
1                      6510        4.33         22.64
36                     6494        4.32         26.96
5                      6348        4.22         31.17
46                     5955        3.96         35.13
11                     5837        3.88         39.01
43                     5789        3.85         42.86
37                     4498        2.99         45.85
34                     4429        2.94         48.79
18                     4012        2.67         51.46
44                     3790        2.52         53.97
22                     3707        2.46         56.44
21                     3652        2.43         58.86
32                     3627        2.41         61.27
33                     3422        2.27         63.55
40                     3349        2.23         65.77
23                     3308         2.2         67.97
26                     2992        1.99         69.96
47                     2685        1.78         71.74
10                     2624        1.74         73.49
31                     2592        1.72         75.21
17                     2576        1.71         76.92
39                     2173        1.44         78.37
27                     2121        1.41         79.78
24                     2104         1.4         81.17
42                     2078        1.38         82.56
35                     2057        1.37         83.92
49                     2035        1.35         85.27
28                     1958         1.3         86.58
30                     1776        1.18         87.76
2                      1636        1.09         88.84
8                      1523        1.01         89.86
25                     1517        1.01         90.86
38                     1411        0.94          91.8
6                      1344        0.89         92.69
12                     1338        0.89         93.58
20                     1294        0.86         94.44
4                      1174        0.78         95.22
13                      982        0.65         95.88
29                      972        0.65         96.52
14                      963        0.64         97.16
19                      886        0.59         97.75
9                       839        0.56         98.31
16                      756         0.5         98.81
3                       732        0.49          99.3
7                       696        0.46         99.76
15                      362        0.24         100.0

============================================================
Column: Vehicle_ID

            Count  Percentage  Cumulative %
Vehicle_ID
249675142       1         0.0           0.0
233928502       1         0.0           0.0
229675939       1         0.0           0.0
104714466       1         0.0           0.0
185498386       1         0.0           0.0
...           ...         ...           ...
251204075       1         0.0         100.0
241344414       1         0.0         100.0
180705626       1         0.0         100.0
240473950       1         0.0         100.0
207667589       1         0.0         100.0

[150482 rows x 3 columns]

============================================================
Column: Vehicle_Location

                                Count  Percentage  Cumulative %
Vehicle_Location
POINT (-122.12302 47.67668)      3876        2.58          2.58
POINT (-122.1876761 47.820517)   2753        1.83          4.41
POINT (-122.20264 47.6785)       2619        1.74          6.15
POINT (-122.16937 47.571015)     2457        1.63          7.78
POINT (-122.201905 47.61385)     2456        1.63          9.41
...                               ...         ...           ...
POINT (-76.34389 36.829805)         1        0.00        100.00
POINT (-76.42047 36.87704)          1        0.00        100.00
POINT (-77.54559 39.44235)          1        0.00        100.00
POINT (-158.019325 21.33516)        1        0.00        100.00
POINT (-76.83207 39.276485)         1        0.00        100.00

[822 rows x 3 columns]

============================================================
Column: Electric_Utility

,Count,Percentage,Cumulative %
Electric_Utility,,,
PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),55637,36.97,36.97
PUGET SOUND ENERGY INC,29865,19.85,56.82
CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),27268,18.12,74.94
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLARK COUNTY - (WA),8643,5.74,80.68
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY,6622,4.40,85.08
PUGET SOUND ENERGY INC||PUD NO 1 OF WHATCOM COUNTY,3443,2.29,87.37
BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||INLAND POWER & LIGHT COMPANY,2244,1.49,88.86
BONNEVILLE POWER ADMINISTRATION||PUD 1 OF SNOHOMISH COUNTY,1341,0.89,89.75
PACIFICORP,1102,0.73,90.49
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF BENTON COUNTY,1048,0.70,91.18
MODERN ELECTRIC WATER COMPANY,917,0.61,91.79
PUD NO 1 OF CHELAN COUNTY,863,0.57,92.37
BONNEVILLE POWER ADMINISTRATION||PUGET SOUND ENERGY INC||PUD NO 1 OF JEFFERSON COUNTY,854,0.57,92.93
BONNEVILLE POWER ADMINISTRATION||ORCAS POWER & LIGHT COOP,840,0.56,93.49
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF COWLITZ COUNTY,762,0.51,94.00
BONNEVILLE POWER ADMINISTRATION||CITY OF RICHLAND - (WA),752,0.50,94.50
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLALLAM COUNTY,731,0.49,94.98
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 3 OF MASON COUNTY,615,0.41,95.39
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF GRAYS HARBOR COUNTY,518,0.34,95.74
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF FRANKLIN COUNTY,479,0.32,96.05
PUD NO 2 OF GRANT COUNTY,452,0.30,96.35
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||ELMHURST MUTUAL POWER & LIGHT CO|PENINSULA LIGHT COMPANY,385,0.26,96.61
NON WASHINGTON STATE ELECTRIC UTILITY,338,0.22,96.83
AVISTA CORP,323,0.21,97.05
BONNEVILLE POWER ADMINISTRATION||VERA IRRIGATION DISTRICT #15,307,0.20,97.25
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 1 OF LEWIS COUNTY,294,0.20,97.45
PUD NO 1 OF DOUGLAS COUNTY,293,0.19,97.64
BONNEVILLE POWER ADMINISTRATION||INLAND POWER & LIGHT COMPANY,276,0.18,97.83
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF KLICKITAT COUNTY,239,0.16,97.99
NO KNOWN ELECTRIC UTILITY SERVICE,209,0.14,98.12
BONNEVILLE POWER ADMINISTRATION||PACIFICORP||PUD NO 1 OF CLARK COUNTY - (WA),203,0.13,98.26
CITY OF TACOMA - (WA)||TANNER ELECTRIC COOP,202,0.13,98.39
BONNEVILLE POWER ADMINISTRATION||CITY OF PORT ANGELES - (WA),185,0.12,98.52
CITY OF BLAINE - (WA)||PUD NO 1 OF WHATCOM COUNTY,179,0.12,98.64
BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF PACIFIC COUNTY,177,0.12,98.75
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF SKAMANIA CO,164,0.11,98.86
BONNEVILLE POWER ADMINISTRATION||TOWN OF STEILACOOM|CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY,153,0.10,98.96
BONNEVILLE POWER ADMINISTRATION||CITY OF CENTRALIA - (WA)|CITY OF TACOMA - (WA),152,0.10,99.07
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||LAKEVIEW LIGHT & POWER|PENINSULA LIGHT COMPANY,130,0.09,99.15
"OKANOGAN COUNTY ELEC COOP, INC",120,0.08,99.23
BONNEVILLE POWER ADMINISTRATION||CITY OF ELLENSBURG - (WA),104,0.07,99.30
"BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||OHOP MUTUAL LIGHT COMPANY, INC|PENINSULA LIGHT COMPANY",99,0.07,99.37
PUD NO 1 OF OKANOGAN COUNTY,89,0.06,99.43
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PARKLAND LIGHT & WATER COMPANY|PENINSULA LIGHT COMPANY,89,0.06,99.48
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 1 OF MASON COUNTY,87,0.06,99.54
BONNEVILLE POWER ADMINISTRATION||PACIFICORP||BENTON RURAL ELECTRIC ASSN,85,0.06,99.60
BONNEVILLE POWER ADMINISTRATION||CITY OF MILTON - (WA)|CITY OF TACOMA - (WA),68,0.05,99.64
BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||PUD NO 1 OF ASOTIN COUNTY,60,0.04,99.68
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF WAHKIAKUM COUNTY,49,0.03,99.72
PUD NO 1 OF PEND OREILLE COUNTY,47,0.03,99.75
PUD NO 1 OF WHATCOM COUNTY,41,0.03,99.77
BONNEVILLE POWER ADMINISTRATION||TOWN OF RUSTON - (WA)|CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY,41,0.03,99.80
"BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||BIG BEND ELECTRIC COOP, INC",37,0.02,99.83
CITY OF CHENEY - (WA),36,0.02,99.85
BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||BENTON RURAL ELECTRIC ASSN|PENINSULA LIGHT COMPANY,33,0.02,99.87
"BONNEVILLE POWER ADMINISTRATION||BIG BEND ELECTRIC COOP, INC",30,0.02,99.89
BONNEVILLE POWER ADMINISTRATION||TOWN OF EATONVILLE - (WA)|CITY OF TACOMA - (WA),25,0.02,99.91
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF MASON COUNTY|PUD NO 1 OF JEFFERSON COUNTY,20,0.01,99.92
CITY OF TACOMA - (WA),18,0.01,99.93
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF KITTITAS COUNTY,15,0.01,99.94
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF FERRY COUNTY,15,0.01,99.95
"BONNEVILLE POWER ADMINISTRATION||PACIFICORP||COLUMBIA RURAL ELEC ASSN, INC",14,0.01,99.96
BONNEVILLE POWER ADMINISTRATION||CITY OF MCCLEARY - (WA),14,0.01,99.97
"BONNEVILLE POWER ADMINISTRATION||COLUMBIA RURAL ELEC ASSN, INC",13,0.01,99.98
CITY OF CHEWELAH,6,0.00,99.99
CITY OF SUMAS - (WA)||PUD NO 1 OF WHATCOM COUNTY,5,0.00,99.99
BONNEVILLE POWER ADMINISTRATION||BENTON RURAL ELECTRIC ASSN,3,0.00,99.99
PORTLAND GENERAL ELECTRIC CO,3,0.00,99.99
"BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||ALDER MUTUAL LIGHT CO, INC|PENINSULA LIGHT COMPANY",2,0.00,99.99
BONNEVILLE POWER ADMINISTRATION||CITY OF COULEE DAM - (WA),2,0.00,100.00
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF ASOTIN COUNTY||INLAND POWER & LIGHT COMPANY,2,0.00,100.00
CITY OF SEATTLE - (WA),1,0.00,100.00
BONNEVILLE POWER ADMINISTRATION||PENINSULA LIGHT COMPANY,1,0.00,100.00
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF ASOTIN COUNTY,1,0.00,100.00
"BONNEVILLE POWER ADMINISTRATION||NESPELEM VALLEY ELEC COOP, INC",1,0.00,100.00
BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF JEFFERSON COUNTY,1,0.00,100.00

============================================================
Column: Census_Tract

               Count  Percentage  Cumulative %
Census_Tract
53033028200.0   1758        1.17          1.17
53033028500.0    963        0.64          1.81
53033032321.0    699        0.46          2.27
53033009300.0    558        0.37          2.64
53033026200.0    531        0.35           3.0
...              ...         ...           ...
6095252801.0       1         0.0         100.0
51800075203.0      1         0.0         100.0
24021752602.0      1         0.0         100.0
15003008410.0      1         0.0         100.0
24027602201.0      1         0.0         100.0

[2080 rows x 3 columns]

============================================================
Column: Legislative_District

                      Count  Percentage  Cumulative %
Legislative_District
41                     9969        6.62          6.62
45                     9171        6.09         12.72
48                     8419        5.59         18.31
1                      6510        4.33         22.64
36                     6494        4.32         26.96
5                      6348        4.22         31.17
46                     5955        3.96         35.13
11                     5837        3.88         39.01
43                     5789        3.85         42.86
37                     4498        2.99         45.85
34                     4429        2.94         48.79
18                     4012        2.67         51.46
44                     3790        2.52         53.97
22                     3707        2.46         56.44
21                     3652        2.43         58.86
32                     3627        2.41         61.27
33                     3422        2.27         63.55
40                     3349        2.23         65.77
23                     3308         2.2         67.97
26                     2992        1.99         69.96
47                     2685        1.78         71.74
10                     2624        1.74         73.49
31                     2592        1.72         75.21
17                     2576        1.71         76.92
39                     2173        1.44         78.37
27                     2121        1.41         79.78
24                     2104         1.4         81.17
42                     2078        1.38         82.56
35                     2057        1.37         83.92
49                     2035        1.35         85.27
28                     1958         1.3         86.58
30                     1776        1.18         87.76
2                      1636        1.09         88.84
8                      1523        1.01         89.86
25                     1517        1.01         90.86
38                     1411        0.94          91.8
6                      1344        0.89         92.69
12                     1338        0.89         93.58
20                     1294        0.86         94.44
4                      1174        0.78         95.22
13                      982        0.65         95.88
29                      972        0.65         96.52
14                      963        0.64         97.16
19                      886        0.59         97.75
9                       839        0.56         98.31
16                      756         0.5         98.81
3                       732        0.49          99.3
7                       696        0.46         99.76
15                      362        0.24         100.0

In [114]:
df.drop(columns=["Legislative District"], inplace=True)

In [115]:
df.columns

Index(['VIN', 'County', 'City', 'State', 'Postal_Code', 'Model_Year', 'Make',
       'Model', 'EV_Type', 'CAFV_Eligibility', 'Electric_Range', 'Base_MSRP',
       'Vehicle_ID', 'Vehicle_Location', 'Electric_Utility', 'Census_Tract',
       'Legislative_District'],
      dtype='str')

## Save the Dataset

In [119]:
from pathlib import Path

folders = [
    "../datas/raw",
    "../datas/cleaned",
    "../datas/processed",
    "../outputs/figures",
    "../outputs/tables",
    "../reports",
    "../models"
]

for folder in folders:
    Path(folder).mkdir(parents=True, exist_ok=True)

print("✅ All project folders created successfully!")

✅ All project folders created successfully!

In [120]:
df.to_csv("../datas/cleaned/ev_cleaned.csv", index=False)

print("✅ Dataset saved successfully!")

✅ Dataset saved successfully!

In [121]:
df

,VIN,County,City,State,Postal_Code,Model_Year,Make,Model,EV_Type,CAFV_Eligibility,Electric_Range,Base_MSRP,Vehicle_ID,Vehicle_Location,Electric_Utility,Census_Tract,Legislative_District
0,KM8K33AGXL,King,Seattle,WA,98103.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258,0,249675142,POINT (-122.34301 47.659185),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033004800.0,43
1,1C4RJYB61N,King,Bothell,WA,98011.0,2022,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,233928502,POINT (-122.20578 47.762405),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),53033021804.0,1
2,1C4RJYD61P,Yakima,Yakima,WA,98908.0,2023,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,229675939,POINT (-120.6027202 46.5965625),PACIFICORP,53077002900.0,14
3,5YJ3E1EA7J,King,Kirkland,WA,98034.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,104714466,POINT (-122.209285 47.71124),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),53033021903.0,45
4,WBY7Z8C5XJ,Thurston,Olympia,WA,98501.0,2018,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,97,0,185498386,POINT (-122.89692 47.043535),PUGET SOUND ENERGY INC,53067010700.0,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150477,WBY43AW05P,Grays Harbor,Montesano,WA,98563.0,2023,BMW,I4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,251204075,POINT (-123.60535 46.982215),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF G...,53027000402.0,19
150478,5YJ3E1EB7P,King,Seattle,WA,98104.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,241344414,POINT (-122.329075 47.6018),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033008500.0,43
150479,5YJYGDEEXM,King,Seattle,WA,98109.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,180705626,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),53033007303.0,43
150480,5UXTA6C08P,Snohomish,Mountlake Terrace,WA,98043.0,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,240473950,POINT (-122.30842 47.78416),PUGET SOUND ENERGY INC,53061051200.0,1
150481,7SAYGDEF8N,Skagit,Mount Vernon,WA,98273.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,207667589,POINT (-122.338975 48.41333),PUGET SOUND ENERGY INC,53057952304.0,40

THE END